### ISSUE TITLE
Spread example image

### ISSUE THREAD

**Issue by butor** [butor/blackbird#1]
![spread_example](https://cloud.githubusercontent.com/assets/11370278/6548498/64764de6-c5d1-11e4-855b-c2eebb3b782b.png)

**Comment by butor** [comment]
![email](https://cloud.githubusercontent.com/assets/11370278/8631347/4654c9dc-2742-11e5-9948-8c7c605b53e6.png)

**Comment by butor** [comment]
![volatility](https://cloud.githubusercontent.com/assets/11370278/8631423/973c89a6-2743-11e5-98b2-c1555611778b.png)

**Comment by butor** [comment]
![blackbird_logo](https://cloud.githubusercontent.com/assets/11370278/10808535/02230d46-7dc3-11e5-92d8-da15cae8c6e9.png)

**Comment by NateBrune** [comment]
Nice logo!

**Comment by butor** [comment]
@NateBrune Thanks!

**Comment by butor** [comment]
![new_chart](https://cloud.githubusercontent.com/assets/11370278/11164055/5863e750-8ab3-11e5-86fc-8f7bab6818df.png)
