### ISSUE TITLE
Issue with "make" and Linking blackbird

### ISSUE THREAD

**Issue by keanemachine** [butor/blackbird#101]
I'm using Ubuntu 14.04 and am running all the dependencies, including jansson 2.9.1.

I get the following when I run the make command:

Linking blackbird:
src/bitcoin.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [blackbird] Error 1

Thanks in advance for any advice.

**Comment by greatwolf** [comment]
Can you show the commands being used by running make with `VERBOSE=1`?

**Comment by keanemachine** [comment]
Running "make VERBOSE=1" returns this:

`Linking blackbird:
g++ -g  src/bitcoin.o src/check_entry_exit.o src/curl_fun.o src/db_fun.o src/main.o src/parameters.o src/result.o src/time_fun.o src/exchange/bitfinex.o src/exchange/bitstamp.o src/exchange/btce.o src/exchange/gemini.o src/exchange/itbit.o src/exchange/kraken.o src/exchange/okcoin.o src/exchange/poloniex.o src/utils/base64.o src/utils/send_email.o -o blackbird -lcrypto -ljansson -lcurl -lmysqlclient

src/bitcoin.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
make: *** [blackbird] Error 1`

Thanks for your help.

**Comment by greatwolf** [comment]
Can you do a clean build on this with or force all targets to rebuild? eg. `make -B VERBOSE=1`. Also show the output for

    which g++
    g++ --version

**Comment by keanemachine** [comment]
A clean build fixed it, thanks so much!
