### ISSUE TITLE
OKCoin trading fee change?

### ISSUE THREAD

**Issue by sschueller** [butor/blackbird#102]
According to: https://www.reddit.com/r/BitcoinMarkets/comments/5pjbsx/okcoin_will_start_charging_trading_fees_from/

I am not sure if this is new or not. There appears to already be a default trading fee configured for OKCoin of `0.0020`.

Do we have to make any adjustments?

**Comment by butor** [comment]
I think these adjustments don't apply to BTC/USD but only to BTC/CNY.
