### ISSUE TITLE
Chinese exchanges forced to stop margin trading

### ISSUE THREAD

**Issue by earleloxton** [butor/blackbird#108]
Hi Julien, awesome project! Congratz on your perseverence.  

How has PBOC's decision to prohibit margin trading affected the viability of Blackbird? Also: from reading the 8-page thread in Bitcointalk forum it seems you were returning around 2% per month (which is awesome for relatively riskfree trading)  What is your current performance?

Please keep up the great work!

**Comment by butor** [comment]
Thank you @earleloxton.

For the moment Blackbird only short sells through Bitfinex, which is based in Hong Kong. So the PBOC decision doesn't impact us so far. It would be the case if we start margin trade on China's exchanges such as OKCoin. Note that margin trading is not exactly prohibited but limited.

Regarding the performance, yes I had very good returns when I started the project back in 2014. Nowadays, the bitcoin market became more efficient and arbitrage opportunities are more difficult to capture. You can try to increase the trade frequency with the strategy parameters, meaning more frequent trades but with less profit each.
