### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by amq8** [butor/blackbird#11]
When tried compile a file im getting this error:

tradedesk@tradedesk-All-Series:~/Documents/blackbird2/blackbird-master$ make
g++ -c -g -Wall -O2  src/bitfinex.cpp -o src/bitfinex.o
src/bitfinex.cpp: In function ‘bool Bitfinex::isOrderComplete(CURL*, Parameters, int)’:
src/bitfinex.cpp:92:68: error: ‘json_boolean_value’ was not declared in this scope
   isComplete = !json_boolean_value(json_object_get(root, "is_live"));
                                                                    ^
make: *** [src/bitfinex.o] Error 1
tradedesk@tradedesk-All-Series:~/Documents/blackbird2/blackbird-master$ make
g++ -c -g -Wall -O2  src/bitfinex.cpp -o src/bitfinex.o
src/bitfinex.cpp: In function ‘bool Bitfinex::isOrderComplete(CURL*, Parameters, int)’:
src/bitfinex.cpp:92:68: error: ‘json_boolean_value’ was not declared in this scope
   isComplete = !json_boolean_value(json_object_get(root, "is_live"));
                                                                    ^
make: *** [src/bitfinex.o] Error 1

Do you have any reference to solve this problem?

**Comment by butor** [comment]
Hi @amq8,

Thank you for your interest. You need to use Jansson **v2.7**. The function ```json_boolean_value``` doesn't exist before 2.7 so that's why I think you have an older Jansson version. Please install Jansson v2.7 and try again.

Butor

**Comment by butor** [comment]
Issue solved by using Jansson 2.7
