### ISSUE TITLE
Error running make

### ISSUE THREAD

**Issue by MShahzadS** [butor/blackbird#112]
*** No rule to make target 'shell.o', needed by 'sqlite3'.  Stop.

I am trying to run it on linode cloud cli and installed all the necessary libraries required

**Comment by antony** [comment]
I'm having the exact same issue compiling this version on Raspberry PI.

I think there might be an issue with the Makefile (I'm not a C++ dev so I can't tell for sure)

**Comment by greatwolf** [comment]
Did you guys check issue #18 

Make to sync submodules with `git submodule update --init`

**Comment by antony** [comment]
Ah - I'll try this when I get home.

There isn't any information about this in the readme - If it works I'll add it in a PR.

**Comment by antony** [comment]
This seems to work well - I see you have already updated the readme! thanks :)
