### ISSUE TITLE
No cash available

### ISSUE THREAD

**Issue by kylegordon** [butor/blackbird#113]
Hi,

I'm new to the trading scene, but have been around Bitcoin for a while now. I am successfully connected to OKCoin, Bitfinex, Kraken and Bitstamp, with around 55USD in each of them, with 0 BTC as advised. 

However, I keep getting told...
WARNING: Opportunity found but no cash available. Trade canceled

This is usually immediately after OKCoin/Bitfinex.

My config file is mostly the defaults, as below. Where am I going wrong?
```
# Program parameters
DemoMode=false
UseFullCash=false
CashForTesting=25.00
MaxExposure=100.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true
CACert=curl-ca-bundle.crt

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600
```

**Comment by butor** [comment]
Hi @kylegordon 

It happens when one of your exchanges (in your case, OKCoin or Bitfinex) doesn't have cash in their **trading** account. Make sure that your $55 are deposited in the trading accounts.

If it still doesn't work, please send us your Blackbird logfile (you can hide sensitive information).

**Comment by kylegordon** [comment]
Superstar @butor thank you :-)

'''
Waiting for the two orders to be filled...
Done
'''

I had my USD in the 'Exchange' wallet rather than the 'Margin' one. Once I transferred it and restarted, it pointed out I now had some cash in BitFinex at the header of the log file. I should have looked there first, to be honest.

It might be worth a wee update to the Readme to point out the importance of having funds in the right place within BitFinex itself.

In market now. Shall leave it ticking. Cheers!

**Comment by butor** [comment]
README updated. Thanks
