### ISSUE TITLE
What operating system does this run on?

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#114]
Hi I am new to bitcoin and new to programming. Is there a windows or mac version also? If not how do one compile it?

**Comment by SharkBeard** [comment]
There are instructions on how to compile it on the main page. You would have to adjust your commands based on the operating system.

**Comment by greatwolf** [comment]
Keep in mind the makefile assumes you're using a compiler that accepts command options compatible with gcc. This should work with clang on mac. For windows it definitely works with mingw, that's the environment I test against when making changes.

It *should* be compilable with visual studio but it's untested. If you're building with that toolchain you'll have to create your own nmake file or create a solutions file with blackbird's source.

**Comment by floopa** [comment]
@greatwolf Is it possible for me to rent a server that runs windows online? Can I have an IP that I connect to in my browser and access it from there?

**Comment by greatwolf** [comment]
I'm not aware of any services for that. Perhaps someone else might know.

**Comment by jw4wellness** [comment]
I am still trying to get my mingw to work on windows 10.
I see it can only short on Bitfinex while it can long on the others. What if the market changes to reverse and you need to do it the other way around?

**Comment by butor** [comment]
I'm not sure to understand your question. Can you please elaborate? You will always need to be short on one exchange (Bitfinex) and long on another one, regardless the direction of the market.

**Comment by SharkBeard** [comment]
@jw4wellness If the market reverses so Bitfinex is lower than Exchange B and you already had it up, you just made extra money. Then, it would not buy any because it can't short on the Exchange B and would look for options on other markets or wait until it Bitfinex is higher than Exchange B again.

**Comment by jw4wellness** [comment]
Thank you for answering

**Comment by jw4wellness** [comment]
I downloaded the balckbird source and Mingw as well. do I have to compile each .cpp file or is there just one that I need to compile? ![Uploading black 01.jpg…]()
To compile with MingW I opened a command prompt on windows 10 and then cd to the direcotry and then type g++ filname.cpp -o filename.exe correct?
Should I do that for each cpp file and am I on the right track, please?

**Comment by greatwolf** [comment]
Compiling each src file manually isn't the recommended way -- while you could do that it's very tedious. You should use the makefile with `mingw32-make`. You'll also need openssl 1.0.x, curl and jansson. Each of those projects of their own respective build instructions so I won't go into it here.

Since windows doesn't have a standard location on where those dependencies go (you can put it wherever you want) you will have to point the makefile on where blackbird can find them. In the context of C++ apps, this means include headers and import libraries. You specify it using `INC_DIR` and `LIB_DIR` make variables.

Full example, I have the dependencies in the follow directories:

###include files location
 - G:/openssl-1.0.1g/include
 - G:/oss/jansson/install/include
 - G:/oss/curl-7.23.1-devel/include

###dll or import library location
 - G:/openssl-1.0.1g/lib
 - G:/oss/jansson/install/lib
 - G:/oss/curl-7.23.1-devel/bin

To build, I would run this command from blackbird's root project's working directory:

    mingw32-make VERBOSE=1 INC_DIR="-I G:/openssl-1.0.1g/include -I G:/oss/jansson/install/include -I G:/oss/curl-7.23.1-devel/include" LIB_DIR="-L G:/openssl-1.0.1g/lib -L G:/oss/jansson/install/lib -L G:/oss/curl-7.23.1-devel/bin"

**Comment by jw4wellness** [comment]
Thank you for helping I just can't get it going. Is there an exe version that one could download of blackbird?

**Comment by greatwolf** [comment]
I suppose I could add precompiled binary under github release section if trust isn't a concern for you. Will have to tag it with a release version. @butor any thoughts on this?

**Comment by butor** [comment]
@greatwolf: while it's fine to directly send a binary to @jw4wellness, I don't think we should put a Windows binary on the GitHub page. This will open the door to people with no interest in understanding how Blackbird works, and who just want to make money by double clicking on it. This is too dangerous. Blackbird remains an experimental open source project and I want the audience to have the technical skills (and interest) to at least install the needed libraries and compile the code. Does that make sense? Thanks.

**Comment by antony** [comment]
@floopa @jw4wellness If you're about to rent a windows server and run this, why not just rent a linux server and follow the instructions in the readme, it's much easier, and you avoid all these trust issues.

it's unlikely somebody will want to maintain a recent .exe even if @butor and @greatwolf are prepared to put one on the downloads page. personally I recompile the latest source every week or so.

also as a side-note, unless you invest a LOT of cash, you will probably lose money renting a server. Personally I run it on a raspberry pi v1 connected to a usb port on the back of my TV :)

**Comment by greatwolf** [comment]
Here's the precompiled binary off the latest head built w/ mingw-4.9.1. It includes all the .dll's needed to run blackbird. The executables are already stripped to reduce space.

For some reason, github doesn't like .zip so I had to attach it as .tar.gz instead.

[blackbird_precompiled.tar.gz](https://github.com/butor/blackbird/files/832563/blackbird_precompiled.tar.gz)

**Comment by oliverDOTnet** [comment]
I would like to add that you can run native linux-commands on Windows with the "Windows Subsystem for Linux". You just need an x64 Windows 10 "Anniversary Update" build 14393 or later ;)
https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

Then you can open the bash and run the commands for Ubuntu as described in the Readme.md

![blackbird-windows](https://cloud.githubusercontent.com/assets/5018090/24081525/dda951a4-0cb5-11e7-968f-4055cfa3e65b.JPG)

**Comment by jw4wellness** [comment]
Dear Friends,
Thank You so much for your help with this.
I was offline for some time, moving, work, sick etc... I enjoy learning with you. 
@greatwolf Thank you for the binary. I downloaded it and ran it. still figuring out what goes where.
@oliverDOTnet Thank you. I will do that too. 
I got the trading accounts opened just need to setup black bird.

**Comment by jw4wellness** [comment]
It is very stimulating. The learning curve is so steep for me. Learning bitcoin and all the trading terms and options. Learning programming and all the info on blackbird. Thank you for all the help. 

The binary I installed that you so kindly shared seems to have an issue with bitfinex - in front of order. Negative order number. Then it doesn't close the order. If you could please now upload the new version, I could learn from that? 
Thank you in advance.

**Comment by jw4wellness** [comment]
Hi I am doing it over to make sure I got everything. That I didn't miss anything.
Would it be okay if I write the wiki for the project so that other complete beginners can learn from it? That will cause more support for the blackbird project, since the other projects does not offer a guide that a 13 year old could understand. They are all using terms that only experienced programmers understand.

So anyway, the link is broken for Crypto 
![black 02](https://cloud.githubusercontent.com/assets/26123052/25966936/e2cd1fcc-3662-11e7-92c5-ef6165a48ab1.jpg)
Where can I find the crypto please?

**Comment by greatwolf** [comment]
Thanks for pointing out the dead openssl dead link in readme. That's fixed now. Regarding wiki, yes feel free to add documentation there on how to build blackbird on windows.

**Comment by jw4wellness** [comment]
so crypto is now replaced with openssl?

**Comment by greatwolf** [comment]
Crypto was always referring to OpenSSL, it just meant what cryptographic library was used.

**Comment by xgdgsc** [comment]
I' ve written cmake build scripts at https://github.com/xgdgsc/blackbird . I don' t know if you are interested in adopting cmake. I would start a PR if you like.

**Comment by butor** [comment]
Thanks @xgdgsc. @greatwolf confirmed that we should indeed move over to `cmake`. It will help building on different platforms. So yes please start a PR, with updated information in the README file. Many thanks.

@greatwolf also said:
>  CMake will have to be added as one of the build requirements, build commands will have to be changed etc.
