### ISSUE TITLE
Trailing Spreads

### ISSUE THREAD

**Issue by jackeown** [butor/blackbird#120]
I think I understand most of the log output, but how are "trailing spreads" used and what is the point of them?  Are they there so you don't immediately buy in and instead wait for the spread to increase more?  If so, how does it decide when to actually trade?

**Comment by butor** [comment]
Yes I know the _trailing spread_ concept is not entirely explained in the README file. I will try to add a specific section within the next couple of days.

Meanwhile, there is a pretty good explanation on how it works on issue #12. But your first understanding is correct: Blackbird waits if the spread continues to increase.

**Comment by jackeown** [comment]
Thank you.  That makes a bit more sense now.
