### ISSUE TITLE
Log seems to hang

### ISSUE THREAD

**Issue by Naki21** [butor/blackbird#122]
How Long does it take to print the log? I run ./blackbird and get 
`Log file generated: blackbird_log_20170311_181900.log
Blackbird is running... (pid 14606)
`

But no log file is ever actually made and that is all that shows up in the terminal. I only have 2 exchange APIs added and the rest are black. I'm running Ubuntu 16.04. Tried renaming stop after no trade. Nothing. Do I need funding in the accounts for demo mode? Let me know if you need more info

**Comment by greatwolf** [comment]
Can you include the blackbird.conf? (omitting any API keys in there)

**Comment by Naki21** [comment]
`# Blackbird Bitcoin Arbitrage
# Configuration file


# Program parameters
DemoMode=true
UseFullCash=false
CashForTesting=00.00
MaxExposure=25000.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true
CACert=curl-ca-bundle.crt

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600

# Email settings
SendEmail=false
SenderAddress=
SenderUsername=
SenderPassword=
SmtpServerAddress=
ReceiverAddress=

# Database settings
DBFile=blackbird.db
`

The rest is the exchange API info. So it looks like it generated the logs after I logged off. There are now log and result files from the time I first tested it. But again, the terminal hangs when I run the program.  As for the disto, it's Ubuntu 16.04. (I mentioned it above, however if you are looking for something more specific please elaborate :))

**Comment by Naki21** [comment]
Wait, is the log supposed to output in the terminal? Cause if not I think its working.

**Comment by butor** [comment]
No, the log is only written into the file specified when you start Blackbird. In your example:
```
Log file generated: blackbird_log_20170311_181900.log Blackbird is running... (pid 14606)
```
Then _blackbird_log_20170311_181900.log_ is the log file, in the working directory.

**Comment by Naki21** [comment]
Ahhh then I do not have a problem lol. You can close issue
