### ISSUE TITLE
Can't connect to Poloniex

### ISSUE THREAD

**Issue by boblin** [butor/blackbird#123]
Hi all,

blackbird seems to not work with **Poloniex** for me. 

I modified **main.cpp** like [here](https://github.com/butor/blackbird/issues/117#issuecomment-285323753). Then I rebuild blackbird with `make -B VERBOSE=1`. 

Now I see in log `Poloniex:    0,00 USD` which is not true. Other accounts, like Bitstamp looks OK (`Bitstamp:    20,00 USD`)

Interesting is that if I change login credentials for Bitstamp I see Error: `<Bitstamp> Error with the credentials.`. But I can't see any errors on Poloniex with wrong credentials.

Is anyone using blackbird with Poloniex successfully?

Thank you

**Comment by greatwolf** [comment]
Blackbird isn't authenticating poloniex correctly. It looks like someone just copied and paste the code from another exchange implementation. It's using the wrong hmac hash function, passing the signature incorrectly, the expected headers aren't being supplied in the request and it's not checking the `error` field in the json response(which is how poloniex signals for errors).

There are probably other things wrong with it but the short answer is it seems to be a placeholder -- not a real implementation.

**Comment by butor** [comment]
@greatwolf is right. The API functions in _poloniex.cpp_ have the following comment:
``` 
  // TODO
  // This function needs to be implemented
  // The code below is given as a general guideline but needs to be rewritten
  // to match the Poloniex API
```

**Comment by boblin** [comment]
Thank you for quick answer :+1:

**Comment by rasheedmoore** [comment]
having the same issue getting (API not implemented), any timeline on the fix?

**Comment by butor** [comment]
HI @rasheedmoore, no timeline for the moment.
