### ISSUE TITLE
Why using getActivePos() while exiting the market?

### ISSUE THREAD

**Issue by yzuyhp** [butor/blackbird#124]
Hello, why do you use `getActivePos()` while exiting the market?
Instead, could we save `longVolume` and `shortVolume` while entering the market and operate in the opposite direction while exiting the market?

**Comment by jackeown** [comment]
What would be the benefit of doing that?

**Comment by butor** [comment]
Because we want to make sure that we get the accurate position from the exchange. The volumes we get are probably not exactly the ones we wanted to trade (slippage, fees, etc). So:

```
double volumeLong = res.exposure / btcVec[res.idExchLong].getAsk();
double volumeShort = res.exposure / btcVec[res.idExchShort].getBid();
```

are theoretical, but:

```
btcUsed[i] = getActivePos[i](params);
```

is the actual and accurate position that was traded on the exchange.
