### ISSUE TITLE
make and libs

### ISSUE THREAD

**Issue by bg560581** [butor/blackbird#125]
I am trying to get this program up and running but I keep getting an error that says:
Compiling src/curl_fun.o:
In file included from src/curl_fun.cpp:4:
./src/jansson.h:56:5: error: invalid token at start of a preprocessor expression
#if JSON_INTEGER_IS_LONG_LONG
    ^
./src/jansson_config.h:33:35: note: expanded from macro
      'JSON_INTEGER_IS_LONG_LONG'
#define JSON_INTEGER_IS_LONG_LONG @json_have_long_long@
                                  ^
1 error generated.
make: *** [src/curl_fun.o] Error 1

I am pretty sure it is because, in the readme it says that I need libssl-dev, libjansson-dev, libcurl4-openssl-dev, and libsqlite3-dev and I dont know how to get these libraries.
Thanks

**Comment by netobasilio** [comment]
If you using Ubuntu try:

sudo apt-get install libssl-dev libjansson-dev libcurl4-openssl-dev libsqlite3-dev sendemail make gcc g++

**Comment by greatwolf** [comment]
I think homebrew (`brew` command)is the package manager used on mac. See if you can install the dependences through that.

**Comment by bg560581** [comment]
I tried that but it didn't work. Ill have to try it again

**Comment by antony** [comment]
I'd recommend using the docker image. See the Readme for instructions - it will handle the build environment and tools for you in a lightweight container.

**Comment by greatwolf** [comment]
I'm going to close this unless you're still having problems.
