### ISSUE TITLE
Don't forget you're in the market.

### ISSUE THREAD

**Issue by jackeown** [butor/blackbird#126]
Currently, if you need to stop blackbird for some reason, when you restart it, it will not remember that it is in the market. (at least this is what I observed).  

Would it be helpful to have the program save the "result" object and then load it on startup if applicable?

(This would also be helpful because you could edit configuration in the middle of a trade.)

**Comment by bertrandfalguiere** [comment]
Is it fixed? Does Blackbird "remembers" it is in the market when stopped?

**Comment by jackeown** [comment]
It did last time I looked at anything...but I know there's been a lot of
development since I last checked in. (It should)
