### ISSUE TITLE
WARNING: X second(s) too late at Date

### ISSUE THREAD

**Issue by mcmunder** [butor/blackbird#128]
Thanks for creating blackbird! Awesome!

I'm running it locally in a docker container in demo mode right now and when I check the logs in the container I get a lot of these warnings: 

WARNING: 2 second(s) too late at 03/17/2017 10:27:42

What does the warning actually mean and (how) can I avoid this?

**Comment by butor** [comment]
Hi @mcmunder,

It means that your system is a bit slow. Usually it's because of network latency. You can increase the _analysis loop_ by increasing the parameter `GapSec`. That should fix the problem.

**Comment by playmobitch** [comment]
when increasing GapSec  blackbird could miss opportunities...what other solution do we have? running blackbird on a hosting like ovh with good bandwitch?

**Comment by mcmunder** [comment]
@playmobitch Yes, I can confirm that hosting/running it on AWS, Azure or similar solves the problem as well. No need to increase the GapSpec when running it there...
