### ISSUE TITLE
After several days no actions were taken

### ISSUE THREAD

**Issue by silverbucket** [butor/blackbird#134]
I have debug disabled, and have cash in two exchanges (bitfinex and bitstamp), blackbird reports the correct info during startup, and regularly updates the log every few seconds, yet after several full days of running, no actions have been taken at all. 

Config:
```
...
# Program parameters
DemoMode=false
UseFullCash=true
CashForTesting=25.00
MaxExposure=25000.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true
CACert=curl-ca-bundle.crt

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600
...
```

From the latest startup:
```
[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.50%

[ Current balances ]
   Bitfinex:    114.10 USD      0.000000 BTC
   Bitstamp:    115.93 USD      0.000000 BTC

[ Cash exposure ]
   FULL cash used!

[ 03/21/2017 12:48:42 ]
   Bitfinex:    1,089.80 / 1,089.90
   Bitstamp:    1,088.66 / 1,091.39
   ----------------------------
   Bitstamp/Bitfinex:   -0.15% [target  0.80%, min -0.15%, max -0.15%]

[ 03/21/2017 12:48:45 ]
   Bitfinex:    1,089.80 / 1,089.90
   Bitstamp:    1,088.70 / 1,091.32
   ----------------------------
   Bitstamp/Bitfinex:   -0.14% [target  0.80%, min -0.15%, max -0.14%]


...

[ 03/22/2017 09:43:00 ]
   Bitfinex:    1,053.80 / 1,054.00
   Bitstamp:    1,049.57 / 1,054.17
   ----------------------------
   Bitstamp/Bitfinex:   -0.04% [target  0.80%, min -0.53%, max  1.28%]

[ 03/22/2017 09:43:03 ]
   Bitfinex:    1,053.80 / 1,054.00
   Bitstamp:    1,049.57 / 1,054.17
   ----------------------------
   Bitstamp/Bitfinex:   -0.04% [target  0.80%, min -0.53%, max  1.28%]

```

**Comment by tonymorella** [comment]
Check the logs, did it ever hit the target? If not then no opportunity. Also this week the two you have are close, need to be on all of them to really get the benefit.

**Comment by butor** [comment]
At some point the spread was higher than your target (1.28% > 0.80%):
```
Bitstamp/Bitfinex:   -0.04% [target  0.80%, min -0.53%, max  1.28%]
```
But the system didn't trade for some reason. Maybe a lack of liquidity on one of the exchanges, or the opportunity quickly went away. You can find that in the log (e.g. look for the keywords _WARNING_, _trade_ or _order_).

**Comment by silverbucket** [comment]
Searching for "trade" came up with nothing, "order" came up with this:

```
[ 03/24/2017 21:12:33 ]
   Bitfinex:    960.01 / 961.30
   Bitstamp:    947.16 / 950.01
   ----------------------------
   Bitstamp/Bitfinex:    1.05% [target  0.80%, min -1.09%, max  1.57%]   trailin
g  1.14%  1/1
<Bitstamp> Looking for a limit price to fill 0.12 BTC...
<Bitstamp> order book: 4.52@$950.01
<Bitfinex> Looking for a limit price to fill 0.12 BTC...
<Bitfinex> order book: 7.93@$960.01

[ ENTRY FOUND ]
   Date & Time:       03/24/2017 21:12:33
   Exchange Long:     Bitstamp (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        $950.01 (target)
   Price Short:       $960.01 (target)
   Spread:            1.05%
   Cash used:         $112.95 on each exchange
   Exit Target:       -0.35%

<Bitstamp> Trying to send a "buy" limit order: 0.12@$950.01...
<Bitstamp> Done (order ID: 202,925,940)

<Bitfinex> Trying to send a "sell" limit order: 0.12@$960.01...
<Bitfinex> Done (order ID: 0)

Waiting for the two orders to be filled...
Done
```

Running for ~5 days, that's the only activity I saw. It looks like it tried to buy on both bitfinex and bitstamp, but only bitstamp worked (and it thought both worked?). Looking at my accounts, my bitstamp one now holds bitcoin and $2 USD. the bitfinex one still holds the $114 USD it started with.

I'm not really sure how to interpret the "target" as it always seems to be in the range given, but maybe I'm misunderstand what the range is. Also, now that one site hold USD and the other BTC, will it do anything anymore?

**Comment by butor** [comment]
Your log shows that there was a problem with filling the order on **Bitfinex**. Look at the order ID:

```
<Bitfinex> Trying to send a "sell" limit order: 0.12@$960.01...
<Bitfinex> Done (order ID: 0)
```
It might be related to the issue we had recently with `orderId` considered as `int` instead of `std::string` (issue #137). Could you please use the latest version of Blackbird and try again? Again, I'm not 100% sure it's related.

In any case, I think Blackbird should show the return code of the exchange if the order ID is 0. In the current situation we have no idea why the order ID is 0.
