### ISSUE TITLE
Add Korbit

### ISSUE THREAD

**Issue by tonymorella** [butor/blackbird#135]
Would like to see korbit.co.kr add, understand its KWR and not USD, but there is a lot of opportunities. Any reason a KWR to USD lookup could not be done in real-time?

**Comment by butor** [comment]
Blackbird is not designed to handle other currencies than USD. Looking up the USD/KRW rate is not enough: you need to trade your USD to KRW first.
On a BTC/USD arbitrage opportunity where Korbit is one of the exchanges, you would need to trade:

- arbitrage entry: USD → KRW → BTC
- arbitrage exit: BTC → KRW → USD

Plus, you need to hedge against the USD/KRW risk.
