### ISSUE TITLE
make: *** No rule to make target 'shell.o', needed by 'sqlite3'.  Stop.

### ISSUE THREAD

**Issue by mcmunder** [butor/blackbird#140]
I get the error `make: *** No rule to make target 'shell.o', needed by 'sqlite3'.  Stop.` when trying to compile blackbird with the provided Dockerfile. The issue did not exist about a week ago in case that helps...

Anyone else having this issue? Any ideas how to fix this?

**Comment by kazamatzuri** [comment]
you didn't check out the submodule for sqlite3. you need to run git clone with the --recursive flag

**Comment by alfonsoperez** [comment]
Thanks @kazamatzuri !, imho this can be closed.

http://stackoverflow.com/questions/1030169/easy-way-pull-latest-of-all-submodules

**Comment by realcotter** [comment]
hi all, could you list the exact command for 'run git clone with the --recursive flag' said by kazamatzuri in issue#140? thanks

**Comment by kazamatzuri** [comment]
god damnit i'm stupid;) ran into the same thing myself...

**Comment by kazamatzuri** [comment]
@realcotter: 
~~~
mkdir blackbird
cd blackbird
git clone --recursive  git://github.com/butor/blackbird.git .
~~~

**Comment by realcotter** [comment]
awesome thx
