### ISSUE TITLE
process stops no details

### ISSUE THREAD

**Issue by tonymorella** [butor/blackbird#141]
Since upgrading to the new patch last night the blackbird process keeps stopping after a few hours at random time. I can not find anything to explain why in any logs.  The is a stock ubuntu server image running on Amazon AWS. Anyone else having issues?

**Comment by greatwolf** [comment]
Can you try running this with gdb compiled with debug symbols(`-g`)? That'll help determine what's really happening, if it's crashing or the process just terminated gracefully. If it's really crashing, eg. segfaults etc., try to grab a backtrace using gdb's `bt` command.

**Comment by tonymorella** [comment]
FYI has not stopped since I setup systemd, have no idea why this would have made a difference.  FYI Started it with & to push to the background via and amazon ubuntu image. Will close this out for now.
