### ISSUE TITLE
Gemini Nonce Error

### ISSUE THREAD

**Issue by rasheedmoore** [butor/blackbird#143]
I was connecting successfully to Gemini, however after restarting the service I am now getting the following Nonce error.  

In addition I am having trouble getting blackbird to recognize my USD holdings in Bitfinex, I have transferred from Exchange to Margin to Funding none seem to show up.

<Gemini> Error with JSON: {"result": "error", "reason": "InvalidNonce", "message": "Nonce '1490722675108' has not increased since your last call to the Gemini API."}. Retrying...

**Comment by butor** [comment]
Hi @rasheedmoore, you might need to recreate your API keys because your nonce is out of sync. Please see issue #38 for a similar resolution.

**Comment by rasheedmoore** [comment]
Thank you, I removed the keys are restarted it and it seems to work, also when I moved USD to margin in Bitfinex it seems to work now you can close this out now.

**Comment by butor** [comment]
Thanks for the feedback.
