### ISSUE TITLE
cURL - Timeout was reached - bitstamp

### ISSUE THREAD

**Issue by Wuzzzel** [butor/blackbird#146]
Hi there, 
i have many of these errors in my log file:
`Error with cURL: Timeout was reached
  URL: https://www.bitstamp.net/api/ticker/
  Retry in 2 sec...

WARNING: 20 second(s) too late at 03/31/2017 06:36:09

Error with cURL: Timeout was reached
  URL: https://www.bitstamp.net/api/ticker/
  Retry in 2 sec...

WARNING: 19 second(s) too late at 03/31/2017 06:36:45

Error with cURL: Timeout was reached
  URL: https://www.bitstamp.net/api/ticker/
  Retry in 2 sec...

WARNING: 20 second(s) too late at 03/31/2017 06:37:15`

They come and go, sometimes each second and sometimes every 20min only. And there are these blank rows, which don't seam to be normal (Okay I see, the code Tag from GitHub don't show the 3-4 blank Lines between the errors).
`# Program parameters
DemoMode=false
UseFullCash=false
CashForTesting=20.00
MaxExposure=25000.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=false
CACert=curl-ca-bundle.crt

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600`
thanks for help

**Comment by butor** [comment]
Hi @Wuzzzel, it looks like you have connection issues with Bitstamp, which is not related to Blackbird code itself. Try to ping Bitstamp and check the latency:
```
ping www.bitstamp.com
```

**Comment by Wuzzzel** [comment]
thx for reply butor. Here is the ping output:

`root@1kv989k:~# ping www.bitstamp.com
PING 95lp8.x.incapdns.net (107.154.248.133) 56(84) bytes of data.
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=1 ttl=60 time=0.392 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=2 ttl=60 time=0.487 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=3 ttl=60 time=0.341 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=4 ttl=60 time=0.405 ms
...
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=136 ttl=60 time=0.356 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=137 ttl=60 time=0.358 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=138 ttl=60 time=0.361 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=139 ttl=60 time=0.362 ms
64 bytes from 107.154.248.133.ip.incapdns.net (107.154.248.133): icmp_seq=140 ttl=60 time=0.360 ms
^C
--- 95lp8.x.incapdns.net ping statistics ---
140 packets transmitted, 140 received, 0% packet loss, time 139081ms
rtt min/avg/max/mdev = 0.318/0.393/1.017/0.083 ms`

I have these errors with a vps from vultr.com and with one from a german distributor linevast.
Beside that, is it really normal that ~90% of the logfile are blank rows/lines?

**Comment by butor** [comment]
The ping looks OK. Do you consistently have that problem?
There are probably blank lines added somewhere that shouldn't be added when `Verbose=false`. Anyway you would get more information in the log with `Verbose=true`.

**Comment by Newar417** [comment]
Keep in mind that between you and Bitstamp sits Incapsula. They might not like your VPN connection. I had similar experiences with another bot at Poloniex (they use Cloudfare though). If you can, try with out the VPN. (I am not sure what you mean by 
>  a german distributor linevast.

Is this a VPN service too?)

**Comment by Wuzzzel** [comment]
@Newar417: I meant a Virtual Private Server (VPS). Linevast is just a german server distributor (I have mentioned it, because probably no one knows what I am talking about if not).
@butor: Yes, between every 30sec - 10min. I had disabled verbose, because I thought this would decrease the size of the logfile.

I will try different locations with vulture and if that doesn't work maybe aws or google.
ty

**Comment by greatwolf** [comment]
Well that pretty much explains it, it's as @Newar417 said. You didn't get an actual api response back from the exchange server, it looks like an incapsula response just to tell you the request didn't go through. Unfortunately, it's a regular html response but blackbird is trying to parse it as if it's json.
