### ISSUE TITLE
src/bitcoin.o: file not recognized: File format not recognized

### ISSUE THREAD

**Issue by bg560581** [butor/blackbird#147]
hey guys thanks for helping me out with the other issue I was having. the latest problem I am having is... 
Linking blackbird:
src/bitcoin.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:49: recipe for target 'blackbird' failed
make: *** [blackbird] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2

what I did was I followed the readme all the way through "make" command once it got there I wasnt able to proceed because of a jansson.h file. So I thought that if continued using Docker it may work. It continued the process and was working fine until I hit this "src/bitcoin.o: file not recognized." 

How do I fix this? Or where how do I get that Jansson.h file.
thanks

**Comment by greatwolf** [comment]
Can you check how bitcoin.cpp is compiled? Usually a link error like that means there's something wrong with the object file or it wasn't compiled correctly.

**Comment by bg560581** [comment]
Im sorry I am kinda new at this stuff that is what the file looks like when you open it? If not how do I check how it compiles

**Comment by greatwolf** [comment]
I would start by forcing a full rebuild with verbose on so you can see the commands executed:

    make -B VERBOSE=1

That ensures all the object files get recompiled. If you still get that linking error at the end you can check it using `nm` or objdump` command.

**Comment by bg560581** [comment]
so I ran the make -B verbose=1 command and this was my result

make -B VERBOSE=1
Compiling shell.o:
gcc -std=c99 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c extern/sqlite3/src/shell.c -o shell.o
Compiling sqlite3.o:
gcc -std=c99 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c extern/sqlite3/src/sqlite3.c -o sqlite3.o
Archiving libsqlite3.a:
ar rv libsqlite3.a sqlite3.o
r - sqlite3.o
Linking sqlite3:
gcc  -L . shell.o -o sqlite3 -lsqlite3  -lpthread -ldl
Compiling src/bitcoin.o:
c++ -Wall -pedantic -std=c++11 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/bitcoin.cpp -o src/bitcoin.o
Compiling src/check_entry_exit.o:
c++ -Wall -pedantic -std=c++11 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/check_entry_exit.cpp -o src/check_entry_exit.o
Compiling src/curl_fun.o:
c++ -Wall -pedantic -std=c++11 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/curl_fun.cpp -o src/curl_fun.o
src/curl_fun.cpp:5:10: fatal error: 'jansson.h' file not found
#include "jansson.h"
         ^
1 error generated.
make: *** [src/cmal_fun.o] Error 1-bash: MacBook-Pro-5:blackbird: command not found
MacBook-Pro-5:blackbird Ben$ Compiling shell.o:
-bash: Compiling: command not found
MacBook-Pro-5:blackbird Ben$ gcc -std=c99 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c extern/sqlite3/src/shell.c -o shell.o
MacBook-Pro-5:blackbird Ben$ Compiling sqlite3.o:
-bash: Compiling: command not found
MacBook-Pro-5:blackbird Ben$ gcc -std=c99 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c extern/sqlite3/src/sqlite3.c -o sqlite3.o
MacBook-Pro-5:blackbird Ben$ Archiving libsqlite3.a:
-bash: Archiving: command not found
MacBook-Pro-5:blackbird Ben$ ar rv libsqlite3.a sqlite3.o
r - sqlite3.o
MacBook-Pro-5:blackbird Ben$ r - sqlite3.o
-bash: r: command not found
MacBook-Pro-5:blackbird Ben$ Linking sqlite3:
-bash: Linking: command not found
MacBook-Pro-5:blackbird Ben$ gcc  -L . shell.o -o sqlite3 -lsqlite3  -lpthread -ldl
MacBook-Pro-5:blackbird Ben$ Compiling src/bitcoin.o:
-bash: Compiling: command not found
MacBook-Pro-5:blackbird Ben$ c++ -Wall -pedantic -std=c++11 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/bitcoin.cpp -o src/bitcoin.o
MacBook-Pro-5:blackbird Ben$ Compiling src/check_entry_exit.o:
-bash: Compiling: command not found
MacBook-Pro-5:blackbird Ben$ c++ -Wall -pedantic -std=c++11 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/check_entry_exit.cpp -o src/check_entry_exit.o
MacBook-Pro-5:blackbird Ben$ Compiling src/curl_fun.o:
-bash: Compiling: command not found
MacBook-Pro-5:blackbird Ben$ c++ -Wall -pedantic -std=c++11 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/curl_fun.cpp -o src/curl_fun.o
src/curl_fun.cpp:5:10: fatal error: 'jansson.h' file not found
#include "jansson.h"
         ^
1 error generated.
MacBook-Pro-5:blackbird Ben$ src/curl_fun.cpp:5:10: fatal error: 'jansson.h' file not found
-bash: src/curl_fun.cpp:5:10:: No such file or directory
MacBook-Pro-5:blackbird Ben$ #include "jansson.h"
MacBook-Pro-5:blackbird Ben$          ^
-bash: ^: command not found
MacBook-Pro-5:blackbird Ben$ 1 error generated.
-bash: 1: command not found
MacBook-Pro-5:blackbird Ben$ make: *** [src/cmal_fun.o] Error 1



I then used the nm on the shell.o command and this was the result



MacBook-Pro-5:blackbird Ben$ nm shell.o
0000000000012850 b _Argv0
                 U __DefaultRuneLocale
                 U ___bzero
                 U ___maskrune
                 U ___stack_chk_fail
                 U ___stack_chk_guard
                 U ___stderrp
                 U ___stdinp
                 U ___stdoutp
                 U ___tolower
                 U _access
000000000000b7e0 t _appendText
0000000000009be0 t _ascii_read_one_field
0000000000012858 b _bail_on_error
00000000000091c0 t _booleanValue
00000000000098b0 t _callback
0000000000012880 b _continuePrompt
0000000000009d00 t _csv_read_one_field
000000000000a280 t _display_stats
0000000000001520 t _do_meta_command
0000000000011260 s _do_meta_command.aCtrl
0000000000011120 s _do_meta_command.aLimit
00000000000111e0 s _do_meta_command.azBool
000000000000b000 t _dump_callback
00000000000128a8 b _enableTimer
000000000000c320 t _exec_prepared_stmt
                 U _exit
000000000000bbc0 t _explain_data_prepare
                 U _fclose
                 U _fflush
                 U _fgetc
                 U _fgets
0000000000008110 t _find_home_dir
00000000000128b8 b _find_home_dir.home_dir
                 U _fopen
                 U _fprintf
                 U _fputc
                 U _fputs
                 U _fread
                 U _free
                 U _fseek
                 U _ftell
                 U _fwrite
                 U _getenv
                 U _getpwuid
                 U _getrusage
                 U _getuid
0000000000012898 b _globalDb
0000000000012950 b _iBegin
00000000000011e0 t _integerValue
0000000000011090 s _integerValue.aMult
00000000000011a0 t _interrupt_handler
                 U _isatty
000000000000cc60 t _local_getline
0000000000000010 T _main
0000000000012860 b _mainPrompt
                 U _malloc
                 U _memcmp
                 U _memcpy
0000000000011200 s _modeDescr
0000000000011ad0 s _needCsvQuote
00000000000013d0 t _open_db
000000000000a0c0 t _output_c_string
000000000000c650 t _output_csv
000000000000a020 t _output_file_open
000000000000c4a0 t _output_html_string
000000000000c7c0 t _output_quoted_string
                 U _pclose
                 U _popen
                 U _printf
00000000000081f0 t _process_input
                 U _putc
                 U _putchar
                 U _puts
0000000000008e70 t _readFile
0000000000008d80 t _readfileFunc
                 U _realloc
0000000000008f30 t _resolve_backslashes
                 U _rewind
000000000000c920 t _runOneSqlLine
00000000000098c0 t _run_schema_dump_query
00000000000099e0 t _run_table_dump_query
00000000000128c0 b _sBegin
0000000000012894 b _seenInterrupt
0000000000008b50 t _set_table_name
                 U _setvbuf
0000000000009310 t _shellAuth
0000000000011360 s _shellAuth.azAction
0000000000000000 T _shellDeleteFile
000000000000ba80 t _shellFkeyCollateClause
0000000000008d10 t _shellLog
0000000000006c50 t _shell_callback
0000000000011ab0 s _shell_callback.aExplainWidths
0000000000011470 s _shell_dbinfo_command.aField
0000000000011530 s _shell_dbinfo_command.aQuery
00000000000066a0 t _shell_exec
00000000000128b0 b _shell_exec.zStmtSql
0000000000008d60 t _shellstaticFunc
                 U _signal
000000000000a7e0 t _sql_trace_callback
                 U _sqlite3_backup_finish
                 U _sqlite3_backup_init
                 U _sqlite3_backup_step
                 U _sqlite3_bind_blob
                 U _sqlite3_bind_double
                 U _sqlite3_bind_int
                 U _sqlite3_bind_int64
                 U _sqlite3_bind_null
                 U _sqlite3_bind_text
                 U _sqlite3_busy_timeout
                 U _sqlite3_changes
                 U _sqlite3_close
                 U _sqlite3_column_blob
                 U _sqlite3_column_bytes
                 U _sqlite3_column_count
                 U _sqlite3_column_double
                 U _sqlite3_column_int
                 U _sqlite3_column_int64
                 U _sqlite3_column_name
                 U _sqlite3_column_text
                 U _sqlite3_column_type
                 U _sqlite3_complete
                 U _sqlite3_config
                 U _sqlite3_context_db_handle
                 U _sqlite3_create_function
                 U _sqlite3_db_status
                 U _sqlite3_enable_load_extension
                 U _sqlite3_errcode
                 U _sqlite3_errmsg
                 U _sqlite3_exec
                 U _sqlite3_extended_errcode
                 U _sqlite3_file_control
                 U _sqlite3_finalize
                 U _sqlite3_free
                 U _sqlite3_get_autocommit
                 U _sqlite3_initialize
                 U _sqlite3_interrupt
                 U _sqlite3_libversion
                 U _sqlite3_limit
                 U _sqlite3_load_extension
                 U _sqlite3_malloc64
                 U _sqlite3_mprintf
                 U _sqlite3_open
                 U _sqlite3_prepare_v2
                 U _sqlite3_realloc64
                 U _sqlite3_reset
                 U _sqlite3_result_blob
                 U _sqlite3_result_int64
                 U _sqlite3_result_text
                 U _sqlite3_set_authorizer
                 U _sqlite3_sleep
                 U _sqlite3_snprintf
                 U _sqlite3_sourceid
                 U _sqlite3_sql
                 U _sqlite3_status
                 U _sqlite3_step
                 U _sqlite3_stmt_status
                 U _sqlite3_strglob
                 U _sqlite3_stricmp
                 U _sqlite3_strlike
                 U _sqlite3_strnicmp
                 U _sqlite3_table_column_metadata
                 U _sqlite3_test_control
                 U _sqlite3_total_changes
                 U _sqlite3_trace_v2
                 U _sqlite3_value_blob
                 U _sqlite3_value_bytes
                 U _sqlite3_value_text
                 U _sqlite3_vfs_find
                 U _sqlite3_vfs_register
000000000000cdd0 d _stdin_is_interactive
                 U _strchr
                 U _strcmp
                 U _strlen
                 U _strncmp
                 U _strncpy
                 U _strtol
                 U _system
00000000000128ac b _test_breakpoint.nCall
0000000000009460 t _testcase_glob
0000000000012958 b _timeOfDay.clockVfs
000000000000ab20 t _tryToCloneData
000000000000a850 t _tryToCloneSchema
                 U _unlink
0000000000008dd0 t _writefileFunc
000000000000cde0 d _zHelp
0000000000011580 s _zOptions
00000000000128a0 b _zShellStatic

I tried using the nm on the other files but just got 

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/nm: curl_fun.o: No such file or directory.

As a response

I am not too sure what I am reading in the second part but it seems there is more than one error.
thanks for the help

**Comment by greatwolf** [comment]
It looks like the build is having trouble finding jansson dependency. I'm not too familiar with macosx but does it follow a similar convention like linux where it places installed packages? eg. `/usr/bin`, `/usr/include`, `/usr/lib` etc.? Where is the jansson install located on your setup?

If it's in an atypical location you can point blackbird on where to find it using `INC_DIR` and `LIB_DIR` for the include headers and shared/static libraries respectively. For example,

    make -B VERBOSE=1 INC_DIR="-I/your/custom/install/jansson/path/goes/here"

**Comment by bg560581** [comment]
everything went well until I got to this:

In file included from src/curl_fun.cpp:5:
/Users/Ben/blackbird/extern/jansson/src/jansson.h:56:5: error: invalid token at
      start of a preprocessor expression
#if JSON_INTEGER_IS_LONG_LONG
    ^
/Users/Ben/blackbird/extern/jansson/src/jansson_config.h:33:35: note: expanded
      from macro 'JSON_INTEGER_IS_LONG_LONG'
#define JSON_INTEGER_IS_LONG_LONG @json_have_long_long@
                                  ^
1 error generated.
make: *** [src/curl_fun.o] Error 1


should I go into the file and change anything? or is it an issue with curl. if I get that to work will Jansson fall into place?

**Comment by greatwolf** [comment]
It looks like the `jansson_config.h` didn't get processed properly. Notice the `@json_have_long_long@`. How did you build jansson source? Was it with cmake?
