### ISSUE TITLE
Bitfinex hard fork measurements: what would this mean for blackbird ?

### ISSUE THREAD

**Issue by pepijnolivier** [butor/blackbird#148]
After logging into my bitfinex account, I got this announcement (march 29th, 2017)

> ... After much analysis, we have chosen to handle the accounting of margin trading and funding based on the model of how stock spinoffs, dividends, and distributions are handled in equity markets. Specifically, in the case of a hardfork event, lenders will receive both BTC and BTU. Anyone that is short BTC/USD or long any BTC trading pair (ETH/BTC, LTC/BTC, etc.) will owe BTU to the lender, effectively making the user short BTU. An exception is in the case that BTC is borrowed but not in use as margin collateral, in which case BTU accrues to the lender. Users that are margin long BTC/USD or short any BTC trading pair will receive BTU...

[Full announcement](https://pastebin.com/USMZ59Mb)

I'm wondering what this means for blackbird. Which updates would be necessary in case bitfinex chooses this strategy when or if the hard fork happens ? How can I help ?

**Comment by butor** [comment]
Thanks for that @pepijnolivier.

It all depends on how Bitfinex will implement the change, if any, in their API. At the end of the announcement they say:

> More details on the specific procedures will be forthcoming [...]

So I guess we need to keep an eye on that.
