### ISSUE TITLE
Chat room

### ISSUE THREAD

**Issue by alfonsoperez** [butor/blackbird#152]
Hi, is there a chat room where people would discuss development of this project and related topics?.

What about setting up a channel in http://gitter.im ?

Regards

**Comment by mtamer** [comment]
I think this is a great idea. I would totally down for this.

**Comment by Finster33** [comment]
Yes

**Comment by butor** [comment]
OK I will take care of that. Stay tuned

**Comment by butor** [comment]
Done.
Link: https://gitter.im/blackbird_bitcoin_arbitrage/Lobby
Thanks for the suggestion

**Comment by alfonsoperez** [comment]
Neat!!!
