### ISSUE TITLE
Issue with Bitfinex

### ISSUE THREAD

**Issue by ki4yvc** [butor/blackbird#156]
Forgive me for my hopefully not ignorant question, but I am relatively new to this so for all I know this might be right with how going long and going short means.
When running the bot, it attempted to make a trade on the Bitfinex exchange and the Bitstamp exchange. The transaction went through on Bitstamp but not Bitfinex, it simply returned an order ID of 0. I have my money in Bitfinex in a margin trading account. Have I configured Blackbird wrong or are my setting in Bitfinex wrong?

**Comment by ki4yvc** [comment]
I did more research, I guess as a US user I cant use

**Comment by greatwolf** [comment]
Can you check what the json response was when you tried to submit that order?

**Comment by greatwolf** [comment]
I found an off-by-one bug in bitfinex's `getAvail` from one of my recent push. See if the fix helps.

**Comment by ki4yvc** [comment]
Thanks! I'll give it a shot!

**Comment by ki4yvc** [comment]
I believe the issue is margin trading is not available in the US if I am correct.

**Comment by greatwolf** [comment]
You're probably right. I've added some logging for the `message` response. If there's something wrong with the auth call, you should see it logged in the the file now. You'll probably see something like "API key not having permission" or something to that effect.
