### ISSUE TITLE
Spread target

### ISSUE THREAD

**Issue by bugduino** [butor/blackbird#158]
Hi,
I'm probably missing something but I see this in my console 

```
[ 04/27/2017 15:02:03 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    1.407,20 / 1.407,80
   Kraken:      1.302,90 / 1.307,01
   Poloniex:    1.404,57 / 1.407,00
   ----------------------------
   Kraken/Bitfinex:      8.05% [target  6.30%, min  7.09%, max  8.70%]
```

 shouldn't the trade begin with a spread of 8.05% (which is > 6.30%) ?

**Comment by butor** [comment]
I wouldn't advise to trade Bitfinex right now. They are trading at a premium (hence the large spread) because of their current banking issues.

**Comment by bugduino** [comment]
Ok but the rationale is correct? Should it trade or not?

**Comment by bugduino** [comment]
There is also the same spread between Kraken and Poloniex

**Comment by butor** [comment]
Yes the rationale is correct. The spread is above the target: Blackbird would trade the opportunity.

Poloniex is also trading at a premium because of their issue with liquidating USDT. However, Blackbird cannot short on Poloniex anyway.

**Comment by bugduino** [comment]
Ok, so why Blackbird is not trading right now Kraken long and Bitfinex short?

**Comment by butor** [comment]
Because you're already in market. See the first line:
```[ 04/27/2017 15:02:03 IN MARKET: Long Kraken / Short Bitfinex ]```

**Comment by bugduino** [comment]
What does this mean? Could you point me to some issues which describe this situation?

**Comment by butor** [comment]
It means that Blackbird already traded that opportunity and is now waiting for the spread to close to trade back to USD and close the opportunity. Check the log file to see when the trades happened.

**Comment by bugduino** [comment]
If I delete the restore.txt all should be back to normal? I have a restore.txt with 
```
1
1
0
Kraken
Bitfinex
9.15265
0.0025
0.002
1493156892
0.0769847
1274.02
1372.5
0
0.0629847
-1
1
1
0
```

**Comment by bugduino** [comment]
I've already traded back all to USD manually an have 0 bitcoin on each exchange

**Comment by butor** [comment]
Yes. Since you've traded everything back to USD you can delete restore.txt and you're good to go.

**Comment by bugduino** [comment]
Ok now all seems clear to me! Thank you @butor!

**Comment by butor** [comment]
You're welcome
