### ISSUE TITLE
Trading Platform

### ISSUE THREAD

**Issue by Megarray** [butor/blackbird#159]
I apologize if this is the wrong place to post this. If it is, please delete and tell where I can post it.

I have a couple questions.

1. Is arbitrage working well for anyone?
2. I purchased the source code to: http://www.modulusfe.com/products/trading-platforms/ I am wondering if having this code would help with using Blackbird or does Blackbird stand on it's own? I am not a programmer so forgive my ignorance. I want to put together a powerful arbitrage bot for crypto currencies. If anyone wants to partner, please contact me. I am using the code for a different Forex trading project right now but want to expand into arbitrage, assuming this code will help and arbitrage is still viable.

I look forward to your responses.

Thank you.

T

**Comment by seecretly** [comment]
Hi T, i'm not a programmer but I'm looking into arbitrage as well right now, if you'd like to join forces my email is seecretly at gmail.com. Cheers!
