### ISSUE TITLE
Alway show "nonce is too small"

### ISSUE THREAD

**Issue by plko** [butor/blackbird#16]
I check the code,
I think it's better to use unsigned long long here.
long nonce = (tv.tv_sec * 100.0) + (tv.tv_usec * 0.001) + 0.5;
unsigned long long nonce = (tv.tv_sec * 100.0) + (tv.tv_usec * 0.001) + 0.5;

**Comment by NateBrune** [comment]
I also experienced this issue. Nonce too small. I actually only experienced this in certain configurations, I wasn't sure why. Did this fix it though?

**Comment by plko** [comment]
After try many times, I think it cause by this rule from bitfinex API:
"The nonce provided must be strictly increasing."
It seems like you should add your nonce every time you do authentication, and can't start from minus number.
This limit is key by key, you can use the nonce from 1 every key.

Use unsigned long long can ensure the nonce will not be minus and it's 64-bit number.(I run this at 32-bit windows7, so long is signed 32-bit number, nonce will easily over 32-bit limit)

**Comment by NateBrune** [comment]
Yeah, I also experienced this issue and this pull request probably solves that for everyone.

**Comment by butor** [comment]
Hi @piko and @NateBrune,

Thanks. I've never experienced this nonce issue (I'm on Ubuntu 15.04 x64) but since _unsigned long long_ fixed your issues I'll accept the PR #17. Thank you guys
