### ISSUE TITLE
Bitfinex position never claimed

### ISSUE THREAD

**Issue by mdrankin** [butor/blackbird#161]
Hi,

I'm testing out the software and an order was placed and filled on OKCoin (long), and a position taken on Betfinex (short), however the Bitfinex position has not been claimed. The price on Bitfinex has risen above the position taken, and also fallen below the position taken since Blackbird found an entry. As far as I can tell, it's still waiting for the two order to be fulfilled, however there is no order on Bitfinex, just a position.

What am I missing?

**Comment by mdrankin** [comment]
Here is an image of my position - http://i.imgur.com/Hv64Lvd.png and you can see trading has been above and below my position.

**Comment by greatwolf** [comment]
Can you also show the logs? You can block out any sensitive info. Is this happening on a build with the latest head?

**Comment by mdrankin** [comment]
Below is the log file. It was built with "git clone --recursive  git://github.com/butor/blackbird.git ." on a clean VPS. I assume this would give me the latest build.
`--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------
Blackbird started on 05/02/2017 00:22:35
Connected to database 'blackbird.db'
[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.50%
[ Current balances ]
   Bitfinex:    28.44 USD       0.000000 BTC
   OKCoin:      26.00 USD       0.000000 BTC
   Bitstamp:    26.45 USD       0.000000 BTC
[ Cash exposure ]
   TEST cash used
   Value: $25.00
Running...
<OKCoin> Looking for a limit price to fill 0.02 BTC...
<OKCoin> order book: 1.84@$1,376.25
<Bitfinex> Looking for a limit price to fill 0.02 BTC...
<Bitfinex> order book: 0.10@$1,549.50
[ ENTRY FOUND ]
   Date & Time:       05/02/2017 00:24:30
   Exchange Long:     OKCoin (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.20% / 0.20%
   Price Long:        $1,376.25 (target)
   Price Short:       $1,549.50 (target)
   Spread:            12.59%
   Cash used:         $25.00 on each exchange
   Exit Target:       11.29%
<OKCoin> Trying to send a "buy" limit order: 0.02@$1,376.25...
<OKCoin> Done (order ID: 500674809)
<Bitfinex> Trying to send a "sell" limit order: 0.02@$1,549.50...
<Bitfinex> Done (order ID: 2429562873)
Waiting for the two orders to be filled...
Done
WARNING: 2 second(s) too late at 05/02/2017 00:24:35
Error with cURL: Timeout was reached
  URL: https://www.bitstamp.net/api/ticker
  Retry in 2 sec...
WARNING: 19 second(s) too late at 05/02/2017 00:36:40
WARNING: 1 second(s) too late at 05/02/2017 00:56:30
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
WARNING: 16 second(s) too late at 05/02/2017 01:30:00
WARNING: 1 second(s) too late at 05/02/2017 01:38:20
WARNING: 3 second(s) too late at 05/02/2017 02:12:05
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
WARNING: 10 second(s) too late at 05/02/2017 02:28:50
WARNING: 7 second(s) too late at 05/02/2017 02:37:05
WARNING: 2 second(s) too late at 05/02/2017 02:45:35
WARNING: 1 second(s) too late at 05/02/2017 02:46:30
WARNING: 2 second(s) too late at 05/02/2017 02:54:10
WARNING: 11 second(s) too late at 05/02/2017 03:13:05
WARNING: 12 second(s) too late at 05/02/2017 03:19:05
WARNING: 1 second(s) too late at 05/02/2017 03:19:40
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
WARNING: 16 second(s) too late at 05/02/2017 03:45:05
WARNING: 2 second(s) too late at 05/02/2017 03:53:25
WARNING: 11 second(s) too late at 05/02/2017 03:53:45
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
WARNING: 9 second(s) too late at 05/02/2017 03:54:05
WARNING: 4 second(s) too late at 05/02/2017 04:02:35
WARNING: 3 second(s) too late at 05/02/2017 04:19:20
WARNING: 4 second(s) too late at 05/02/2017 04:27:25
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
WARNING: 21 second(s) too late at 05/02/2017 04:27:50
Error with cURL: Timeout was reached
  URL: https://www.okcoin.com/api/ticker.do?ok=1
  Retry in 2 sec...
WARNING: 9 second(s) too late at 05/02/2017 04:44:55`

**Comment by greatwolf** [comment]
Judging from the logs, it looks like that bfx margin position did get filled:

    <OKCoin> Trying to send a "buy" limit order: 0.02@$1,376.25...
    <OKCoin> Done (order ID: 500674809)
    <Bitfinex> Trying to send a "sell" limit order: 0.02@$1,549.50...
    <Bitfinex> Done (order ID: 2429562873)
    Waiting for the two orders to be filled...
    Done

Notice the orderid it got back. You can confirm this by checking your account Reports section from the webui, the time and orderid should match up.

**Comment by mdrankin** [comment]
ok, it may well be that I didn't wait long enough and the app would have existed the Bitfinex position when it was more favourable. Please close for now.
