### ISSUE TITLE
Short order on Bitfinex still open...

### ISSUE THREAD

**Issue by mdrankin** [butor/blackbird#162]
Same as issue #137 as far as I can tell. Getting "Short order on Bitfinex still open..." since last night and I indeed do still have a position open on Bitfinex. Was built with master build yesterday.

Looks like it's not an issue, I do still have an active order, just that the price on Bitfinex jumped overnight.

**Comment by butor** [comment]
Can you please show us the log file? Thanks

**Comment by mdrankin** [comment]
Sorry, I've since deleted the log file.

**Comment by chickenwing** [comment]
Relating Bitfinex, how are you deposing funds there anyway? On Bitfinex they display the message "Wire deposits have been paused" because of issues with their bank. Since its the only Implemented trading platform with short selling its kind of needed, isnt it? Sorry if this is the wrong place to ask.

**Comment by mdrankin** [comment]
@chickenwing same way I deposit funds on all the exchanges - transferring BTC then opening a sell order to get USD.

**Comment by chickenwing** [comment]
@mdrankin thx for enlightening me.

**Comment by jw4wellness** [comment]
I had the same issue
Here is my log:
[ 05/08/2017 17:40:12 ]
   Bitfinex: 	1659.80 / 1659.90
   OKCoin: 	1508.23 / 1508.24
   Kraken: 	1590.00 / 1594.67
   BTC-e: 	1586.60 / 1580.25
   ----------------------------
   OKCoin/Bitfinex:	 10.05% [target  0.80%, min  10.05%, max  10.13%]   trailing  10.05%  0/1
   Kraken/Bitfinex:	 4.08% [target  0.80%, min  3.95%, max  4.17%]   trailing  4.09%  0/1
   BTC-e/Bitfinex:	 5.03% [target  0.80%, min  5.03%, max  5.12%]   info only

[ 05/08/2017 17:40:15 ]
   Bitfinex: 	1659.80 / 1659.90
   OKCoin: 	1508.23 / 1508.24
   Kraken: 	1590.00 / 1594.67
   BTC-e: 	1585.60 / 1580.25
   ----------------------------
   OKCoin/Bitfinex:	 10.05% [target  0.80%, min  10.05%, max  10.13%]   trailing  10.05%  1/1
<OKCoin> Looking for a limit price to fill 0.02 BTC...
<OKCoin> order book: 0.09@$1508.24
<Bitfinex> Looking for a limit price to fill 0.02 BTC...
<Bitfinex> order book: 0.75@$1659.80

[ ENTRY FOUND ]
   Date & Time:       05/08/2017 17:40:15
   Exchange Long:     OKCoin (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.20% / 0.20%
   Price Long:        $1508.24 (target)
   Price Short:       $1659.80 (target)
   Spread:            10.05%
   Cash used:         $25.00 on each exchange
   Exit Target:       8.75%

<OKCoin> Trying to send a "buy" limit order: 0.02@$1508.24...
<OKCoin> Done (order ID: 508271075)

<Bitfinex> Trying to send a "sell" limit order: 0.02@$1659.80...
<Bitfinex> Done (order ID: -1811374968)

Waiting for the two orders to be filled...
Short order on Bitfinex still open...
**over 500 pages repeat:
Short order on Bitfinex still open...
Short order on Bitfinex still open...**

**Comment by butor** [comment]
@chickenwing
You are correct: Bitfinex is the only exchange where short selling is implemented, so an account on it is needed to run Blackbird.

@jw4wellness
Look at the negative _order ID_ on Bitfinex:
`<Bitfinex> Done (order ID: -1811374968)`
It seems that this is the same problem as the one from #137. Are you running Blackbird with the latest build?

**Comment by jw4wellness** [comment]
I don't think so, I have this one that Greatwolf uploaded here:
https://github.com/butor/blackbird/issues/114

**Comment by butor** [comment]
Right. I forgot you had this version.

Since then a fix has been provided by @greatwolf ([see here](https://github.com/butor/blackbird/commit/6728cde3621808d4b7fc6c2b5e0ad87b95703776)) to deal with `orderId` not fitting into a `int`.

**Comment by jw4wellness** [comment]
Thank you, will those files be in the new build? Then I can download and
compile that?

**Comment by greatwolf** [comment]
I could provide the latest binaries from the latest head but you're encouraged to just clone the repo and build it yourself. It's mainly a trust issue.

**Comment by jw4wellness** [comment]
Yes thank you. I am also eager to do that. I am only interested in learning
so I don't have trust issues. The practice / test accounts doesn't have
much to lose in. When I figured out how to do it all I can do that and that
will be a great experience in itself too. For example I noticed the issue
with the negative order number on bitfinex and then it took me a few hours
to figure out how to close the open order manually. So finally I got it and
next time it will be quicker.

Would it be okay if you provide the one please? If you could I just learn
faster by doing a little each day than trying to learn everything all in
once.
