### ISSUE TITLE
Different quantities between exposures and orders size

### ISSUE THREAD

**Issue by bugduino** [butor/blackbird#163]
Hi, 
I have the following situation which seems odd to me:

```
[ 05/04/2017 13:38:06 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    1.617,00 / 1.618,00
   Kraken:      1.554,03 / 1.556,94
   BTC-e:       1.447,00 / 1.449,90
   Poloniex:    1.618,98 / 1.619,00
   ----------------------------
   Kraken/Bitfinex:      4.12% [target  4.15%, min  4.01%, max  4.12%]   trailing  4.09%  1/1
<Bitfinex> Looking for a limit price to fill 0,02 BTC...
<Bitfinex> order book: 0,06@$1.616,90

[ EXIT FOUND ]
   Date & Time:       05/04/2017 13:38:06
   Duration:          8.534,95 minutes
   Price Long:        $1.554,03 (target)
   Price Short:       $1.616,90 (target)
   Spread:            4,12%
   ---------------------------
   Target Perf Long:  16,79% (fees incl.)
   Target Perf Short: -15,99% (fees incl.)
   ---------------------------

BTC exposure on Kraken: 0,017502
BTC exposure on Bitfinex: -0,016578

<Kraken> Trying to send a "sell" limit order: 0,02 @ $1.554,03...
{"error": ["EOrder:Insufficient funds"]}
```
why blackbird is trying to fill orders with 0,02 as quantity

```
<Bitfinex> Looking for a limit price to fill 0,02 BTC...
<Kraken> Trying to send a "sell" limit order: 0,02 @ $1.554,03...
```
when the exposure I have is
```
BTC exposure on Kraken: 0,017502
BTC exposure on Bitfinex: -0,016578
```

(which causes the {"error": ["EOrder:Insufficient funds"]} issue) ?

**Comment by greatwolf** [comment]
Can you show the section of where the entry happened?

**Comment by greatwolf** [comment]
I just looked in [kraken.cpp:118](https://github.com/butor/blackbird/blob/master/src/exchange/kraken.cpp#L118), this doesn't look correct:

    double getActivePos(Parameters& params) {
      return getAvail(params, "btc");
    }

`getAvail` returns the current balance as I understand. Why is it used to query the active positions? From this commit https://github.com/butor/blackbird/commit/300434785d217ef4436ab19f2149ace9741208ab#diff-6f538166ec11ea3f8bfb7bddcbf7cb14R124. @beckel, @butor is this really the correct implementation?

**Comment by bugduino** [comment]
Here you have it

```
132163-[ 04/28/2017 15:23:09 ]
132164-   Bitfinex:     1.398,60 / 1.399,50
132165-   Kraken:       1.320,33 / 1.325,00
132166-   BTC-e:        1.290,30 / 1.292,40
132167-   Poloniex:     1.398,15 / 1.399,50
132168-   ----------------------------
132169-   Bitfinex/Poloniex:    -0.10% [target  0.80%, min -0.18%, max -0.00%]   info only
132170-   Kraken/Bitfinex:       5.55% [target  0.80%, min  5.55%, max  5.77%]   trailing  5.69%  1/1
132171-<Bitfinex> Looking for a limit price to fill 0,02 BTC...
132172-<Bitfinex> order book: 1,35@$1.398,80
132173-
132174:[ ENTRY FOUND ]
132175-   Date & Time:       04/28/2017 15:23:09
132176-   Exchange Long:     Kraken (id 1)
132177-   Exchange Short:    Bitfinex (id 0)
132178-   Fees:              0,25% / 0,20%
132179-   Price Long:        $1.325,00 (target)
132180-   Price Short:       $1.398,80 (target)
132181-   Spread:            5,55%
132182-   Cash used:         $23,19 on each exchange
132183-   Exit Target:       4,15%
132184-
132185-<Kraken> Trying to send a "buy" limit order: 0,02 @ $1.325,00...
132186-<Kraken> Done (transaction ID: XXXXXXX)
132187-
132188-<Bitfinex> Trying to send a "sell" limit order: 0,02@$1.398,80...
132189-<Bitfinex> Done (order ID: YYYYYYYYYY)
```

and I'm using the following params 
```
# Program parameters
DemoMode=false
UseFullCash=true
CashForTesting=10.00
MaxExposure=25000.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true
CACert=curl-ca-bundle.crt

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600
```

**Comment by unclemimo** [comment]
I'm running through the same issue. Here are my logs:

Configuration:

`# Blackbird Bitcoin Arbitrage
# Configuration file


# Program parameters
DemoMode=false
UseFullCash=false
CashForTesting=25.00
MaxExposure=25000.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true
CACert=curl-ca-bundle.crt

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=true
VolatilityPeriod=600`

Entry:

`
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 04/29/2017 15:46:13

Connected to database 'blackbird.db'

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.50%

[ Current balances ]
<Bitstamp> Error with the credentials.
<Bitstamp> Error with the credentials.
   Bitfinex:    35.02 USD       0.000000 BTC
   OKCoin:      26.83 USD       0.000024 BTC
   Bitstamp:    0.00 USD        0.000000 BTC
   Kraken:      27.50 USD       0.000000 BTC
   ItBit:       n/a (API not implemented)
   BTC-e:       n/a (API not implemented)
   GDAX:        n/a (API not implemented)

[ Cash exposure ]
   TEST cash used
   Value: $25.00

[ 04/29/2017 15:46:18 ]
   Bitfinex:    1,404.20 / 1,404.30
   OKCoin:      1,264.26 / 1,265.99
   Bitstamp:    1,324.02 / 1,326.66
   Kraken:      1,315.58 / 1,323.54
   ItBit:       1,336.12 / 1,337.22
   BTC-e:       1,285.02 / 1,289.40
   GDAX:        1,345.59 / 1,345.88
   ----------------------------

   **...**

   [ ENTRY FOUND ]
   Date & Time:       04/29/2017 15:48:00
   Exchange Long:     OKCoin (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.20% / 0.20%
   Price Long:        $1,263.07 (target)
   Price Short:       $1,404.00 (target)
   Spread:            11.15%
   Cash used:         $25.00 on each exchange
   Exit Target:       9.85%

<OKCoin> Trying to send a "buy" limit order: 0.02@$1,263.07...
<OKCoin> Done (order ID: 498405602)

<Bitfinex> Trying to send a "sell" limit order: 0.02@$1,404.00...
<Bitfinex> Done (order ID: 2409008310)

Waiting for the two orders to be filled...
Done

Exchange Short:    Bitfinex (id 0)
   Fees:              0.20% / 0.20%
   Price Long:        $1,263.07 (target)
   Price Short:       $1,404.00 (target)
   Spread:            11.15%
   Cash used:         $25.00 on each exchange
   Exit Target:       9.85%

<OKCoin> Trying to send a "buy" limit order: 0.02@$1,263.07...
<OKCoin> Done (order ID: 498405602)

<Bitfinex> Trying to send a "sell" limit order: 0.02@$1,404.00...
<Bitfinex> Done (order ID: 2409008310)

Waiting for the two orders to be filled...
Done

WARNING: 4 second(s) too late at 04/29/2017 15:48:03

[ 04/29/2017 15:48:09 IN MARKET: Long OKCoin / Short Bitfinex ]
   Bitfinex:    1,404.40 / 1,404.50
   OKCoin:      1,263.02 / 1,263.07
   Bitstamp:    1,324.03 / 1,326.50
   Kraken:      1,315.58 / 1,323.55
   ItBit:       1,335.70 / 1,336.81
   BTC-e:       1,285.00 / 1,285.00
   GDAX:        1,346.92 / 1,347.00
   ----------------------------
   OKCoin/Bitfinex:      11.20% [target  9.85%, min  11.20%, max  11.20%]  volat. n/a 36<600

`
Order placement:

`
[ 05/05/2017 10:53:51 IN MARKET: Long OKCoin / Short Bitfinex ]
   Bitfinex:    1,656.20 / 1,656.60
   OKCoin:      1,508.46 / 1,509.94
   Bitstamp:    1,599.69 / 1,604.11
   Kraken:      1,579.10 / 1,585.00
   ItBit:       1,610.14 / 1,611.27
   BTC-e:       1,482.00 / 1,484.00
   GDAX:        1,623.90 / 1,624.02
   ----------------------------
   OKCoin/Bitfinex:      9.82% [target  9.85%, min  7.97%, max  16.60%]  volat. 0.29%   trailing  9.79%  1/1
<OKCoin> Looking for a limit price to fill 0.02 BTC...
<OKCoin> order book: 0.08@$1,509.67
<Bitfinex> Looking for a limit price to fill 0.02 BTC...
<Bitfinex> order book: 0.50@$1,656.60

[ EXIT FOUND ]
   Date & Time:       05/05/2017 10:53:51
   Duration:          8,345.85 minutes
   Price Long:        $1,509.67 (target)
   Price Short:       $1,656.60 (target)
   Spread:            9.82%
   ---------------------------
   Target Perf Long:  19.12% (fees incl.)
   Target Perf Short: -18.39% (fees incl.)
   ---------------------------

BTC exposure on OKCoin: 0.018986
BTC exposure on Bitfinex: -0.017808

<OKCoin> Trying to send a "sell" limit order: 0.02@$1,509.67...
<OKCoin> Done (order ID: 503810993)

<Bitfinex> Trying to send a "buy" limit order: 0.02@$1,656.60...
<Bitfinex> Done (order ID: 2454910080)

Waiting for the two orders to be filled...
Done

New balance on Bitfinex:        30.29 USD (perf $-4.73), -0.000005 BTC
New balance on OKCoin:          29.95 USD (perf $3.12), 0.000986 BTC
New balance on Bitstamp:        0.52 USD (perf $0.52), 0.000000 BTC
New balance on Kraken:          0.01 USD (perf $-27.49), 0.000000 BTC
New balance on ItBit:   0.00 USD (perf $0.00), 0.000000 BTC
New balance on BTC-e:   0.00 USD (perf $0.00), 0.000000 BTC
New balance on GDAX:    0.00 USD (perf $0.00), 0.000000 BTC

ACTUAL PERFORMANCE: $-28.58 (-57.16%)

Email sent

Exit after last trade (file stop_after_notrade found)
`
Any ideas why it's restricting the orders to 0,02?

**Comment by bugduino** [comment]
I'm not able to close any trade automatically due to this 'bug' here is another log (that also shows a warning)
```
[ 05/05/2017 13:11:03 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    1.609,00 / 1.610,00
   Kraken:      1.574,52 / 1.576,82
   BTC-e:       1.466,22 / 1.470,85
   Poloniex:    1.611,09 / 1.611,35
   ----------------------------
   Kraken/Bitfinex:      2.25% [target  2.92%, min  2.17%, max  3.07%]   trailing  2.25%  1/1
<Bitfinex> Looking for a limit price to fill 0,01 BTC...
<Bitfinex> order book: 0,38@$1.610,20
WARNING: Opportunity found but not enough liquidity. Trade canceled
         Target long price:  1.574,52, Real long price:  1.574,52
         Target short price: 1.610,00, Real short price: 1.610,20

[ 05/05/2017 13:11:06 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    1.609,60 / 1.610,20
   Kraken:      1.574,52 / 1.576,82
   BTC-e:       1.466,23 / 1.470,85
   Poloniex:    1.611,09 / 1.612,58
   ----------------------------
   Kraken/Bitfinex:      2.27% [target  2.92%, min  2.17%, max  3.07%]

[ 05/05/2017 13:11:09 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    1.609,60 / 1.610,20
   Kraken:      1.571,10 / 1.576,81
   BTC-e:       1.466,23 / 1.470,85
   Poloniex:    1.612,00 / 1.612,02
   ----------------------------
   Kraken/Bitfinex:      2.49% [target  2.92%, min  2.17%, max  3.07%]   trailing  2.35%  0/1

[ 05/05/2017 13:11:12 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    1.609,70 / 1.610,20
   Kraken:      1.571,10 / 1.576,81
   BTC-e:       1.466,23 / 1.471,30
   Poloniex:    1.611,09 / 1.612,02
   ----------------------------
   Kraken/Bitfinex:      2.49% [target  2.92%, min  2.17%, max  3.07%]   trailing  2.35%  1/1
<Bitfinex> Looking for a limit price to fill 0,01 BTC...
<Bitfinex> order book: 0,38@$1.610,20

[ EXIT FOUND ]
   Date & Time:       05/05/2017 13:11:12
   Duration:          1.377,55 minutes
   Price Long:        $1.571,10 (target)
   Price Short:       $1.610,20 (target)
   Spread:            2,49%
   ---------------------------
   Target Perf Long:  0,67% (fees incl.)
   Target Perf Short: 0,35% (fees incl.)
   ---------------------------

BTC exposure on Kraken: 0,013302
BTC exposure on Bitfinex: -0,012761

<Kraken> Trying to send a "sell" limit order: 0,01 @ $1.571,10...
{"error": ["EOrder:Insufficient funds"]}

```

**Comment by butor** [comment]
@unclemimo 
I don't think you have the same error, which is related to Kraken only. The 0.02 that you see is a display formatting (_x.xx_) of your current position, but the values are correct:

`BTC exposure on OKCoin: 0.018986` is displayed as "sell" limit order 0.02.
`BTC exposure on Bitfinex: -0.017808` is displayed as "buy" limit order 0.02.

Maybe we should change the display format from _x.xx_ to _x.xxxx_ to have a more accurate log.

@bugduino 
@greatwolf 
In some exchanges, like OkCoin, the exposure is actually the bitcoins you own. Look at the OkCoin implementation of `getActivePos()`:

`double getActivePos(Parameters& params) { return getAvail(params, "btc"); }`

But in this case it looks like it doesn't work correctly. I think `EOrder:Insufficient funds` happens because Blackbird is not looking at the correct BTC account, or something like that. I'll take a look.

**Comment by omargeek** [comment]
I have the same issue.. I'm not able to  close any trade automatically.

> <Bitfinex> Looking for a limit price to fill 0,03 BTC...
> <Bitfinex> order book: 0,10@$1.590,20
> 
> [ EXIT FOUND ]
>    Date & Time:       05/05/2017 17:16:39
>    Duration:          1.666,65 minutes
>    Price Long:        $1.568,10 (target)
>    Price Short:       $1.590,20 (target)
>    Spread:            2,65%
>    ---------------------------
>    Target Perf Long:  0,39% (fees incl.)
>    Target Perf Short: 1,29% (fees incl.)
>    ---------------------------
> 
> BTC exposure on Kraken: 0,034127
> BTC exposure on Bitfinex: -0,031288
> 
> <Kraken> Trying to send a "sell" limit order: 0,03 @ $1.568,10...
> {"error": ["EOrder:Insufficient funds"]}

**Comment by omargeek** [comment]
Maybe can be due number precision.
I can see on blackbird log: Kraken:	0,38 USD	0,032557 BTC
On my kraken account I can see XBT: ฿0.03255

Maybe it is this difference?..

**Comment by omargeek** [comment]
It solved for me.. 
I just modify getAvail function on kraken.cpp
I added just after "available = avail_str ? atof(avail_str) : 0.0;" this:
available = (int)(available * 100000) / 100000.0f;

Hope can help

**Comment by greatwolf** [comment]
That's weird, that would imply that kraken's api is returning bad data

**Comment by butor** [comment]
@bugduino @omargeek  Any news on this? Thanks

**Comment by bugduino** [comment]
I'm sorry but I'didnt have enough time at the moment to dig deeper
