### ISSUE TITLE
issue while installing on mac+docker

### ISSUE THREAD

**Issue by assafwo2** [butor/blackbird#164]
i'm trying to build the docker according to the readme file. this is what i am getting: 

mac: ~/Desktop/docker/blackbird master $ docker build -t blackbird .
Sending build context to Docker daemon 16.32 MB
Step 1/6 : FROM ubuntu:16.04
 ---> f7b3f317ec73
Step 2/6 : MAINTAINER Alex Gandy <alexgandy@gmail.com>
 ---> Using cache
 ---> fe7d7e7a203b
Step 3/6 : RUN apt-get update   && apt-get install -yq --no-install-recommends   libssl-dev   libjansson-dev   libcurl4-openssl-dev   libsqlite3-dev   sendemail   make   gcc   g++   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> ae613f27c0de
Step 4/6 : COPY . /blackbird
 ---> 307b1f63cca7
Removing intermediate container 4083be627f04
Step 5/6 : WORKDIR /blackbird
 ---> 69747ee9ea3b
Removing intermediate container 8d99b76800bf
Step 6/6 : RUN make
 ---> Running in f7a51fdddf45
Compiling src/curl_fun.o:
Compiling src/time_fun.o:
Compiling src/db_fun.o:
Compiling src/result.o:
Compiling src/parameters.o:
Compiling src/main.o:
Compiling src/exchange/gdax.o:
Compiling src/exchange/bitstamp.o:
Compiling src/exchange/btce.o:

Compiling src/exchange/poloniex.o:
Compiling src/exchange/itbit.o:
Compiling src/exchange/gemini.o:
Compiling src/exchange/kraken.o:
Compiling src/exchange/okcoin.o:
Compiling src/exchange/bitfinex.o:
Compiling src/utils/base64.o:
Compiling src/utils/send_email.o:
Compiling src/utils/restapi.o:
Linking blackbird:
src/bitcoin.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:49: recipe for target 'blackbird' failed
make: *** [blackbird] Error 1
The command '/bin/sh -c make' returned a non-zero code: 2
mac: ~/Desktop/docker/blackbird master $ ls
Dockerfile          Makefile            blackbird.conf      extern              shell.o             sqlite3.o           stop_after_notrade_
LICENSE             README.md           curl-ca-bundle.crt  libsqlite3.a        sqlite3             src

help me.

**Comment by greatwolf** [comment]
Can you modify the following line in dockerfile to

    RUN make VERBOSE=1

**Comment by assafwo2** [comment]
mac: ~/Desktop/docker/blackbird master $ docker build -t blackbird .
Sending build context to Docker daemon 16.32 MB
Step 1/6 : FROM ubuntu:16.04
 ---> f7b3f317ec73
Step 2/6 : MAINTAINER Alex Gandy <alexgandy@gmail.com>
 ---> Using cache
 ---> fe7d7e7a203b
Step 3/6 : RUN apt-get update   && apt-get install -yq --no-install-recommends   libssl-dev   libjansson-dev   libcurl4-openssl-dev   libsqlite3-dev   sendemail   make   gcc   g++   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> ae613f27c0de
Step 4/6 : COPY . /blackbird
 ---> 676e32552352
Removing intermediate container 5ed42eaa33ba
Step 5/6 : WORKDIR /blackbird
 ---> 615bf6b9f55f
Removing intermediate container ac9a37e09807
Step 6/6 : RUN make VERBOSE=1
 ---> Running in 1d95393485d7
Compiling src/curl_fun.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/curl_fun.cpp -o src/curl_fun.o
Compiling src/time_fun.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/time_fun.cpp -o src/time_fun.o
Compiling src/db_fun.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/db_fun.cpp -o src/db_fun.o
Compiling src/result.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/result.cpp -o src/result.o
Compiling src/parameters.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/parameters.cpp -o src/parameters.o
Compiling src/main.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/main.cpp -o src/main.o
Compiling src/exchange/gdax.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/gdax.cpp -o src/exchange/gdax.o
Compiling src/exchange/bitstamp.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/bitstamp.cpp -o src/exchange/bitstamp.o
Compiling src/exchange/btce.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/btce.cpp -o src/exchange/btce.o
Compiling src/exchange/poloniex.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/poloniex.cpp -o src/exchange/poloniex.o
Compiling src/exchange/itbit.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/itbit.cpp -o src/exchange/itbit.o
Compiling src/exchange/gemini.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/gemini.cpp -o src/exchange/gemini.o
Compiling src/exchange/kraken.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/kraken.cpp -o src/exchange/kraken.o
Compiling src/exchange/okcoin.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/okcoin.cpp -o src/exchange/okcoin.o
Compiling src/exchange/bitfinex.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/bitfinex.cpp -o src/exchange/bitfinex.o
Compiling src/utils/base64.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/utils/base64.cpp -o src/utils/base64.o
Compiling src/utils/send_email.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/utils/send_email.cpp -o src/utils/send_email.o
Compiling src/utils/restapi.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/utils/restapi.cpp -o src/utils/restapi.o
Linking blackbird:
g++  -L . src/curl_fun.o src/bitcoin.o src/check_entry_exit.o src/time_fun.o src/db_fun.o src/result.o src/parameters.o src/main.o src/exchange/gdax.o src/exchange/bitstamp.o src/exchange/btce.o src/exchange/poloniex.o src/exchange/itbit.o src/exchange/gemini.o src/exchange/kraken.o src/exchange/okcoin.o src/exchange/bitfinex.o src/utils/base64.o src/utils/send_email.o src/utils/restapi.o -o blackbird -lsqlite3 -lcrypto -ljansson -lcurl  -lpthread -ldl
src/bitcoin.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:49: recipe for target 'blackbird' failed
make: *** [blackbird] Error 1
The command '/bin/sh -c make VERBOSE=1' returned a non-zero code: 2
mac: ~/Desktop/docker/blackbird master $

**Comment by greatwolf** [comment]
This is very strange, it looks like something else is interfering or clashing with src/bitcoin.cpp. It looks like that file isn't getting compiled but somehow src/bitcoin.o exist anyway. Where is that object file coming from?

Try forcing a rebuild of all targets using `-B`, eg.

    RUN make -B VERBOSE=1

**Comment by assafwo2** [comment]
Successfully built!!!!!




mac: ~/Desktop/docker/blackbird master $ docker build -t blackbird .
Sending build context to Docker daemon 16.32 MB
Step 1/6 : FROM ubuntu:16.04
 ---> f7b3f317ec73
Step 2/6 : MAINTAINER Alex Gandy <alexgandy@gmail.com>
 ---> Using cache
 ---> fe7d7e7a203b
Step 3/6 : RUN apt-get update   && apt-get install -yq --no-install-recommends   libssl-dev   libjansson-dev   libcurl4-openssl-dev   libsqlite3-dev   sendemail   make   gcc   g++   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> ae613f27c0de
Step 4/6 : COPY . /blackbird
 ---> 27f4b5532b92
Removing intermediate container 63b40bcd2368
Step 5/6 : WORKDIR /blackbird
 ---> a20760a43cfb
Removing intermediate container af6d7041be22
Step 6/6 : RUN make -B VERBOSE=1
 ---> Running in 4becc3ff5be4
Compiling shell.o:
gcc -std=c99 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c extern/sqlite3/src/shell.c -o shell.o
Compiling sqlite3.o:
gcc -std=c99 -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c extern/sqlite3/src/sqlite3.c -o sqlite3.o
Archiving libsqlite3.a:
ar rv libsqlite3.a sqlite3.o
r - sqlite3.o
Linking sqlite3:
gcc  -L . shell.o -o sqlite3 -lsqlite3  -lpthread -ldl
Compiling src/curl_fun.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/curl_fun.cpp -o src/curl_fun.o
Compiling src/bitcoin.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/bitcoin.cpp -o src/bitcoin.o
Compiling src/check_entry_exit.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/check_entry_exit.cpp -o src/check_entry_exit.o
Compiling src/time_fun.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/time_fun.cpp -o src/time_fun.o
Compiling src/db_fun.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/db_fun.cpp -o src/db_fun.o
Compiling src/result.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/result.cpp -o src/result.o
Compiling src/parameters.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/parameters.cpp -o src/parameters.o
Compiling src/main.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/main.cpp -o src/main.o
Compiling src/exchange/gdax.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/gdax.cpp -o src/exchange/gdax.o
Compiling src/exchange/bitstamp.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/bitstamp.cpp -o src/exchange/bitstamp.o
Compiling src/exchange/btce.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/btce.cpp -o src/exchange/btce.o
Compiling src/exchange/poloniex.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/poloniex.cpp -o src/exchange/poloniex.o
Compiling src/exchange/itbit.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/itbit.cpp -o src/exchange/itbit.o
Compiling src/exchange/gemini.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/gemini.cpp -o src/exchange/gemini.o
Compiling src/exchange/kraken.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/kraken.cpp -o src/exchange/kraken.o
Compiling src/exchange/okcoin.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/okcoin.cpp -o src/exchange/okcoin.o
Compiling src/exchange/bitfinex.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/exchange/bitfinex.cpp -o src/exchange/bitfinex.o
Compiling src/utils/base64.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/utils/base64.cpp -o src/utils/base64.o
Compiling src/utils/send_email.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/utils/send_email.cpp -o src/utils/send_email.o
Compiling src/utils/restapi.o:
g++ -Wall -pedantic -std=c++11 -Wno-missing-braces -O2 -DNDEBUG -I ./src -I ./extern/sqlite3/include -c src/utils/restapi.cpp -o src/utils/restapi.o
Linking blackbird:
g++  -L . src/curl_fun.o src/bitcoin.o src/check_entry_exit.o src/time_fun.o src/db_fun.o src/result.o src/parameters.o src/main.o src/exchange/gdax.o src/exchange/bitstamp.o src/exchange/btce.o src/exchange/poloniex.o src/exchange/itbit.o src/exchange/gemini.o src/exchange/kraken.o src/exchange/okcoin.o src/exchange/bitfinex.o src/utils/base64.o src/utils/send_email.o src/utils/restapi.o -o blackbird -lsqlite3 -lcrypto -ljansson -lcurl  -lpthread -ldl
 ---> 47f4ae4f841c
Removing intermediate container 4becc3ff5be4
Successfully built 47f4ae4f841c
mac: ~/Desktop/docker/blackbird master $
