### ISSUE TITLE
Negative target whilst short on Bitfinex

### ISSUE THREAD

**Issue by mdrankin** [butor/blackbird#167]
After my last trade completed (reached a target of 0.60%) the new trade made by Blackbird has a target of -0.44% (Bitfinex/Bitstamp) which doesn't make sense to me. Wouldn't a negative target mean that Blackbird is looking for Bitstamp to be higher than Bitfinex? I would have thought Blackbird would wait to find a bigger price gap between Bitfinex and another exchange.

I am using the default blackbird.conf settings.

Here is the log entries for the current trade;
```
[ 05/10/2017 22:19:18 ]
   Bitfinex:    1,779.70 / 1,780.20
   Bitstamp:    1,761.40 / 1,762.81
   Kraken:      1,771.11 / 1,773.98
   ----------------------------
   Bitstamp/Bitfinex:    0.96% [target  0.08%, min  0.96%, max  1.05%]   trailing  0.97%  1/1
<Bitstamp> Looking for a limit price to fill 0.014006 BTC...
<Bitstamp> order book: 5.094113@$1,762.81
<Bitfinex> Looking for a limit price to fill 0.013873 BTC...
<Bitfinex> order book: 1.712500@$1,779.70

[ ENTRY FOUND ]
   Date & Time:       05/10/2017 22:19:18
   Exchange Long:     Bitstamp (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        $1,762.81 (target)
   Price Short:       $1,779.70 (target)
   Spread:            0.96%
   Cash used:         $24.69 on each exchange
   Exit Target:       -0.44%
<Bitstamp> Trying to send a "buy" limit order: 0.014006@$1,762.81...
<Bitstamp> Done (order ID: ******)

<Bitfinex> Trying to send a "sell" limit order: 0.013873@$1,779.70...
<Bitfinex> Done (order ID: ******)

Waiting for the two orders to be filled...
Done

WARNING: 5 second(s) too late at 05/10/2017 22:19:21

[ 05/10/2017 22:19:27 IN MARKET: Long Bitstamp / Short Bitfinex ]
   Bitfinex:    1,779.70 / 1,779.80
   Bitstamp:    1,761.40 / 1,762.81
   Kraken:      1,771.11 / 1,773.98
   ----------------------------
   Bitstamp/Bitfinex:    1.04% [target -0.44%, min  1.04%, max  1.04%]
```

**Comment by butor** [comment]
The exit target, -0.44% in your case, is computed based on the parameters `SpreadEntry` (more precisely on `res.spreadIn`), `SpreadTarget` and the fees ([link to the code](https://github.com/butor/blackbird/blob/master/src/check_entry_exit.cpp#L114)):
```
res.exitTarget = res.spreadIn - params.spreadTarget - 2.0*(res.feesLong + res.feesShort);
```

What parameters do you use? It seems that you used 0.08% for `SpreadEntry`. If that's the case yes, it's possible to get a negative  exit target. It means that the position will be closed when Bitstamp is above Bitfinex by 0.44%.

**Comment by mdrankin** [comment]
Ok so a higher spread entry would prevent this?

**Comment by butor** [comment]
Yes

**Comment by mdrankin** [comment]
Yep, you are correct, my config file has SpreadEntry=0.00080 which explains the issue, should have been SpreadEntry=0.008
