### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#168]
I trust it is okay for me to write some pages in the wiki? I took the info that was provided in some of the issues and started to write a manual for beginners, like me. You know how they say you learn by teaching?

Anyway, I write so that you can see what I am missing. You now have the opportunity to teach me, how to teach others and correct me where I am wrong.

Thank you for the opportunity to learn together.
If you could let me know what your thoughts are on the wiki I could edit it.

**Comment by butor** [comment]
Thank you @jw4wellness for your work on the Wiki about compiling on Windows. I got many questions about how to compile Blackbird on Windows, so such a Wiki page will be useful to the community.

**Comment by jw4wellness** [comment]
Thank you.
I also think this will benefit society.
I appreciate that you express your appreciation and just as background I
wish to mention my experience because I think we can all learn from it. I
have no ill will, so please don't be offended. I just offer a learning
experience.
I wanted to give up many times, but my local friend Jack helped me a lot.
As you tag along let me tell you the story.

*How I see my experience:*
There were too many kind people trying to help and each one has a different
method and then they interject their idea and leave me hanging. So I would
start following one expert's (or person I assumed to be an expert's because
s/he talks about something I don't know) advice and run into snags and ask
for guidance. Maybe they saw it as too much work or I am too needy and
stopped replying?
Anyway, so I thought, "no wonder so few people support the project because
if it is this confusing, who will want to struggle like this?" Many people,
wife, and colleagues told me to rather just give up because of the effort I
put in and the time it takes me that I am not getting paid for. But I value
learning.
And I know that when you are an expert, you forget what you needed when you
were a newbie. So I figured this project just needs a newbie so that s/he
can connect the dots from newbie to expert if I could only found experts
that would hang in there with me like Jack did.
So I respect Jack's time and stopped writing, because I don't want to run
to him, with all my questions. I can improve the wiki even more and I need
help.

If kind people like you could stick with me through it all I think we would
get more support for the project because more newbies, like me, will be
able to understand what they should do. The more people who can learn the
more developers/support we would have for the app, isn't it?

I get discouraged when I google something and I find 20 different ways and
they are all different than the one the blackbird expert suggested I use.
Maybe 1 or 2 of those methods would work, the other are just some wild
theory, but how does a newbie like me, know which 2 are good? Hence I ask
the community. Then experts suggest I google first before I ask and it
feels like a waste of time for both of us.

I am googling but don't find the answer and sometimes I google in the wrong
places because I don't know, what I don't know. (See link. Stage one
*Unconscious
incompetence*) for example, I don't know what search terms to use in some
instances and hence after 45 google searches, I might not get one answer,
while after 1 google search an expert could get 30 + good answers because
they are unconsciously competent (Stage 4).

Anyway, if they could please forgive me for asking so many questions I
could continue to improve the wiki and we could help so much more people,
isn't it?

So if you could please bare with me as I transition from stage 1 to stage 2
to stage 3 to stage 4 I could write out the process and we could contribute
that to the community because most people are at stage one. They don't know
what is bitcoin, they don't know what is arbitrage and they don't know what
they could learn from it. They don't even know programming and it they do,
what language do they know? They don't know how this will benefit society.

For more information:
https://en.wikipedia.org/wiki/Four_stages_of_competence
Looking forward to working together.
JW

**Comment by butor** [comment]
Hi @jw4wellness Thanks for your message. Yes, I always admire when people are _in the zone_, the phenomenon that occurs when they reach stage 4. Very satisfying, whether it happens to people performing intellectual activities, sports or arts ;-) It's a great goal in life.

I saw in the other threads that you have successfully compiled Blackbird. Well done!

**Comment by jw4wellness** [comment]
Thank you. I'm making progress. I would like to know how to use it in my
investment strategy too. It seems like one can't use it with the bull
market going on right now, is it?

**Comment by greatwolf** [comment]
It should matter whether it's a bull market or bear market, the strategy is suppose to be market neutral. It doesn't mean this strategy is risk free though, you still have to consider fundamental factors, like for example, finex's recent fiat withdraw issues causing the spread to never close.

**Comment by jw4wellness** [comment]
Yes it is true. The spread not closing was actually the issue.
Maybe we could make it a priority to have more than one exchange to short
on? If we have 3 or 4 exchanges to short on then we could be prepared
should something like that happen again. It will also enable us to
"reverse" when the spread closes. Meaning we could then short on the other
exchange and long on bitfinex when the spread swings.
How do you think?
do you know of a script that could buy at one exchange and sell at another
one and then convert to another currency and sell it again at another
exchange?
For example. When there is a spread. Buy BTC low at BTC-e and sell it at
the higher price on finex. Then buy another currency and offload that
somewhere else?

*--*
*Oh, by the way!*
We are introducing a solution for people who pay too much tax. Learn More
Here: http://eepurl.com/cxT-jD​

*Talk Soon,*
*Jan-Willem Kühn*
*Bookkeeper*
www.e-galdesigns.com
Phone/Text: (226) 388-1304
Fax: (877) 709-2588
*IMPORTANT Disclaimer: *The contents of this email and any attachments are
confidential. They are intended for the named recipient(s) only. If you
have received this email by mistake, please notify the sender immediately
and do not disclose the contents to anyone or make copies thereof.

If you are not the recipient, you are hereby notified that any disclosure,
copying, distribution or taking action in connection with the contents of
this information is strictly prohibited and may be unlawful.

**Comment by butor** [comment]
Yes, Blackbird would be greatly improved if we can connect it to other exchanges, specially the ones with high volume where short selling is easy to implement ...and allowed for US residents.

Regarding your second question, what you describe is non market-neutral arbitrage. I don't know such a script, but you would need to take into account the latency of the following chain: BTC → Currency1 → Currency2 → BTC.

**Comment by jw4wellness** [comment]
Yes, that is true. Thank you. Did you know that if you have a corporation
or a trust in another country like Panama, that entity is not a US citizen?
There might also be a market for blackbird in Russia, China, and the other
Bricks countries so if we could connect to other exchanges they could get
onboard too, right?

**Comment by butor** [comment]
Yes definitely, that's why I want to upgrade Blackbird from a BTC/USD arbitrage only to a more general `Leg1/Leg2` arbitrage, that could be ETH/BTC, BTC/EUR, ETH/KRW and so on.

**Comment by jw4wellness** [comment]
That is a brilliant idea, what is the next step to doing it?

**Comment by sbarale** [comment]
Count me, in. Albeit available time is still a luxury, I think I can contribute to this project.
