### ISSUE TITLE
Windows Subsystem for Linux

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#169]
Do you really need that too? 
When I used the exe that @greatwolf provided it worked fine on my windows 10. I just installed the subsystem because another user suggested it, but I didn't have a use for that. 

Maybe we can skip that in the wiki to avoid information overload on newbies?

**Comment by greatwolf** [comment]
That's not needed, the purpose of of that subsystem is to create a linux like build environment. However MinGW is itself a native binary that runs directly on Windows as a host and it creates native PE binaries that Windows can directly run. So this linux subsystem layer isn't needed.

**Comment by jw4wellness** [comment]
Thank you
​I Updated the wiki with that as a second option.
