### ISSUE TITLE
Wiki Question

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#170]
@greatwolf wrote:
To build, run this command from the project root (aka same location as blackbird's makefile):
How do I do this with mingw on windows?
I downloaded it and all run it and all I can find is 
![black 03](https://cloud.githubusercontent.com/assets/26123052/25969977/65a31a1e-366d-11e7-9262-a16bca26179b.jpg)
When I open it it looks like this:
![black 04](https://cloud.githubusercontent.com/assets/26123052/25970022/965b65c6-366d-11e7-9bc3-086953161edb.jpg)
It is for this wiki page. [IF you could just answer there](https://github.com/butor/blackbird/wiki/1-How-to-compile-the-blackbird-program-from-source-code) we could make it easier to understand for the next guys.

**Comment by greatwolf** [comment]
You can just download the toolchain from mingw-w64's sourceforge page: https://sourceforge.net/projects/mingw-w64/files/?source=navbar.

TDM-gcc is another gcc port based off of MinGW: http://tdm-gcc.tdragon.net

**Comment by jw4wellness** [comment]
So I first download the mingw program like I showed above.
Then the toolchain
Then TDM-gcc
So I need al three of them or would just one of them do?

**Comment by jw4wellness** [comment]
As you can see from the below, there are various links with toolchain in the name: ![black 05](https://cloud.githubusercontent.com/assets/26123052/25974076/6361ac92-367d-11e7-9147-a8d5e1d4cfcf.jpg)
Which one are you refering to above with "You can just download the toolchain from mingw-w64's sourceforge page"

**Comment by greatwolf** [comment]
You only need one of them, scroll down you'll find a list of the different toolchain releases. I suggest getting `i686-posix-*` for best compatibility; any version will work.

**Comment by jw4wellness** [comment]
Okay,
So I download this one underlined?
![black 06](https://cloud.githubusercontent.com/assets/26123052/25975997/27714642-3688-11e7-843e-34e11054e836.jpg)

**Comment by jw4wellness** [comment]
I have this one, MinGW-W64-install.exe do I need that or did I download that in vain?

**Comment by greatwolf** [comment]
Yes, download and unzip that somewhere. Add the subdirectory mingw/bin to your `PATH`. Confirm it works by opening a 'cmd.exe' terminal and check the commands:

    g++ --version
    mingw32-make --version

You can delete Mingw-w64-install.exe.

**Comment by jw4wellness** [comment]
How do I add that to my path? I run it like you said next and then I got this: ![black 07](https://cloud.githubusercontent.com/assets/26123052/26009931/540b1298-3721-11e7-8bd8-a3166e425092.jpg)

**Comment by greatwolf** [comment]
Something like

    setx PATH "%PATH%;c:\mingw\bin"

modify it as appropriate for your location.

Also I suggest trying to google for the answer first since asking here every time you encounter an issue is just not very efficient approach.

**Comment by jw4wellness** [comment]
I do google thanks, I just don't always find the answer. Sometimes there are conflicting answers and I think it is best to stick to one expert and learn from them or I get confused like with the windows subsystem and various mingw versions. Like in my previous questions elsewhere.
Other times I do not know if their solution would work in our situation. Sorry about that.
So I did what you recommended and this is the result: 
![black 08](https://cloud.githubusercontent.com/assets/26123052/26016082/efce9b10-3739-11e7-9e2d-af1e5d67da32.jpg)
Did I do something wrong?
Another question, should I point the link of "Mingw or another compiler for windows" on the page https://github.com/butor/blackbird/wiki/0-Things-you-need-to-compile-Blackbird-on-Windows-10 to https://mingw-w64.org/ or to 
i686-posix-* that you posted above?
PS: I am eager to learn and so I aim to do it as fast as possible. If you could please, provide me with the exe version I could install it and find the answers in the meanwhile on google and not be pressed to have it up and running.

**Comment by cattaneoriccardo** [comment]
Sorry if I ask, but why are you not using docker instead?

**Comment by jw4wellness** [comment]
What is docker?

**Comment by jw4wellness** [comment]
use it instead of what?

**Comment by greatwolf** [comment]
You need to start a new terminal for it to be effective. I also suggest not putting the toolchain in the blackbird repo, mingw really belongs in it's own directory relative to `C:\`'s root.
