### ISSUE TITLE
Bitfinex order failures

### ISSUE THREAD

**Issue by aaur0** [butor/blackbird#172]
I have setup blackbird with Bitfinex + Gemini. The buy orders in Gemini are executed right however short sell orders in Bitfinex fail with the following error message :

> <Bitfinex> Trying to send a "sell" limit order: 0.011007@$1798.80...
> <Bitfinex> Error with response: This pair cannot be traded on margin.
> <Bitfinex> Done (order ID: 0)
>
> Waiting for the two orders to be filled...
> Done
> WARNING: 9 second(s) too late at 05/14/2017 17:22:51

**Comment by greatwolf** [comment]
I get the same thing too. Are you in the US? That's likely the reason.

**Comment by aaur0** [comment]
Yes. I am in the US.

**Comment by butor** [comment]
Indeed: [link here](https://support.bitfinex.com/hc/en-us/articles/115000580465-Can-US-Residents-Trade-on-Margin-).

**Comment by nborggren** [comment]
placing an "exchange limit" order works in the US still.  "limit" order points to the margin account.

**Comment by butor** [comment]
Yes @nborggren, but you won't be able to margin trade with exchange limit orders.
