### ISSUE TITLE
Adding BTC-e as an exchange and its authRequest() function

### ISSUE THREAD

**Issue by gbsilp** [butor/blackbird#173]
Hi all,

I've been trying to learn a bit about cryptocurrencies, coding etc etc and thought that a nice way may be to work on something here.  Anyway, I've got the code compiling and running which was the first hurdle and thought I'd try to add BTC-e as another exchange.  

I've been trying to figure out how to add BTC-e as an exchange but I have no clue  about API authentication so when it comes to the authRequest() function I am flummoxed.  My usual strategy of looking at the cpp files for the other exchanges and figuring out by trial and error (lots of those in the debug window!) is failing miserably, as presumably each exchange has its own requirements for the structure of the request.

I've looked at the BTC-e https://btc-e.com/tapi/docs#auth but it makes little sense. I simply don't have the knowledge to understand the structure of the API request, let alone write it. I've done all the necessary declarations for the functions in the header and config files, so a functino si ready to go.  Is there anyone who can give me any pointers at least as to the structure of the request I am aiming for?

thanks

**Comment by greatwolf** [comment]
I would start with googling how http rest-style request works. There are plenty of tutorials to help.

For blackbird, check out https://github.com/butor/blackbird/blob/master/src/utils/restapi.h and use that to send the request. You can also check out https://github.com/greatwolf/cryptofu/blob/master/exchange/btce.lua#L11 which shows a working auth implementation for btc-e using Lua.

**Comment by gbsilp** [comment]
Thanks greatwolf, I feel like I'm inching closer.  The thing I can't seem to understand is the structure of the string that is to be hashed, and I can't work it our from your Lua code (the "post_data" string).  

I am currently concatenating the nonce with the request eg (nonce=1494912588255&request=/getinfo) which then gets hashed and signed, but the query still returns "success:0" (i.e. FAIL...!).  Its not obvoius to me from the BTC-e documentation what the structure of the string should look like for the getinfo request.  How does one determine what this string should look like?

**Comment by greatwolf** [comment]
It looks like you're using the wrong name for the parameter. It's suppose to be `method` not `request`. There's also no forward slash in the method name. eg. `nonce=123456&method=getInfo`

**Comment by Newar417** [comment]
Just FYI, if I remember correctly, there is a quirk with BTC-e API. This is a comment in the spreadbot1000 code: 

"Special of BTC-e as an order that has directly been fulfilled the order id returned is always 0"

**Comment by gbsilp** [comment]
After trying most of the night, I think I am going to have to (temporarily) admit defeat on this.  I simply do not know enough about computing in general as my knowledge only extends to hacking about with recognisable bits of code.  I think its also possibly to do with the fact that the URL for the private api at BTC-e (https://btc-e.com/tapi)  is different to the URL for the public api (https://btc-e.com).  I'll look again in a couple of days after my eyes can focus again.  Thanks for the help thus far.

**Comment by jw4wellness** [comment]
Do one really have to do all of that @gbsilp ? Can't one just add the key info in the conf file? Like you do with the other?

**Comment by butor** [comment]
@jw4wellness The connection to BTC-e hasn't been implemented in Blackbird yet
