### ISSUE TITLE
stop_after_notrade not working

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#177]
Hi the contents of the file states:
"(while Blackbird is running, use this file in the working directory to exit Blackbird after the last arbitrage trade closes. Rename or delete it if you don't want to stop Blackbird)
"
while the program runs I tried to delete the stop_after_notrade_ because I want to exit the program because of a needed restart on my system. Then it would not delete since it is locked. So I created a new file called stop_after_notrade screenshot http://prntscr.com/f98l5r 

reading the instructions again as I post here I see I should delete or rename it if I do not want it to stop. So what do I do to make it stop?

**Comment by greatwolf** [comment]
You actually need to rename it, by removing the trailing underscore. eg. from `stop_after_notrade_` to `stop_after_notrade`
