### ISSUE TITLE
Manually Exit Blackbird?

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#178]
HI
I for had to get out of market at bitfinex and okcoin manually, so I closed my positions at both exchanges manually. Now that I restart blackbird it still shows I am in the market.
Here is the log:
```
[ 05/19/2017 05:27:27 IN MARKET: Long OKCoin / Short Bitfinex `]`
   Bitfinex: 	1,974.00 / 1,974.10
   OKCoin: 	1,925.01 / 1,925.67
   Kraken: 	1,923.19 / 1,928.39
   BTC-e: 	1,865.67 / 1,866.67
   ----------------------------
   OKCoin/Bitfinex:	 2.55% [target -0.21%, min  2.55%, max  2.55%]
```
So it is stuck and will not trade on kraken and okcoin. I don't want to trade on bitfinex anymore. How do I reset blackbird please?

**Comment by oiovoyo** [comment]
if you closed all position, please remove this file : restore.txt, and restart blackbird

**Comment by jw4wellness** [comment]
thank you
