### ISSUE TITLE
How to short on okcoin

### ISSUE THREAD

**Issue by jw4wellness** [butor/blackbird#179]
![black 10](https://cloud.githubusercontent.com/assets/26123052/26244792/6666a518-3c5f-11e7-8db6-9f1173ccda37.jpg) when I click on the link there is a lot of options and after doing a ctrl +F I don't even find the word short? 
So what do I do to short on OKcoin (or any other exchange) and not on bitfinex, please?

**Comment by butor** [comment]
For the moment short selling is only implemented in Bitfinex
