### ISSUE TITLE
Compiling issue for me. 

### ISSUE THREAD

**Issue by rmak168** [butor/blackbird#18]
Hello all, i was wondering if someone can help me resolve my issue. During make i get this error. How can i fix it? I don't know cpp well.  Thanks in advance!. 

rmak@V400:~/bb/blackbird-master$ make
g++ -c -g -Wall -O2  src/bitfinex.cpp -o src/bitfinex.o
src/bitfinex.cpp: In function ‘bool Bitfinex::isOrderComplete(CURL*, Parameters, int)’:
src/bitfinex.cpp:92:73: error: ‘json_boolean_value’ was not declared in this scope
   bool isComplete = !json_boolean_value(json_object_get(root, "is_live"));
                                                                         ^
make: *** [src/bitfinex.o] Error 1

**Comment by butor** [comment]
Hi @rmak168,

Your Jansson version is probably too old. Please install Jansson __2.7__ minimum and try again.

**Comment by rmak168** [comment]
Thank you! that fixed my problem.

**Comment by butor** [comment]
Great! I close the issue.
