### ISSUE TITLE
bug, unequal exposure on long/short exchanges

### ISSUE THREAD

**Issue by mathias-dietrich** [butor/blackbird#180]
PRECONDITION: after successful trading a small amount of BTC ist left in Kraken;

Bot tries to sell with:

BTC exposure on Kraken: 0.000004
BTC exposure on Bitfinex: -0.023521

<Kraken> Trying to send a "sell" limit order: 0.000004 @ $1,947.48...
{"error": ["EOrder:Order minimum not met"]}

**Comment by butor** [comment]
Hi @mathias-dietrich, something was off during the trade on Kraken:

```
BTC exposure on Kraken:    0.000004
BTC exposure on Bitfinex: -0.023521
```

 Only 0.000004 BTC were traded, but it should be something close to what was traded on Bitfinex (0.023521). What was the quantity of the _first_ trade sent to Kraken?
