### ISSUE TITLE
Problems compiling with Docker

### ISSUE THREAD

**Issue by zax988** [butor/blackbird#181]
Hello! I installed Docker and executed the commands to get Docker to build the container. It executed but at Step 6 it gives an error. Can anyone help?

PS C:\Users\Jonathan Pumarol\Desktop\blackbird-master> docker build -t blackbird .
Sending build context to Docker daemon  1.04 GB
Step 1/6 : FROM ubuntu:16.04
 ---> ebcd9d4fca80
Step 2/6 : MAINTAINER Alex Gandy <alexgandy@gmail.com>
 ---> Using cache
 ---> 6a77495347ff
Step 3/6 : RUN apt-get update   && apt-get install -yq --no-install-recommends   libssl-dev   libjansson-dev   libcurl4-openssl-dev   libsqlite3-dev   sendemail   make   gcc   g++   && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 0d285e2617c2
Step 4/6 : COPY . /blackbird
 ---> 2a4b59245053
Removing intermediate container 796ac63407a4
Step 5/6 : WORKDIR /blackbird
 ---> f7ea0e52a1bc
Removing intermediate container 7b6d85549abc
Step 6/6 : RUN make -B
 ---> Running in 2154b65f8bc1
make: *** No rule to make target 'shell.o', needed by 'sqlite3'.  Stop.
The command '/bin/sh -c make -B' returned a non-zero code: 2
PS C:\Users\Jonathan Pumarol\Desktop\blackbird-master>

**Comment by butor** [comment]
Hi @zax988, please take a look at issue #140.

**Comment by zax988** [comment]
Thank  you so much :)
