### ISSUE TITLE
Not all pair exchanges are used

### ISSUE THREAD

**Issue by rstormsf** [butor/blackbird#183]
I'm trying to figure out why there is no check for lets say
```
GDAX/BitStamp
``` 
??? 
Why Gdax is only being checked against 
```
GDAX/Bitfinex:	 0.03% [target  0.80%, min -0.44%, max  0.03%]
   GDAX/Poloniex:	-1.25% [target  0.80%, min -1.83%, max -1.25%]
```
Bitfinex and poloniex.

Also, it doesn't make sense to check against USDT exchanges cause it's not real representation of actual USD value, and it's not always 1:1 USD/USDT

**Comment by greatwolf** [comment]
It's mainly because bitfinex is the only exchange that let's you take a short position on margin. Actually, Poloniex shouldn't be there IMO since shorting on margin on USDT/BTC isn't possible either.

**Comment by rstormsf** [comment]
Correct. @greatwolf 
DO you know any bots that don't use short?

**Comment by LorenzoPanico** [comment]
is there someone who is using this? can you please tell me if it is profitable?
