### ISSUE TITLE
Blackbird running inside Docker

### ISSUE THREAD

**Issue by Samuelvs** [butor/blackbird#185]
I have encountered issues when trying to run it using docker:
Log:
> Deploying 'blackbirdContainer  Dockerfile: Dockerfile'...
> Building image...
> Step 1/6 : FROM ubuntu:16.04
> 
>  ---> ebcd9d4fca80
> 
> Step 2/6 : MAINTAINER Alex Gandy <alexgandy@gmail.com>
> 
>  ---> Using cache
> 
>  ---> 5ee75e8c2991
> 
> Step 3/6 : RUN apt-get update   && apt-get install -yq --no-install-recommends   libssl-dev   libjansson-dev   libcurl4-openssl-dev   libsqlite3-dev   sendemail   make   gcc   g++   && rm -rf /var/lib/apt/lists/*
> 
>  ---> Using cache
> 
>  ---> 522de4e9b354
> 
> Step 4/6 : COPY . /blackbird
> 
>  ---> 66c09b0c355a
> 
> Removing intermediate container 43a535beebce
> 
> Step 5/6 : WORKDIR /blackbird
> 
>  ---> 59759fe289eb
> 
> Removing intermediate container 8fc1450e8ca6
> 
> Step 6/6 : RUN make
> 
>  ---> Running in c3726b644f6f
> 
> make: *** No rule to make target 'shell.o', needed by 'sqlite3'.  Stop.
> 
> Error: ResponseItem.ErrorDetail[code=2,message=The command '/bin/sh -c make' returned a non-zero code: 2]
> Failed to deploy 'blackbirdContainer  Dockerfile: Dockerfile': The command '/bin/sh -c make' returned a non-zero code: 2
> 

Does anybody know what to do?

**Comment by greatwolf** [comment]
See issue #140

**Comment by Samuelvs** [comment]
Thank you very much.
