### ISSUE TITLE
HELP! Keep getting Opportunity found but error with the order books

### ISSUE THREAD

**Issue by nicklello** [butor/blackbird#187]
Hi,

This is very likely a newby error, but after searching around I still cannot find a solution.

I have Bitfinex, OKCoin and Kraken enabled

As far as I can tell no trades have been made within the last month.

I keep getting the following in my logfile:-

[ 06/01/2017 14:12:45 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    2,351.3000 / 2,354.6000
   OKCoin:      2,522.2000 / 2,522.2100
   Kraken:      2,449.7670 / 2,452.9950
   ----------------------------
   OKCoin/Bitfinex:     -6.64% [target  6.27%, min -6.80%, max -6.64%]   trailing -6.72%  1/1
<Bitfinex> WARNING: BTC position not available, return 0.0
<OKCoin> Looking for a limit price to fill 0.000000 BTC...
<Bitfinex> Looking for a limit price to fill 0.000000 BTC...
<Bitfinex> order book: 0.200000@$2,353.90
WARNING: Opportunity found but error with the order books (limit price is null). Trade canceled
         Long limit price:  0.00
         Short limit price: 2,353.90

What on earth have I done wrong ?

**Comment by greatwolf** [comment]
It sounds like 'restore.txt' is putting blackbird into a `IN MARKET` state. You can delete that file to reset but if you're in that state it means some kind of trade must have been carried out.

**Comment by nicklello** [comment]
Thankyou for that hint... the file had been around for so long I just assumed it came as part of a pull.

 

I have deleted the file and restarted blackbird, let's see how we get on now.
