### ISSUE TITLE
src/curl_fun.cpp:5:10: fatal error: 'jansson.h' file not found

### ISSUE THREAD

**Issue by chriscrutt** [butor/blackbird#188]
(using macOS Sierra) 

After doing "git clone --recursive  git://github.com/butor/blackbird.git" in /Users/username/ (creating a Blackbird folder) and downloading OpenSSL, Jansson, cURL, SQLite3 and sendEmail (and extracting) to /Users/username/ I proceeded to type "make" in the terminal. After some successes i recieved:

Compiling src/curl_fun.o:
src/curl_fun.cpp:5:10: fatal error: 'jansson.h' file not found
#include "jansson.h"
         ^
1 error generated.
make: *** [src/curl_fun.o] Error 1

I do not know why this happened, please help, thank you in advance

**Comment by greatwolf** [comment]
It looks like `make` can't find location of dependencies. See issue #114. In particular, scroll to the section where I described how to specify exactly where to look for those dependencies using `INC_DIR` and `LIB_DIR`.

**Comment by chriscrutt** [comment]
`mingw32-make VERBOSE=1 \` isn't a command for osx

**Comment by greatwolf** [comment]
Obviously not, use that as a starting point and modify the settings and commands as appropriate for your platform rather than following it verbatim.

**Comment by chriscrutt** [comment]
it's not working, ill just do it on my linux instead
