### ISSUE TITLE
repository blackbird not found

### ISSUE THREAD

**Issue by VincentPourcent** [butor/blackbird#189]
Hi,

I am trying to run the blackbird from docker:
docker run -v $(pwd)/blackbird.conf:/blackbird/blackbird.conf -it blackbird /blackbird/blackbird
I get:
Unable to find image 'blackbird:latest' locally
docker: Error response from daemon: repository blackbird not found: does not exist or no pull access.

Could you please help me with that?
Thank you

**Comment by alexgandy** [comment]
You need to build the image first, like in step one from the README. In the project directory, run the command 

```
docker build -t blackbird .
```

Once that executes successfully, you'll be able to run the `docker run...` command.
