### ISSUE TITLE
Hangs while downloading Bitstamp prices

### ISSUE THREAD

**Issue by butor** [butor/blackbird#19]
I am experiencing an issue that I have never faced before. When Blackbird is analyzing the market, it sometimes hangs after a few days, usually after between 1 to 6 days. The `blackbird` process doesn't crash and still runs but the output just hangs without any error or warning. It always happens at the same moment: when Blackbird downloads the prices from Bitstamp.

Here is the output file after the last hang:

```
[ 10/21/2015 01:54:40 ]
    Bitfinex:    271.67 / 272.00
    OKCoin:      272.30 / 272.31
    Bitstamp:    270.60 / 271.00
    Kraken:      265.13 / 271.28
    ItBit:       271.12 / 271.28
    ----------------------------
    Bitfinex/Kraken:     -2.53% [target  100.00%, min -2.69%, max -0.23%]
    OKCoin/Bitfinex:     -0.24% [target  100.00%, min -0.53%, max  0.47%]
    OKCoin/Kraken:       -2.64% [target  100.00%, min -2.73%, max -0.21%]
    Bitstamp/Bitfinex:    0.25% [target  100.00%, min -0.26%, max  1.01%]
    Bitstamp/Kraken:     -2.17% [target  100.00%, min -2.75%, max  0.48%]
    Kraken/Bitfinex:      0.14% [target  100.00%, min -0.15%, max  1.39%]
    ItBit/Bitfinex:       0.14% [target  100.00%, min -0.46%, max  0.31%]
    ItBit/Kraken:        -2.27% [target  100.00%, min -2.68%, max  0.00%]
 
[ 10/21/2015 01:54:45 ]
    Bitfinex:    271.67 / 272.00
    OKCoin:      272.22 / 272.23
```

And then nothing.

Does anybody experience this issue? I use the version currently on GitHub. Maybe a timeout on the _cURL_ calls would be necessary?

Thanks,
Butor

**Comment by julianmi** [comment]
I can confirm this bug. It happened to me once when I was on version 0.0.2 but in the last couple of days it occurred several times. I am currently also on the latest version. @butor are you sure that it always happens on Bitstamp?

I can almost certainly say that it is not a problem with the operating system like I thought at first. Like @butor said, the process is not being killed and still runs fine. I even tried redirecting stdout and stderr with debugging tools but there was no output.

The default cURL timeout `CURLOPT_TIMEOUT` is set to *0* which means that a transfer never timeouts. I added a timeout of 20 seconds for testing purposes. The commit is at https://github.com/julianmi/blackbird/commit/a5e0e2ea5ed75e6770b73a6ffb5cdb8e1f26e7d1 if anyone wants to help testing.

**Comment by butor** [comment]
Hi @julianmi sorry I didn't realize that my symptoms were the same as the ones you described to me a few weeks back.

Yes, so far I only experienced the issue after the line:

`OKCoin:      272.22 / 272.23`

But it may just be a coincidence. I will try out your 20-second timeout idea. Thanks.

**Comment by NateBrune** [comment]
Hi @butor, I can also add another confirmation. It happened to me while downloading other market prices as well as bitstamp. I am going to try out @julianmi's branch to see if that works. Thank you guys.

**Comment by butor** [comment]
``` curl_easy_setopt(curl, CURLOPT_TIMEOUT, 20L)``` seems to have fixed the issue. I don't experience this hang issue anymore. Thanks @julianmi and @NateBrune.
