### ISSUE TITLE
Can total Noob use this bitcoin Arbitrage software ?

### ISSUE THREAD

**Issue by Maju126** [butor/blackbird#190]
I have try to build this using Docker but fail  
got stuck in the step 2 I try to build a container using  nginx in mac with ITerm but got really confuse.
(https://www.youtube.com/watch?v=Vyp5_F42NGs)

i have no experience in code what so ever but thought i could learn from youtube and stuff
should i just give up?

**Comment by greatwolf** [comment]
Have you looked at the Docker section in the readme?

**Comment by Maju126** [comment]
Yes,i have read it. I spend have spend 5 hours trying with Nginx lol
1. Download and install docker 
2. Build container (docker build -t blackbird .)
3. Mount your configuration and run container (OS X/Linux) (docker run -v $(pwd)/blackbird.conf:/blackbird/blackbird.conf -it blackbird /blackbird/blackbird)

I have finished the 1 first step download and install 
![screen shot](https://user-images.githubusercontent.com/29227591/26875930-f34416aa-4bbe-11e7-9608-1deb9ac6884b.png)
the 2 step build container is were I am stuck.

how do you build container ?

**Comment by greatwolf** [comment]
You need to open a terminal shell a before you can enter those commands. It should be under *applications*->*utilities*.  Or try command + spacebar and type in "terminal".
