### ISSUE TITLE
output folder was not created on installation

### ISSUE THREAD

**Issue by jefferythewind** [butor/blackbird#194]
Hi, I am trying out your project.  I just installed it today to an EC2 server using your instructions on the main page.  Everything installed correctly without errors.  Good job!  One thing I noticed, is that the program wrote: 

`Log file generated: output/blackbird_log_20170608_135146.log` 

something like that, and I looked and the `output` folder was not even there.  I created it 

`mkdir output`

, and re-ran the program

`./blackbird` (everything default, so `demo=true`).  

and now I have the output log files.

So I don't know why the `output` folder wasn't created automatically, but it seems the program didn't have permissions to create it after installation.  just FYI, but really BRAVO on this project.

**Comment by butor** [comment]
Bug fixed. Now the `output` folder is part of the repository
