### ISSUE TITLE
demo=true, verbose=true not printing real-time output, only to log file

### ISSUE THREAD

**Issue by jefferythewind** [butor/blackbird#195]
Hi again, so just a little more feedback, no big deal really.  I installed the program, and keeping the config file as it was, with `DemoMode=true` and `Verbose=True`.  I see the nice output, for every 3 seconds in the log file, but it isn't printing the real-time stats to the console, which I figured it should with `Verbose=true`.

**Comment by butor** [comment]
Hi @jefferythewind Everything is printed into the log file. There is no information printed to the console, regardless the value of `Verbose`.

When `Verbose=False` you only see the details of the trades executed, but not the spreads that are printed every 3 seconds.

**Comment by jefferythewind** [comment]
Very well thank you, then I just assumed incorrectly about what it does.  I think a simple update to the reader would help. I will try to do that.
