### ISSUE TITLE
Not able to get BlackBird working

### ISSUE THREAD

**Issue by nasehim7** [butor/blackbird#198]
Hi! I wanted to use the Application in Demo Mode before using it on my account. I built it on my system(Linux 14.04), added two of my accounts but the problem that i'm facing is the terminal shows Log created and Blackbird is running but i'm not able to see anything further like the spot prices. I need some assistance on this? :)

**Comment by butor** [comment]
Hi @nasehim7 Could you please show us what you have in your log file?

**Comment by jebbgrenham** [comment]
`tail -f yourlogfile`

**Comment by nasehim7** [comment]
When i do ./blackbird, it says : 
Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

Log file generated: output/blackbird_log_20170610_202454.log
Blackbird is running... (pid 3420)

Where exactly is the log located? I can't find the output folder.

**Comment by mhusbyn** [comment]
See #194 . If you make a folder called 'output' in the root directory the logs should appear:
```
cd .../blackbird
mkdir output
```

**Comment by nasehim7** [comment]
Thanks It Helped :)

@butor This is the what log says : 
  Retry in 2 sec...
Error with cURL: Problem with the SSL CA cert (path? access rights?)
  URL: https://api.bitfinex.com/v1/ticker/btcusd
  Retry in 2 sec...
Error with cURL: Problem with the SSL CA cert (path? access rights?)
  URL: https://api.bitfinex.com/v1/ticker/btcusd
  Retry in 2 sec...
Error with cURL: Problem with the SSL CA cert (path? access rights?)
  URL: https://api.bitfinex.com/v1/ticker/btcusd
  Retry in 2 sec...

**Comment by greatwolf** [comment]
What's your directory structure? 'blackbird' executable and 'curl-ca-bundle.crt' should be in the same path. If not, you can change it in the 'blackbird.conf' through `CACert` field.

**Comment by nasehim7** [comment]
Thanks It works Now :) @greatwolf
