### ISSUE TITLE
Can you please Explain me three things : SpreadEntry, Spread Target, Trailing spread? & Why spread > 100 %

### ISSUE THREAD

**Issue by nasehim7** [butor/blackbird#199]
Hi I am attaching a screenshot of blackbird in demo mode. I dont understand why is Poloniex/Bitfinex spread so large and what does min max mean here? Is it that Min spread which should pe there before we start trading something like that? And what does Spread Entry, Target, trailing spread mean? Help would be really appreciated.
![first](https://user-images.githubusercontent.com/18035782/27009904-e5f9f460-4eb6-11e7-9f91-4706d0283e01.png)

**Comment by butor** [comment]
Poloniex shouldn't been shown in _Demo_ mode when the legs are _USD/BTC_. I'll fix that.

The parameters are explained on the [README](https://github.com/butor/blackbird/blob/master/README.md) file.

**Comment by nasehim7** [comment]
Why only bitfinex supports short and not other platforms, do you have an idea about this?

**Comment by butor** [comment]
I cannot reproduce your issue with Poloniex showed in _Demo_ mode, at least not with the current version.

Other platforms now support short selling, but Bitfinex was the first one. Moreover, the short selling is easily accessible through their API, which is not always the case with other exchanges.

I don't think I understand your other questions. Please see #100 for more information about the mechanism implemented.

**Comment by nasehim7** [comment]
Okay Thanks I get it now.
Thanks for the link, i read it earlier only and it's a hats off to this project. Maybe i have framed it incorrectly, I read it somewhere in the issues that blackbird waits if the spread keeps increasing. Tell me if i understand this correctly or not :
1. Before entering any trade, Blackbird checks for threshold target value. If current spread % is greater between exchanges, it enters.
2. Volume of BTC is decided by exposure (minimum of the two account).
I wanted to ask : When will it go long and when short? When will it exit the market? Also i want to understand : blackbird waits if the spread keeps increasing. :)

**Comment by nasehim7** [comment]
I understood All of it. It's actually a brilliant work done @butor. Genuinely clapping for you. :)

**Comment by butor** [comment]
Thanks @nasehim7! And your understanding is correct.

Regarding your last question:
> Also i want to understand : blackbird waits if the spread keeps increasing.

This is also correct. It's not explained in details in the README file, but take a look at issue #12 for more details about how Blackbird waits for the spreads to increase before trading an opportunity. The related parameters are `TrailingSpreadLim` and `TrailingSpreadCount`.
