### ISSUE TITLE
Porting Blackbird to C

### ISSUE THREAD

**Issue by julianmi** [butor/blackbird#20]
After consulting with @butor I began porting Blackbird to C for having a small and clean code base. Moreover, Blackbird does not make use of many OO features so porting should be straight forward. See the current working branch at https://github.com/julianmi/blackbird/tree/Cversion. Please feel free to make any suggestions or contributions to the port.

Additionally, what do you think about unit testing the core of Blackbird? Does anyone of you have experience with a unit testing framework for C?

**Comment by butor** [comment]
Hi @julianmi, thank you for the porting effort. I don't have a great experience in C unfortunately but let me know how I can contribute. And yes adding unit testing is a good idea.

Note that I just updated Blackbird with some improvements and I also added all the functions to connect the <a href="https://gemini.com/" target="_blank">Gemini exchange</a>.

**Comment by guribe94** [comment]
What is the advantage of a C version over the C++ version?

**Comment by julianmi** [comment]
Blackbird was performing very slow back then. The idea was to refactor large parts of the code base (see the gigantic main method) and use a low level approach to effectively scale the application. However, this might not be a problem anymore and can be closed.
