### ISSUE TITLE
OKCoin short selling capabilities

### ISSUE THREAD

**Issue by mauriziograssi** [butor/blackbird#200]
Hello there
Thank you very much for the work you guys have been doing so far. Brilliant !!

I noticed that OKCoin is now accepting short selling but this is not used yet as the parties which are normally selling short is Bitfinex. Am I correct ? Is it because of testing or anything specific ?

I saw pretty large spread between Bitfinex and OKCoin lately....

**Comment by butor** [comment]
Hi @mauriziograssi Yes that's correct. You can see a first implementation [here](https://github.com/butor/blackbird/blob/master/src/exchanges/okcoin.cpp#L88), but it hasn't been validated yet.

**Comment by mauriziograssi** [comment]
OK. Is there anything we can do to help out. I think everybody would benefit from it anyway.

**Comment by elsehow** [comment]
Is it possible to short sell on OKCoin, even if it hasn't been validated yet? Ditto to @mauriziograssi's question - happy to help out.

**Comment by BayesStreet** [comment]
@elsehow I would love to test it, but looks like OKCoin doesn't allow borrowing of <0.1BTC.

**Comment by elsehow** [comment]
@BayesStreet I see - that's a little more than I'm willing to spend on something that may not work (: and also a little more than people may be wanting to trade with in general. Definitely a limitation to using OKCoin as a Bitfinex replacement for short-selling.

**Comment by sbarale** [comment]
@butor Hit me up privately if you can (skype:sbarale), I can contribute to this project and I'm very interested to do so. I think it's a brilliant idea.

**Comment by butor** [comment]
Hi @sbarale I just sent you an email. Thanks
