### ISSUE TITLE
Using Blackbird for altcoin arbitrage?

### ISSUE THREAD

**Issue by riggedeggcam** [butor/blackbird#201]
How much work would it take to do this? Is it already feasible with minor tweaks, or is something larger needed?

**Comment by greatwolf** [comment]
I haven't tried it myself but I'd imagine it's possible do that. It would mostly involve going through the source and replacing all the places using btc/usd to the pair you're interested in. It'll be tedious and error prone however and you have to figure out which exchanges support the pair you want.

I believe @butor is working on supporting different altcoin pairs. You can hit him up on what the status is either here or on gitter chat.

**Comment by riggedeggcam** [comment]
I was thinking about Eth, mostly. As for exchanges, GDAX, Kraken, Poloniex, BitFinex, BitTrex, CoinMarketCap. Anything that supports Eth/USD, more or less.

**Comment by mauriziograssi** [comment]
I am interested to. Available if you like

**Comment by elsehow** [comment]
Poloniex would be nice, as it allows US users to trade on margin (unlike Bitfinex). It also has a wide array of altcoins.
