### ISSUE TITLE
Kraken long order remains open

### ISSUE THREAD

**Issue by todoniko** [butor/blackbird#203]
Hi, 
here is an interesting situation that occured recently. Arbitrage window has opened between Kraken & Bitfinex.
Kraken/Bitfinex:      0.93% [target  0.80%, min -1.48%, max  1.17%]
Long and Short orders were issued, but long order in Kraken remained open.
Here is the relevant part of the log file:
```
[ 06/11/2017 13:54:24 ]
   Bitfinex:    2,862.7000 / 2,864.4000
   OKCoin:      3,033.1000 / 3,033.1200
   Kraken:      2,827.7470 / 2,836.4180
   BTC-e:       2,831.0030 / 2,834.9980
   ----------------------------
   OKCoin/Bitfinex:     -5.62% [target  0.80%, min -7.22%, max -5.12%]
   Kraken/Bitfinex:      0.93% [target  0.80%, min -1.48%, max  1.17%]   trailing  1.09%  1/1
<Bitfinex> Looking for a limit price to fill 0.359652 BTC...
<Bitfinex> order book: 0.851500@$2,862.70
<Bitfinex> order book: 2.562165@$2,862.60

[ ENTRY FOUND ]
   Date & Time:       06/11/2017 13:54:24
   Exchange Long:     Kraken (id 2)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        2,827.01 (target)
   Price Short:       2,862.60 (target)
   Spread:            0.93%
   Cash used:         1,029.58 on each exchange
   Exit Target:       -0.47%

<Kraken> Trying to send a "buy" limit order: 0.362985 @ $2,827.01...
<Kraken> Done (transaction ID: ORDER-ID-IN-KRAKEN)

<Bitfinex> Trying to send a "sell" limit order: 0.359652@$2,862.60...
<Bitfinex> Done (order ID: ORDER-ID-IN-BITFINEX)

Waiting for the two orders to be filled...
{"ORDER-ID-IN-KRAKEN": {"misc": "", "refid": null, "userref": null, "status": "open", "descr": {"pair": "XBTUSD", "type": "buy", "price": "2827.010", "ordertype": "limit", "price2": "0", "order": "buy 0.36298500 XBTUSD @ limit 2827.010", "leverage": "none"}, "vol": "0.36298500", "fee": "0.00000", "opentm": 1497189293.2511001, "expiretm": 0, "vol_exec": "0.00000000", "starttm": 0, "cost": "0.00000", "oflags": "fciq", "price": "0.00000"}}
<Kraken> Order ORDER-ID-IN-KRAKEN still exists!
Long order on Kraken still open...
{"ORDER-ID-IN-KRAKEN": {"misc": "", "refid": null, "userref": null, "status": "open", "descr": {"pair": "XBTUSD", "type": "buy", "price": "2827.010", "ordertype": "limit", "price2": "0", "order": "buy 0.36298500 XBTUSD @ limit 2827.010", "leverage": "none"}, "vol": "0.36298500", "fee": "0.00000", "opentm": 1497189293.2511001, "expiretm": 0, "vol_exec": "0.00000000", "starttm": 0, "cost": "0.00000", "oflags": "fciq", "price": "0.00000"}}
<Kraken> Order ORDER-ID-IN-KRAKEN still exists!

========this loop of messages continue until cURL timeout and=========
<Kraken> No order exists
Done

WARNING: 12,101 second(s) too late at 06/11/2017 13:54:27

[ 06/11/2017 17:16:09 IN MARKET: Long Kraken / Short Bitfinex ]
   Bitfinex:    2,949.8000 / 2,949.9000
   OKCoin:      3,138.0300 / 3,148.3500
   Kraken:      2,895.2240 / 2,899.9360
   BTC-e:       2,860.0010 / 2,866.9990
   ----------------------------
   Kraken/Bitfinex:      1.89% [target -0.47%, min  1.89%, max  1.89%]

```
Why is blackbird placing long limit order below the current price? Doesn't this quarantee that if the market goes up this order will stay open too long?

There is second issue with Kraken implementation, because this order was still open even though 'No order exists' line. I presume that this is due to cURL timeout and the check for open orders. Wouldn't it be less confusing if order completion is checked with 
`private/QueryOrders` rather than `private/OpenOrders`?

**Comment by butor** [comment]
> Why is blackbird placing long limit order below the current price? Doesn't this quarantee that if the market goes up this order will stay open too long?

I guess you are referring to the difference between this line:
`   Kraken:      2,827.7470 / 2,836.4180`
And this line:
`<Kraken> Trying to send a "buy" limit order: 0.362985 @ $2,827.01...`

This happens when the exchange's order book changes between the two lines. On the second line, the order book is re-analyzed from scratch so that the limit price would reflect its very last status.

**Comment by todoniko** [comment]
Yes, that is what I meant.
So if during this calculation of the latest status, the price goes up, this limit order will be left hanging for price drop. And if the arbitrage window is closing above the price of this long order there will be loss. In other words only the short order will be executed and overall there is only loss. Is that correct?

**Comment by butor** [comment]
Yes, that's why we are aggressive regarding the limit prices, to make sure we get immediate executions. Two mechanisms in place for that:
- we _cross the spread_, meaning we buy at the ask and we sell at the bid.
- we make sure that the available liquidity is at least 3 times what we need at that price (parameter `OrderBookFactor`).

**Comment by photonherder** [comment]
By crossing the spread, don't you give up a lot?  Does Blackbird account for this before deciding whether to do the arbitrage at all?  If not, couldn't you lose money?  I don't speak C++, but I may learn just to use this program.  I don't suppose you know of a similar program in Python?  :)

**Comment by butor** [comment]
Yes we give up some margin, but we want our orders to be immediately executed to stay market-neutral at all times. This has a cost, and yes this cost is taken into account before trading: the spreads between exchanges are always calculated with the spread _crossed_.

I don't know any similar program in Python.

**Comment by photonherder** [comment]
Thanks!
