### ISSUE TITLE
Error: file cannot be open

### ISSUE THREAD

**Issue by niliss** [butor/blackbird#204]
Hi There,

Just wanted to check if this is a common bug or if this is something that only I get. I installed the script on lightsail, following this instructions: 

> sudo apt-get install libssl-dev libjansson-dev libcurl4-openssl-dev libsqlite3-dev sendemail make gcc g++
> mkdir blackbird
> cd blackbird
> git clone --recursive  git://github.com/butor/blackbird.git .
> mkdir build && cd build
> cmake -DCMAKE_BUILD_TYPE=Release  ..
> make

So far, so good, no errors, but then when I run 

> ./blackbird

The outcome is that I am getting an error:

> Error: file cannot be open .

I thought it was due to the fact that I have not set any API keys. So I set those in my script, but I still keep getting this error. Any help is greatly appreciated.

**Comment by greatwolf** [comment]
That message comes up if the configure file couldn't be opened. Try copying the blackbird executable to the project root directory. That's where the blackbird.conf is.

**Comment by niliss** [comment]
Works Like a charm! Just one more question. If you hit ./blackbird, it just shows it us running. It also shows the location of the log file. However, there is no output folder. Is there a way to actively show what blackbird is doing?

**Comment by kavernar** [comment]
The log file should be created in the "output" folder as you can see in the log when you start the app. If the folder doesn't exist you need to make it. After that you should be able to see the log file in that folder after you start the app.

**Comment by kavernar** [comment]
When you see the folder containing the log file, just enter this command
`tail -f blackbird_log_XXXXX`
*replace the Xs with the complete file name
this will show you live logs running

**Comment by butor** [comment]
I've added an `output` folder to the repository, so there is no more need to do it manually.
