### ISSUE TITLE
Disable unused exchanges

### ISSUE THREAD

**Issue by elsehow** [butor/blackbird#206]
Since not everyone uses all exchanges, we could save some bandwidth (and time) by disabling fetch from exchanges that aren't in use. Does such a feature exist?

**Comment by butor** [comment]
In _Demo_ mode, it is correct that all the exchanges are shown. The latency is less a problem there, because no trading occurs in _Demo_ mode.

However, when you switch `DemoMode` to false, only the exchanges for which you have put the credentials in _blackbird.conf_ are shown.

**Comment by elsehow** [comment]
I'll issue a PR that adds a note about this to the README.
