### ISSUE TITLE
ERROR: file cannot be open.

### ISSUE THREAD

**Issue by cryptoneep** [butor/blackbird#209]
Getting this after the build:

$ ./blackbird 
Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

ERROR: file cannot be open.

Any idea what file is referred to here?

Thanks!

**Comment by bluedragon9958** [comment]
Move the conf file into /blackbird/build

**Comment by greatwolf** [comment]
I've updated the error message to show the filename now in parameter. It should show up now in case of load failure.

**Comment by cryptoneep** [comment]
Thanks, that was obvious, but not to me in my early morning :)
