### ISSUE TITLE
Problem when calling "make"

### ISSUE THREAD

**Issue by Lexinek** [butor/blackbird#21]
Hello, i was going step by step through the instructions but when i enter "make" in terminal i get this error message:
```
src/bitfinex.cpp: In function ‘bool Bitfinex::isOrderComplete(CURL*, Parameters, int)’:
src/bitfinex.cpp:91:73: error: ‘json_boolean_value’ was not declared in this scope
   bool isComplete = !json_boolean_value(json_object_get(root, "is_live"));
``` 
Am i missing some package or did i miss something else?
Running on Ubuntu 14.04 LTS

**Comment by butor** [comment]
Hi @Lexinek,

Thank you for your interest. You need to use the <a href="http://www.digip.org/jansson" target="_blank">Jansson library </a> __v2.7__ minimum. You're probably using an older version, where `json_boolean_value` didn't exist. Please install Jansson v2.7 and try again.

Thanks
Butor

**Comment by Lexinek** [comment]
Thank you for your quick reply, this is exactly the fault.
Running ``` dpkg -s libjansson-dev ``` shows me that version 2.5-2 
But im absolutely desperate, tried apt-get update && apt-get upgrade, even tried to download and compile latest libjansson-dev from https://github.com/akheron/jansson/tree/2.7 still having the 2.5-2 version :(

**Comment by Lexinek** [comment]
Finally, i have successfully run make and i am able to run ./blackbird even though my terminal was showing my libjansson-dev version is 2.5-2 (i compiled and installed manually 2.7).

Really thank you.

**Comment by butor** [comment]
Well done @Lexinek! Enjoy Blackbird and let us know if you have any questions.
