### ISSUE TITLE
How to run Docker on CentOS?

### ISSUE THREAD

**Issue by imkane** [butor/blackbird#212]
The Dockerfile is written for Ubuntu ...

Sorry if this is a dumb question, it just won't work on CentOS 7. When trying to build it, I get errors like:

E: Unable to locate package libssl-dev
E: Unable to locate package libjansson-dev
E: Unable to locate package libcurl4-openssl-dev
E: Unable to locate package libsqlite3-dev
E: Unable to locate package sendemail
E: Unable to locate package make
E: Unable to locate package gcc

**Comment by butor** [comment]
Hi @imkane you need to install the missing packages, as explained [here](https://github.com/butor/blackbird#getting-and-building-the-software):

```
libssl-dev
libjansson-dev
libcurl4-openssl-dev
libsqlite3-dev (available as a Blackbird submodule)
sendemail
```

**Comment by imkane** [comment]
libssl-dev doesn't exist for CentOS 7.
