### ISSUE TITLE
Help to setup on a Windows machine

### ISSUE THREAD

**Issue by dmanman** [butor/blackbird#213]
Can anybody help me set up  Blackbird on a Windows machine with mingw

Here is what I did;

- Downloaded and install mingw
- Downloaded the blackbird source 
- Downloaded the other libraries
- Placed them all in directory
- Extracted them all to folders

I ran mingw

It was giving me some error about shell.0 and sqlite3.0 so I just created blank files with those names and put them in the blackbird-master directory

Here is the command and the output;

C:\Users\Smiles\blackbird\blackbird-master>mingw32-make VERBOSE=1 INC_DIR="-I C:/Users/Smiles/blackbirdextras/openssl-1.0.2l.tar -I C:/Users/Smiles/blackbirdextras/jansson-2.10.tar -I C:/Users/Smiles/blackbirdextras/curl-7.54.1.tar" LIB_DIR="-L C:/Users/Smiles/blackbirdextra/openssl-1.0.2l.tar/lib -L C:/Users/Smiles/blackbirdextras/jansson-2.10.tar -L C:/Users/Smiles/blackbirdextras/openssl-1.0.2l.tar"

Linking sqlite3:
gcc  -L C:/Users/Smiles/blackbirdextra/openssl-1.0.2l.tar/lib -L C:/Users/Smiles/blackbirdextras/jansson-2.10.tar -L C:/Users/Smiles/blackbirdextras/openssl-1.0.2l.tar -L . shell.o -o sqlite3 -lsqlite3
shell.o: file not recognized: File truncated
collect2.exe: error: ld returned 1 exit status
Makefile:41: recipe for target 'sqlite3' failed
mingw32-make: *** [sqlite3] Error 1

I have probably made some stupid errors. 
I have no idea whats wrong...

**Comment by mgandulfo** [comment]
I am also struggling to install on a Windows machine. It'd be great if someone could help with a more detailed explanation or a correction to what dmanman has done, so we can take that as a detailed explanation.

Thanks in advance!

**Comment by greatwolf** [comment]
1. You need to do a recursive clone of the repo so extern/sqlite3 is in blackbird's source tree. See the readme.
 2. You need to have the dependencies include headers and import libraries ready to link. That means either building those dependencies yourself or getting a precompiled version from somewhere.

**Comment by Gregor959** [comment]
I am also busy with that. .. for starters I would comment out sqllite, since blackbird does not really write to the database yet ( current version). So you can integrate with another database later. 
The rest like Jansson you have to compile from source or find windows alternatives. 
P.S. I hope you do know C++ . (if not learning linux and running it a VM seems much easier. )
Ultimately I hope to port it to Visual Studio..

**Comment by greatwolf** [comment]
Porting to VS isn't necessary, cmake already handles that. I've tested cmake + nmake with cl compiler from VS2017 and that does build successfully.

**Comment by mshish** [comment]
Another great alternative if you're on Windows 10 is to follow the Linux instructions and just use the Windows Subsystem for Linux (https://msdn.microsoft.com/en-us/commandline/wsl/install_guide).
