### ISSUE TITLE
Setup with docker: Error

### ISSUE THREAD

**Issue by gYumpu** [butor/blackbird#214]
Hi there,

when running the command "docker-compose up" I get this error message:

make: *** No rule to make target 'shell.o', needed by 'sqlite3'.  Stop.
ERROR: Service 'blackbird' failed to build: The command '/bin/sh -c make -B' returned a non-zero code: 2

Any idea what's wrong there? Thanks a lot for your feedback!

**Comment by butor** [comment]
Hi @gYumpu, please see issue #140

**Comment by gYumpu** [comment]
@butor Thanks a lot! Works great now!
