### ISSUE TITLE
Can't build project on ubuntu 16.04

### ISSUE THREAD

**Issue by ArnoutCreemers** [butor/blackbird#215]
I have followed all installation steps, installed all necessary tools, but when I now try to make my project, I get the following stacktrace:

[  4%] Building CXX precompiled header cotire/blackbird_CXX_prefix.hxx.gch
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMake Error at cmake/Modules/cotire.cmake:1848 (message):
  cotire: error 4 precompiling
  /root/Projects/blackbird/build/cotire/blackbird_CXX_prefix.hxx.
Call Stack (most recent call first):
  cmake/Modules/cotire.cmake:3512 (cotire_precompile_prefix_header)
  

CMakeFiles/blackbird.dir/build.make:63: recipe for target 'cotire/blackbird_CXX_prefix.hxx.gch' failed
make[2]: *** [cotire/blackbird_CXX_prefix.hxx.gch] Error 1
make[2]: *** Deleting file 'cotire/blackbird_CXX_prefix.hxx.gch'
CMakeFiles/Makefile2:131: recipe for target 'CMakeFiles/blackbird.dir/all' failed
make[1]: *** [CMakeFiles/blackbird.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Any suggestions on what a possible solution could be?

**Comment by greatwolf** [comment]
Which version of gcc is this?

**Comment by ArnoutCreemers** [comment]
The GCC version is 5.4.0 20160609

**Comment by greatwolf** [comment]
Try disabling cotire in cmake. Just comment out the line in `CMakeLists.txt`

    # cotire(${PROJECT_NAME})

**Comment by ArnoutCreemers** [comment]
The build now continues to fail in a later stage with a different error:

Compiling shell.o:
Compiling sqlite3.o:
Archiving libsqlite3.a:
ar: creating libsqlite3.a
a - sqlite3.o
Linking sqlite3:
Compiling src/curl_fun.o:
Compiling src/bitcoin.o:
Compiling src/check_entry_exit.o:
Compiling src/time_fun.o:
Compiling src/db_fun.o:
Compiling src/result.o:
Compiling src/parameters.o:
Compiling src/main.o:
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
Makefile:53: recipe for target 'src/main.o' failed
make: *** [src/main.o] Error 4

Is it a version conflict somewhere maybe?

**Comment by greatwolf** [comment]
You're getting an internal compiler error, it means the source you're feeding it is triggering some kind of bug in the compiler itself. I have no idea why that's happening. You could try building with a different version of gcc or see if you can reproduce the bug with a minimal source example.

I would start with main.cpp and see if that always triggers ICE. From there start stripping out unnecessary code until it compiles successfully. That'll narrow down where the problem is.

**Comment by ezillinger** [comment]
Looks like you're running out of RAM. Are you trying to build this on a VPS with 512MB and no swap? What does dmesg say?

**Comment by ArnoutCreemers** [comment]
I indeed had a VPS with only 512 MB of memory. I increased my VPS memory to 1GB and now the build succeeds.

Thanks for your help!
