### ISSUE TITLE
specify log file in config.json

### ISSUE THREAD

**Issue by emteeoh** [butor/blackbird#22]
Instead of writing to standard out, write to a file specified in the config file. Furthermore, catch SIGTERM and respond by closing and re-opening log file. That allows a sysadmin (or cron job) to rename the log file, and then signal the process, thus doing a log rotate.

**Comment by butor** [comment]
Thanks @emteeoh for the idea. If you know how to do it and you have some free time, please submit a _pull request_ with your enhancements.

**Comment by emteeoh** [comment]
My C++ is theoretical: I've never coded beyond a cout<<"hello, world!", but I'll give it a try.

**Comment by butor** [comment]
Now the output generated by Blackbird goes to a log file (e.g. _blackbird_log_20151122_223543.log_) instead of the standard output.
