### ISSUE TITLE
How to install on Mac OS???Problem solved.

### ISSUE THREAD

**Issue by jaywong003** [butor/blackbird#222]
I have problem installing the following libraries on Mac OS:
libssl-dev
libsqlite3-dev (available as a Blackbird submodule)
Does anybody else have the same problems?
I have googled several days but does not find the solution. 
Thanks for help!!!

**Comment by butor** [comment]
Hi @jaywong003 please take a look at:
- issue #62
- issue #92 
- issue #165 

You can try installing `openssl` using Homebrew, that should work:
```
brew install openssl
```
For more details please refer to issue #62.

**Comment by sbarale** [comment]
if you're having issues with the libraries not being found, you can pass extra parameters to the cmake command so it builds the Makefile properly, like this:

> cmake -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl/1.0.2j/ .

**Comment by greatwolf** [comment]
OP can also use:

    cmake -DCMAKE_PREFIX_PATH="<somepath>;<anotherpath>"

OP will have to be more specific about what he means by "have problem installing" though.

**Comment by jaywong003** [comment]
Thanks everydody, problem solved.!
first, using "ln -s ... " command to link the installed openssl path instead of the original Mac openssl path.
second, copy the "include" file of the installed openssl file into the corresponding file path (cannot remember the exact path, but you can reffer to the "include" file of sqlite3, etc)
