### ISSUE TITLE
Explanation please

### ISSUE THREAD

**Issue by ThatDeveloper** [butor/blackbird#223]
First of all, I love the project as I see it here. Great ReadMe, but could you please explain how to set up and make it running? I executed the commands on Ubuntu of your readme and then it says no blackbord config. I took the default one and it just said: Blackbird running on process pid xxxx. Nothing happend. It would be great if you could provide a small tutorial. (Maybe you could explain if the user can loose money that doesn't belong to him => e.g. I put 100 on 2 Exchanges and I get a bill of 1000 because the bot lost)

Best Regards

**Comment by butor** [comment]
Thanks @ThatDeveloper 
Take a look into the `output` folder. This is where the log file is.
You can't loose more money than what you put on your accounts.

**Comment by mgandulfo** [comment]
I installed same way and have the same problem. But in my case no log file appears in Output or anywhere else with the name defined by blackbird.

This is the code that I ran (take into account I had already installed the same way and had the same problem so I decided to install one again, hence the fact that the libraries where not installed again):

mariano@mariano-VirtualBox:~$ sudo apt-get install libssl-dev libjansson-dev libcurl4-openssl-dev [sudo] password for mariano: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
g++ is already the newest version (4:5.3.1-1ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
libjansson-dev is already the newest version (2.7-3).
libsqlite3-dev is already the newest version (3.11.0-1ubuntu1).
make is already the newest version (4.1-6).
sendemail is already the newest version (1.56-5).
libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2.2).
libssl-dev is already the newest version (1.0.2g-1ubuntu4.8).
0 to upgrade, 0 to newly install, 0 to remove and 101 not to upgrade.
mariano@mariano-VirtualBox:~$ mkdir blackbird
mariano@mariano-VirtualBox:~$ cd blackbird
mariano@mariano-VirtualBox:~/blackbird$ git clone --recursive  git://github.com/butor/blackbird.git .
Cloning into '.'...
remote: Counting objects: 1783, done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 1783 (delta 21), reused 25 (delta 11), pack-reused 1742
Receiving objects: 100% (1783/1783), 2.11 MiB | 432.00 KiB/s, done.
Resolving deltas: 100% (1264/1264), done.
Checking connectivity... done.
Submodule 'extern/sqlite3' (https://github.com/greatwolf/sqlite3) registered for path 'extern/sqlite3'
Cloning into 'extern/sqlite3'...
remote: Counting objects: 9, done.
remote: Total 9 (delta 0), reused 0 (delta 0), pack-reused 9
Unpacking objects: 100% (9/9), done.
Checking connectivity... done.
Submodule path 'extern/sqlite3': checked out '41e73a066f09b3f4af499bebfd4f0256d4b1362d'
mariano@mariano-VirtualBox:~/blackbird$ mkdir build && cd build
mariano@mariano-VirtualBox:~/blackbird/build$ cmake -DCMAKE_BUILD_TYPE=Release  ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- cotire 1.7.9 loaded.
-- Found CURL: /usr/lib/x86_64-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found Jansson: /usr/lib/x86_64-linux-gnu/libjansson.so  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Found SQLITE3: /usr/lib/x86_64-linux-gnu/libsqlite3.so  
-- CXX target blackbird cotired.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mariano/blackbird/build
mariano@mariano-VirtualBox:~/blackbird/build$ make
[  4%] Generating CXX unity source cotire/blackbird_CXX_unity.cxx
[  8%] Generating CXX prefix source cotire/blackbird_CXX_prefix.cxx
[ 12%] Generating CXX prefix header cotire/blackbird_CXX_prefix.hxx
[ 16%] Building CXX precompiled header cotire/blackbird_CXX_prefix.hxx.gch
Scanning dependencies of target blackbird
[ 20%] Building CXX object CMakeFiles/blackbird.dir/src/check_entry_exit.cpp.o
[ 24%] Building CXX object CMakeFiles/blackbird.dir/src/main.cpp.o
[ 28%] Building CXX object CMakeFiles/blackbird.dir/src/result.cpp.o
[ 32%] Building CXX object CMakeFiles/blackbird.dir/src/parameters.cpp.o
[ 36%] Building CXX object CMakeFiles/blackbird.dir/src/curl_fun.cpp.o
[ 40%] Building CXX object CMakeFiles/blackbird.dir/src/db_fun.cpp.o
[ 44%] Building CXX object CMakeFiles/blackbird.dir/src/time_fun.cpp.o
[ 48%] Building CXX object CMakeFiles/blackbird.dir/src/bitcoin.cpp.o
[ 52%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/itbit.cpp.o
[ 56%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/btce.cpp.o
[ 60%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/bitstamp.cpp.o
[ 64%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/bitfinex.cpp.o
[ 68%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/gdax.cpp.o
[ 72%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/gemini.cpp.o
[ 76%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/okcoin.cpp.o
[ 80%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/poloniex.cpp.o
[ 84%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/kraken.cpp.o
[ 88%] Building CXX object CMakeFiles/blackbird.dir/src/utils/restapi.cpp.o
[ 92%] Building CXX object CMakeFiles/blackbird.dir/src/utils/base64.cpp.o
[ 96%] Building CXX object CMakeFiles/blackbird.dir/src/utils/send_email.cpp.o
[100%] Linking CXX executable blackbird
[100%] Built target blackbird
mariano@mariano-VirtualBox:~/blackbird/build$ ./blackbird
Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

Log file generated: output/blackbird_log_20170625_173318.log
Blackbird is running... (pid 3397)
************************************************************
This is my blackbird.conf file:

# Blackbird Bitcoin Arbitrage
# Configuration file


# Program parameters
DemoMode=true
Leg1=BTC
Leg2=USD
UseFullExposure=false
TestedExposure=25.00
MaxExposure=25000.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true
CACert=curl-ca-bundle.crt

# Strategy parameters
Interval=3.0
SpreadEntry=0.0080
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600

# Email settings
SendEmail=false
SenderAddress=
SenderUsername=
SenderPassword=
SmtpServerAddress=
ReceiverAddress=

# Database settings
DBFile=blackbird.db

Plus my API keys for the exchanges...
************************************************************
I don't know why it's not working. I'd appreciate if someone can point me in the right direction. 

Thanks in advance!

**Comment by greatwolf** [comment]
Try moving blackbird executable from blackbird/build to just blackbird/.

**Comment by mgandulfo** [comment]
Thanks @greatwolf ! It was as easy as that. Now it's working.
