### ISSUE TITLE
Help with Error "blackbird.conf cannot be open

### ISSUE THREAD

**Issue by eglyants** [butor/blackbird#226]
Can anyone help with this error message when trying to start the program?  ./blackbird

"Error: blackbird.conf cannot be open."
http://imgur.com/a/VW1Bc

I followed the instructions in the readme, and the blackbird.conf file is default right now.  My goal is to test the bot without inputting API credentials yet.

**Comment by ThatDeveloper** [comment]
Had the same problem. Copy blackbird out of build folder. (mv blackbird ../blackbird)
Then you can start it.
