### ISSUE TITLE
Email config question #question

### ISSUE THREAD

**Issue by emteeoh** [butor/blackbird#23]
When configuring email from blackbird... I have SMTP setup on the localhost, so blackbird does not need a login/password to send an email. Do I configure that just by leaving password blank?

**Comment by butor** [comment]
Hi @emteeoh,

I've never tried from localhost but yes I think it will work.

If `-s SERVER[:PORT]` is not defined then sendEmail will use `localhost:25`.
Also, STMP username and password are optional so blank should be fine.

Here are the full specifications of sendEmail (i.e. the library used by Blackbird):
http://caspian.dotconf.net/menu/Software/SendEmail

Please let us know how it goes.
