### ISSUE TITLE
How to install in Ubuntu 16 at AWS Amazon?

### ISSUE THREAD

**Issue by nam1248** [butor/blackbird#232]
I use Amazon Ubuntu Server 16.04 LTS (HVM), SSD Volume Type
I installed following the instructions. 
Q1. Which folder should I start to install the program? I installed on the root folder and my home folder. Both got errors ("blackbird.conf cannot be open"). I did "chmod 777 blackbird.conf" to allow access to the conf file but still not working. 
Errors are shown as below. 

"Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

ERROR: blackbird.conf cannot be open.
"

**Comment by butor** [comment]
Hi @nam1248, please see issue #233
