### ISSUE TITLE
'ERROR: blackbird.conf cannot be open.'

### ISSUE THREAD

**Issue by amritsaxena** [butor/blackbird#233]
After building blackbird, when I try to run the program, I receive the following error: 

amritsaxena$ ./blackbird 
Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

ERROR: blackbird.conf cannot be open.

How do I go about addressing this?  Thanks in advance!

**Comment by greatwolf** [comment]
You need to copy the executable from ./blackbird/build to ./blackbird. I just updated cmake to use install that does this automatically.
