### ISSUE TITLE
Running blackbird

### ISSUE THREAD

**Issue by oztoon** [butor/blackbird#235]
Hi there....i downloaded blackbird and am not having any success running it.  When I enter the ./blackbird command, its starts up (generates a log file and gives me the title page and the disclaimer and then states "blackbird is running... (pid 25971)" but that's where it stops. Nothing happens after it says its running. Any suggestions? Thanks in advance for your help. Cheers

**Comment by butor** [comment]
Hi @oztoon Please check the _ouput_ folder. You should find a log file in there, where all the events are recorded.

**Comment by oztoon** [comment]
Thanks for that. I will do that and see what it is telling me. Appreciate the help. Cheers

**Comment by oztoon** [comment]
dont know how to open the output folder (yea, true....lol). any suggestions would be appreciated. thanks again. cheers

**Comment by oztoon** [comment]
and thank you for adding the label (couldn't find anywhere to tag my initial request)

**Comment by butor** [comment]
There should be an _output_ folder in the _blackbird_ directory. You don't see any?

**Comment by oztoon** [comment]
I do see the folder. I just dont know how To open it

**Comment by butor** [comment]
What do you mean?

**Comment by oztoon** [comment]
I mean the log is there, but I dont know how to Open it

**Comment by oztoon** [comment]
And by the way, I'm Kevin Corcoran. The one talking to u about doing the
bitcoin arb. I use this email for most of my bitcoin stuff.

I just can't figure out to get the software running. Any help would be
Appreciated.

Do u think what I mentioned (on kevindcorcoran @gmail.com) about shorting
on one exchange and covering with the "buy" on the other exchange, make
better sense than waiting for the "round trip"?

Let me know What u think. Thanks for your help. Cheers

**Comment by butor** [comment]
The log is just a text file. Do something like:
```
more blackbird_log_xxxxxxxx_xxxxxx.log
```

**Comment by oztoon** [comment]
Ahh gotcha. Will try that.

Would u be interested in collaborating on something with an investor of
mine? He has large amounts if money to invest and is very tech savey (he
was into HFT for years).

He is interested in funding something in the bitcoin area. Anything u would
like to talk about further?

Let me know. Thanks (and by the way, what part if the country are you in?)

**Comment by butor** [comment]
Your strategy sounds correct in principle, but I will need a step-by-step description of the workflow along with an example to make sure I thoroughly understand it.

Regarding your investor, sure please introduce us using my email address. Someone with HFT experience will definitely bring values in that space.

**Comment by oztoon** [comment]
Hi julien. Can I get your phone number? I would like to introduce myself
and give you an ides of what we are trying to accomplish.  Thanks

**Comment by oztoon** [comment]
Good idea....I had no idea when i was responding to your emails that it was
posting on the hub. (i'm very tech unsavy!! lol)

**Comment by oztoon** [comment]
Hey Julien!!! How are you doing?

Just thought I'd drop you a line to say hello.

Any exciting new developments in your life? Still working on the dating app?

I'm working for a small brokerage firm doing currency arbitrage.
Couldn't ever figure out a way to make money in it in the crypto world
(which I find very odd!)

Looking forward to hearing the latest from you.

Cheers

Kevin
