### ISSUE TITLE
Demo Mode Question

### ISSUE THREAD

**Issue by hongkongkiwi** [butor/blackbird#236]
Hi,

Thanks for the hard work.

Quick question, in demo mode, will it show the results of trades in the results section? e.g. paper trading.

I would like to leave it running over a month period and see how much I potentially could have gained.

**Comment by greatwolf** [comment]
Demo mode currently doesn't do any actual "paper trading"; no fake trades are done or recorded on opportunity signals. There is some discussion on this see issue #99.
