### ISSUE TITLE
Missing big spread with high volume

### ISSUE THREAD

**Issue by NateBrune** [butor/blackbird#24]
> Issue: http://pastebin.com/uKm4LrHk

My proposed solution is that the config file include an offset setting. I have a few bitcoins in the exchanges (About as much as you have in your exchanges) and it seemed to miss this big spread oppertunity. Tell me what you think.

**Comment by butor** [comment]
Hi @NateBrune,

Thank you for your feedback. Let's look at your missed opportunity (the miss is on Bitfinex):

Bitfinex: __324.63__ / 324.90
WARNING: Opportunity found but not enough liquidity. Trade canceled.
Target short price: 324.63, Real short price: __312.01__

The reason that you didn't get the trade is that the bid at $324.63 on Bitfinex covered an insufficient  volume of Bitcoin. To be sure to be immediately executed, Blackbird calculated a limit price at $312.01 that will correspond to an immediate execution of the requested volume. However, $312.01 was too different from $324.63 and Blackbird canceled the trade.

The maximum difference between the target limit price and the calculated limit price is defined by the parameter `PriceDeltaLimit` in the configuration file. An nice improvement would be to define that limit dynamically based on the existing spreads (e.g. high spreads could tolerate a higher PriceDeltaLimit).
