### ISSUE TITLE
Poloniex quote in BTC not USD

### ISSUE THREAD

**Issue by splash123** [butor/blackbird#240]
When I start Blackbird the Poloniex quote is not expressed in USD, but in other coin?
Bitfinex: 	2.288,5000 / 2.288,7000
   OKCoin: 	2.371,0100 / 2.382,8600
   Bitstamp: 	2.303,9900 / 2.304,0000
   Gemini: 	2.295,8300 / 2.295,8400
   Kraken: 	2.290,8100 / 2.291,1050
   ItBit: 	2.289,5000 / 2.297,7300
   BTC-e: 	2.226,1070 / 2.226,1080
   **Poloniex: 	0,0840 / 0,0840**
   GDAX: 	2.298,7800 / 2.298,9300
   QuadrigaCX: 	2.270,0100 / 2.280,0000
This messes up the spread calculation.

**Comment by DMLoy** [comment]
Same, but only in Release mode. In Demo it seems fine.

**Comment by greatwolf** [comment]
It's because polo got changed from btc/usdt to btc/eth in [this commit](https://github.com/butor/blackbird/commit/8131ece389351568a68cc6baca2aca2c3ffdb74a#diff-da2735653448bd9bd85dca4154d22d79R42).

Maybe just disable polo in the config file for the time being.

**Comment by DMLoy** [comment]
@greatwolf if this is breaking the normal pair comparison shouldn't this commit be taken of master?

**Comment by greatwolf** [comment]
I agree this should probably not be in master. Implementing arbitrage for other pairs should be done in another branch until it's ready to be merge/rebased later. It's @butor call though.

**Comment by butor** [comment]
@greatwolf I agree with you. It should be a separated branch.

**Comment by butor** [comment]
@greatwolf I will remove the _ETH/BTC_ stuff from the codebase when I have time, but I'll keep the `Leg1` and `Leg2` nomenclature. Implementing other pairs will be done in another branch as you've suggested.
