### ISSUE TITLE
How to disable BTC-e in demo-mode?

### ISSUE THREAD

**Issue by PatrickHuetter** [butor/blackbird#252]
I would like to disable BTC-e in demo mode to make some tests. As i can see, the demo mode ignores the enabled flag within the configuration file and that's the cause why the software isn't running anymore. BTC-e's CDN (Cloudflare) is responding with some error html page which can't get parsed by blackbird.

BTC-e is offline now regarding to the following news:
https://www.reuters.com/article/us-greece-russia-arrest-bitcoin-idUSKBN1AB27W

Best regards

**Comment by greatwolf** [comment]
I can't reproduce the issue you're talking about. When `BTCeEnable=false` then blackbird never tries to query the price from btce.

**Comment by PatrickHuetter** [comment]
You're right, the problem was that the config file got cached from docker compose. Had to rebuild the whole container and it worked. Thank you!
