### ISSUE TITLE
Docker toolbox on windows error ' is unknown. Valid pairs for now are BTC/USD and ETH/BTC

### ISSUE THREAD

**Issue by newb1ez** [butor/blackbird#256]
i'm already docker-compose build and when i try to docker-compose up this error shown : 

> $ docker-compose up
Starting blackbird_blackbird_1 ...
Starting blackbird_blackbird_1 ... done
Attaching to blackbird_blackbird_1
blackbird_1  | Blackbird Bitcoin Arbitrage
blackbird_1  | DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK
blackbird_1  |
' is unknown. Valid pairs for now are BTC/USD and ETH/BTC
blackbird_1  |
blackbird_blackbird_1 exited with code 1

i'm using docker toolbox.
is that mean i must re-download and build the lib for this or what  ???
please help me :(

**Comment by pikespeak** [comment]
What are your 

Leg1 and Leg2 in blackbird.conf?

**Comment by newb1ez** [comment]
same as first download.
so it's Leg1 = BTC, Leg2 = USD

**Comment by pikespeak** [comment]
Try to build without caching. 

docker build --no-cache -t blackbird .

**Comment by newb1ez** [comment]
already try it docker build --no-cache -t blackbird .
still same :(

**Comment by pikespeak** [comment]
Can you start blackbird without docker-compose?

**Comment by newb1ez** [comment]
with ./blackbird right ? 
can't bash: ./blackbird: No such file or directory

**Comment by pikespeak** [comment]
On windows, I am not sure how to run

**Comment by newb1ez** [comment]
ahahaha... i don't know too... hope they release just the output for easly configuration and installation :(

**Comment by realcotter** [comment]
I am getting this same error

**Comment by butor** [comment]
ETH/BTC has been removed from the main branch
