### ISSUE TITLE
Question: Gemini API error message 

### ISSUE THREAD

**Issue by inkymaze** [butor/blackbird#306]
<Gemini> Error with JSON: {"result": "error", "reason": "InvalidSignature", "message": "InvalidSignature"}. Retrying...

Anyone have any guesses as to why? I have tried new keys numerous times and have the same error. Note I also just got blackbird up and running so I'm not sure if this is the only issue. Thanks

**Comment by greatwolf** [comment]
I don't have a working gemini account to test it myself. I think @Butor implemented the signing code for gemini. He may be able to help.

**Comment by butor** [comment]
Yes I haven't had any signature issue with Gemini so far.
