### ISSUE TITLE
Help~How to remove or add more exchanges?

### ISSUE THREAD

**Issue by kokomoji** [butor/blackbird#31]
Hi,
  @butor 
Your project ideas really inspired me a lot, This idea can also be used for other commodities.thank you!
So,If I don't need an exchange, can i remove it by edit the source code? can i edit blackbird.conf to complete this.
And how to  add more exchange?
Thanks for your reply!

**Comment by butor** [comment]
Hi @kokomoji,

Thank you for your interest. Yes the code can be adapted to other instruments.

If you leave Blackbird in demo mode (`DemoMode=true`) then all the Bitcoin exchanges will be displayed, even if you don't have any accounts on them.

If you want to actually trade (`DemoMode=false`) you can simply put into _blackbird.conf_ the credentials of the exchanges where you have an account. The remaining exchanges will be ignored by Blackbird. As explained in the README, you need at least two exchanges and one of them must allow short selling (e.g. Bitfinex).

If you want to add a new exchange you need to code the API functions so Blackbird can connect to it and send orders. See [issue #4](https://github.com/butor/blackbird/issues/4) for more details.

**Comment by kokomoji** [comment]
Hi,
@butor 
OK, Thanks!

**Comment by jw4wellness** [comment]
If you opened another exchange account and now want to add that. Let's say you have 2 accounts and blackbird is running. While it is busy you open a 3rd account and update the conf file with the API details. Do you have to restart blackbird so that the changes can come into effect? Is a restart required to trade on 3 exchanges now?

**Comment by butor** [comment]
Yes, every time you change something in the config file you need to restart Blackbird.
