### ISSUE TITLE
Kraken send a "buy" limit order

### ISSUE THREAD

**Issue by juniperbeam** [butor/blackbird#312]
Bitfinex:    7,401.00 / 7,408.90
   Kraken:      7,298.80 / 7,298.80
   —------------------------—
   Kraken/Bitfinex:      1.40% [target  0.80%, min -0.31%, max  1.59%]   trailing  1.51%  1/1
<Bitfinex> Looking for a limit price to fill 0.001351 BTC...
<Bitfinex> order book: 1.594400@$7,402.40

[ ENTRY FOUND ]
   Date & Time:       11/16/2017 10:56:15
   Exchange Long:     Kraken (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        7,296.50 (target)
   Price Short:       7,402.40 (target)
   Spread:            1.40%
   Cash used:         10.00 on each exchange
   Exit Target:       0.00%

<Kraken> Trying to send a "buy" limit order: 0.001370 @ $7,296.50...
{"error": ["EGeneral:Invalid arguments:volume"]}

**Comment by yuanfeng-ma** [comment]
I run into same problems, what happened? What is the reason for this?

**Comment by greatwolf** [comment]
It looks like kraken is placing a minimum volume size of 0.002 on orders. Volume < 0.002 returns that json error.
