### ISSUE TITLE
BTC-E issue

### ISSUE THREAD

**Issue by j4r3kb** [butor/blackbird#32]
Hello,
I've setup API keys at btc-e, have a USD balance there but blackbird is showing 0 balance and there is 'info only' note in log file.
I did not found any other USD balance beside their Meta trader account at btc-e.
What am I doing wrong?

**Comment by j4r3kb** [comment]
I just saw in commits that is not fully implemented, sorry.

**Comment by butor** [comment]
No problem @j4r3kb. I hope BTC-e will be implemented soon. I close the issue.
