### ISSUE TITLE
Blackbird not making trades

### ISSUE THREAD

**Issue by j4r3kb** [butor/blackbird#33]
My config:
/# Program parameters
DemoMode=false
UseFullCash=false
UntouchedCash=0.01
CashForTesting=40.00
MaxExposure=100.00
MaxLength=5184000
DebugMaxIteration=3200000
Verbose=true

/# Strategy parameters
GapSec=3.0
SpreadEntry=0.0080
SpreadTarget=0.0030
PriceDeltaLimit=0.10
AggressiveVolume=true
TrailingSpreadLim=0.0010
OrderBookFactor=1.5

Few log entries:
Bitfinex/Kraken:      0.10% [target  0.80%, min -0.70%, max  0.83%]
OKCoin/Bitfinex:      0.35% [target  0.80%, min -0.51%, max  0.56%]
OKCoin/Kraken:        0.46% [target  0.80%, min -0.80%, max  1.12%]
Kraken/Bitfinex:     -0.87% [target  0.80%, min -1.15%, max  0.34%]

...

Bitfinex/Kraken:     -0.06% [target  0.80%, min -1.73%, max  0.22%]
OKCoin/Bitfinex:      0.05% [target  0.80%, min -0.47%, max  0.59%]
OKCoin/Kraken:       -0.01% [target  0.80%, min -1.66%, max  0.23%]
Kraken/Bitfinex:     -0.16% [target  0.80%, min -0.66%, max  1.34%]

Why it did not make a single trade?
I have $50 on each exchange.

**Comment by butor** [comment]
Hi @j4r3kb,

Did you change `KrakenCanShort` to `true`? The API to short sell on Kraken doesn't exist yet, so it's impossible to automatically short sell on Kraken for the moment.

I will remove the `canShort` parameters from the config file so there won't be any more confusion.

Yes, according to this line:
```
Kraken/Bitfinex: -0.16% [target 0.80%, min -0.66%, max 1.34%]
```
you should have gotten a trade, if there were enough volume. Can you please send me your log file?
Note that the Kraken connection has never been fully tested. It's explicit in the Changelog but I'll make it more obvious in the README file. Thanks.

**Comment by j4r3kb** [comment]
No, I did not change any option *CanShort to true (beside leaving default Bitfenix true).
I've attached all my logs with csv.
[logs.tar.gz](https://github.com/butor/blackbird/files/83785/logs.tar.gz)

**Comment by butor** [comment]
Thank you. I'll take a look at it.

**Comment by butor** [comment]
I just fixed the issue with `KrakenCanShort`

**Comment by j4r3kb** [comment]
I just need to update and compile or change any settings too?

**Comment by butor** [comment]
Just update and compile. You won't see Kraken on the _short_ side anymore.

**Comment by butor** [comment]
Hi @j4r3kb,

You didn't get any trade at that time because the spread between Kraken and Bitfinex went directly from 0.55% to 1.34% and back to 0.55% within 21 seconds and without triggering the trailing stop.

```
[ 01/07/2016 09:24:15 ]
   Kraken/Bitfinex:	 0.55% [target  0.80%, min  0.42%, max  0.87%]

[ 01/07/2016 09:24:18 ]
   Kraken/Bitfinex:	 1.34% [target  0.80%, min  0.42%, max  1.34%]

[ 01/07/2016 09:24:21 ]
   Kraken/Bitfinex:	 1.34% [target  0.80%, min  0.42%, max  1.34%] trailing 1.24%  0/2

[ 01/07/2016 09:24:24 ]
   Kraken/Bitfinex:	 1.34% [target  0.80%, min  0.42%, max  1.34%] trailing 1.24%  0/2

[ 01/07/2016 09:24:39 ]
   Kraken/Bitfinex:	 0.55% [target  0.80%, min  0.42%, max  1.34%] trailing 1.24%  0/2

[ 01/07/2016 09:24:42 ]
   Kraken/Bitfinex:	 0.55% [target  0.80%, min  0.42%, max  1.34%]
```

It usually happens when a small limit order arrives in front of the order book. It doesn't really represent a true discrepancy between the exchanges as the volume of that order is usually too low.

If you want to trade this kind of situation anyway it's totally possible: just set `TrailingSpreadLim=0.0000`.
