### ISSUE TITLE
OKCoin sends order at 0$

### ISSUE THREAD

**Issue by beckel** [butor/blackbird#34]
Hi,

There is a problem using OKCoin:

\<OKCoin\> Looking for a limit price to fill 1.50 BTC...
\<OKCoin\> order book: 0.67@$439.94
\<OKCoin\> order book: 0.04@$439.95
\<OKCoin\> order book: 0.44@$439.97
\<OKCoin\> order book: 0.01@$439.99
\<OKCoin\> order book: 3.56@$0.00
\<OKCoin\> Trying to send a "buy" limit order: 1.50@$0.00...
\<OKCoin\> Done (order ID: 0)

As a consequence, the order is not fulfilled.

Christian

**Comment by butor** [comment]
Hi @beckel,

Yes for some reasons there is an inconsistency in the OKCoin order book:

```
<OKCoin> order book: 3.56@$0.00
```

I guess it can occasionally happen with exchanges, and Blackbird should manage that. I label it as a bug and I will try to fix it. Thanks.

**Comment by butor** [comment]
Fixed.
