### ISSUE TITLE
BTC-e connection implementation

### ISSUE THREAD

**Issue by butor** [butor/blackbird#35]
Many people requested the implementation of the connection to <a href="https://btc-e.com/" target="_blank">BTC-e</a> as it's a very popular Bitcoin exchange. The API is described on <a href="https://support.btc-e.com/index.php?/Knowledgebase/Article/View/212/0/api-trade" target="_blank">this page</a>.

**Note:**

At the beginning of this project I didn't implement BTC-e because the bid/ask prices on BTC-e were almost always _below_ the other exchanges. Therefore, BTC-e wouldn't have been a good candidate for arbitrage since the bid/ask prices must "swing" between the exchanges (otherwise the trades would never close).

This is not the case anymore (thanks @kokomoji) so it does make sense to get BTC-e implemented.

**Comment by kokomoji** [comment]
Hello,
@butor 
 There are some opportunities in the BTCE ,But not this week... : )
![btce](https://cloud.githubusercontent.com/assets/16488965/12226908/79c15a26-b85e-11e5-89df-1c6f899734e0.PNG)

**Comment by nikhiljha** [comment]
:+1: I'm mostly a C dev but I'll try to add this soon :)

**Comment by asidiali** [comment]
I'm going to begin tonight attempting to implement BTC-E capability. I'm not a C dev, so hoping someone would be interested in working together to review/revise/supervise any progress that I make.

Also, if anyone has made progress on this so far and has a starting point that I can collaborate on, that would be awesome too.

Thank you

**Comment by IonoclastBrigham** [comment]
These pages describe the REST API:
* https://support.btc-e1.com/index.php?/Knowledgebase/Article/View/212/4/api-trade
* https://btc-e.com/api/documentation

They seem to have overlapping information; the first one appears to be more comprehensive, while the second may be easier to read.

**Comment by rasheedmoore** [comment]
getting BTC-e:	n/a (API not implemented) similar to poloniex

**Comment by Newar417** [comment]
It is listed as "potential". So far nobody has added it to this Github.
