### ISSUE TITLE
Blackbird stopping without reason and error

### ISSUE THREAD

**Issue by j4r3kb** [butor/blackbird#36]
After several hours program just stops without error. I have it running in screen session on vps server, console looks like this:
/
jarek@xxx:~/blackbird$ ./blackbird
Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

Log file generated: blackbird_log_20160111_161002.log
Blackbird is running... (pid 16177)

jarek@xxx:~/blackbird$
/

end of log file:
[ 01/11/2016 22:39:39 ]
   Bitfinex:    448,97 / 448,99
   OKCoin:      447,00 / 447,10
   Kraken:      450,01 / 451,49

   OKCoin/Bitfinex:      0.42% [target  0.80%, min -0.03%, max  0.71%]
   Kraken/Bitfinex:     -0.56% [target  0.80%, min -0.87%, max  0.01%]

[ 01/11/2016 22:39:42 ]

I had this problem 4 times already. On my home virtual machine it does the same.

**Comment by j4r3kb** [comment]
This time it stopped when in market

/
[ 01/13/2016 01:10:42 IN MARKET: Long OKCoin / Short Bitfinex ]
   Bitfinex:    433,69 / 433,71
   OKCoin:      431,95 / 432,40
   Kraken:      440,00 / 440,01
   ----------------------------
   OKCoin/Bitfinex:      0.41% [target -0.18%, min -0.41%, max  1.16%]

[ 01/13/2016 01:10:45 IN MARKET: Long OKCoin / Short Bitfinex ]
/

Is there a way to continue from here? If I start blackbird again it will not close this trade.
Maybe it is a good idea to make a resume mode?

**Comment by butor** [comment]
Hi @j4r3kb,

There is no resume mode for the moment. I would wait for the spread between OKCoin and Bitfinex to close and then manually send orders from both OKCoin and Bitfinex websites to close your trades. A resume mode would be a nice feature for a future version.

If I understand correctly, your `blackbird` process crashes without warning. This is what you can do to trace the error:

1. First, type the command `ulimit -c unlimited`. This will produce a core file next time Blackbird crashes
2. Run `./blackbird`
3. When Blackbird crashes you should get a core file in the current directory
4. Type `gdb ./blackbird core` to start [GNU Debugger](https://www.gnu.org/software/gdb/)
5. Type `backtrace` in the debugger. You should be able to see when the crash occurred and hopefully why.
