### ISSUE TITLE
Blackbird doesn't work on CentOS

### ISSUE THREAD

**Issue by slwski** [butor/blackbird#37]
I have it running in on vps server. I used Cent OS 6.5 32bit on My linux server
console looks like this:

Blackbird started on 01/15/2016 23:56:52

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.30%

[ Current balances ]
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:

How Can I troubleshoot this problem ?

**Comment by butor** [comment]
Hi @slwski,

I don't think it's related to the OS. It looks like the JSON object retrieved by one of the exchanges to get the balances is incorrect for some reasons. A couple of questions for you:

1. Is the problem consistent? If you restart Blackbird do you always get the exact same error?
2. For what exchanges did you put credentials?
3. Did you try with a recent version of Blackbird? If not, try with the current version.
4. What is the _Jansson_ version that you use? It should be 2.7.

The answers will help troubleshooting. Thanks.

Also, if you know what JSON object (`root`) causes the issue, you can add the line:

```
std::cout << json_dumps(root, 0) << std::endl;
```

right after the `root` object is created. The full content of the object will be displayed.

**Comment by slwski** [comment]
1. Yes. I restart Blackbird several times. but got the exact same error. 
2. I put bitfinex, btc-e,okcoin, bitstamp, okcoin. console log look like this
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 01/16/2016 10:18:19

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.30%

[ Current balances ]
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...
<Bitfinex> Error with JSON:
'[' or '{' expected near '<'. Retrying...

3. I tried with a most recent version of Blackbird.
4. I installed the Jansson version 2.7

**Comment by kokomoji** [comment]
Hi,
@butor 
My problem is diffrent from slwski.I do not know anyone encountered the same problem.
After i change Demo to "false" and add api in blackbird.conf , it shows:
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 01/16/2016 12:12:10

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.20%

[ Current balances ]
<Bitfinex> Error with JSON: {"message": "Nonce is too small."}. Retrying...
<Bitfinex> Error with JSON: {"message": "Nonce is too small."}. Retrying...

**Comment by butor** [comment]
@slwski Apparently the GitHub editor interpreted \<Bitfinex\> as a markdown tag and removed it from your text. I saw you also noticed and put some spaces around :wink:

It makes more sense now. So we know the issue is with Bitfinex. Please use the file 
[bitfinex.txt](https://github.com/butor/blackbird/files/92776/bitfinex.txt) (rename it to _.cpp_), recompile, rerun Blackbird and send me the console output (not the log file but the console output). You may want to hide any sensitive information you might find (like your USD balances) before showing it. Thanks.

@kokomoji I think I know how to fix your problem as I had it in the past. But please open a new issue and I will answer it. Thanks.

**Comment by kokomoji** [comment]
Hi,
@butor  Please see new issue.Thanks!

**Comment by slwski** [comment]
Hi butor!
I changed my file and recompiled. console output like the.

--- Debug issue #37 ---
<html style="height:100%"><head><META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW"><meta name="format-detection" content="telephone=no"><meta name="viewport" content="initial-scale=1.0"><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></head><body style="margin:0px;height:100%"><iframe src="/_Incapsula_Resource?CWUDNSAI=17&xinfo=10-43314252-0 0NNN RT(1453032700619 307) q(-1 -1 -1 -1) r(0 -1) b1&incident_id=0-395164255704318762&edet=3&cinfo=ffffffff" frameborder=0 width="100%" height="100%" marginheight="0px" marginwidth="0px">Request unsuccessful. Incapsula incident ID: 0-395164255704318762</iframe></body></html>
-----------------------

**Comment by butor** [comment]
Thank you @slwski. The error seems to come from Bitfinex and not Blackbird:
```
Request unsuccessful. Incapsula incident ID: 0-395164255704318762
```

I just googled and I found two discussions about it, one on <a href="https://bitcointalk.org/index.php?topic=229438.msg11914341#msg11914341" target="_blank">Bitfinex</a> and one on <a href="https://www.reddit.com/r/BitcoinMarkets/comments/28jdlj/bitfinex_api_inaccessible_due_to_captcha/" target="_blank">Reddit</a>.

Could you please contact the Bitfinex support (support@bitfinex.com) and submit the problem? I guess they will need your _ClientId_. Please let us know what they say. Thanks!

**Comment by slwski** [comment]
Hi @butor 

I contact the Bitfinex Support and They said fixed the problem, but I still couldn`t troobleshoot this problem.

**Comment by butor** [comment]
Hi @slwski, do you mean you still have the same issue? What did the Bitfinex support say exactly? Do you know what they fixed? Thanks

**Comment by butor** [comment]
@slwski any news on that issue? Thanks
