### ISSUE TITLE
Verbose not showing spread

### ISSUE THREAD

**Issue by DanDoYouMind** [butor/blackbird#372]
Hi, 

First thanks to whoever put this together.

My log only shows:

[ Cash exposure ]
   No cash - Demo mode

[ 01/05/2018 21:48:24 ]
   OKCoin: 	17,887.50 / 18,021.92
   QuadrigaCX: 	16,200.23 / 16,569.99
   ----------------------------

[ 01/05/2018 21:48:27 ]
   OKCoin: 	17,888.51 / 18,021.90
   QuadrigaCX: 	16,200.24 / 16,569.99
   ----------------------------

[ 01/05/2018 21:48:30 ]
   OKCoin: 	17,888.51 / 18,021.88
   QuadrigaCX: 	16,200.24 / 16,569.99
   ----------------------------

[ 01/05/2018 21:48:33 ]
   OKCoin: 	17,889.52 / 18,024.98
   QuadrigaCX: 	16,200.25 / 16,569.99
   ----------------------------

doesn't show the calculated spread. Am I missing something? I've kept verbose as true.

**Comment by itskeKs** [comment]
its running in demo mode

**Comment by DanDoYouMind** [comment]
cheers.
