### ISSUE TITLE
Add new Bitcoin exchanges

### ISSUE THREAD

**Issue by butor** [butor/blackbird#4]
#### How to add a new exchange connection

Adding new Bitcoin exchange connections (BTC-e, LakeBTC, etc) will increase the number of arbitrage opportunities. This is what we have so far:
- Fully implemented and tested: _Bitfinex_, _OKCoin_, _Bitstamp_ and _Gemini_
- Implemented as a beta version and hasn't been tested: _Kraken_ and _796_
- Hasn't been implemented yet: _BTC-e_

Here is the procedure to add a new exchange, let's say an exchange called _BTCExchange_:

1) Add the exchange parameters to the config file, _blackbird.conf_:

```
# BTCExchange
BTCExchangeApiKey=
BTCExchangeSecretKey=
BTCExchangeFees=0.0020
```

2) Edit _parameter.h_ and _parameter.cpp_ to add the new exchange variables:

``` C++
  btcExchangeApi = getParameter("BTCExchangeApiKey", configFile);
  btcExchangeSecret = getParameter("BTCExchangeSecretKey", configFile);
  btcExchangeFees = getDouble(getParameter("BTCExchangeFees", configFile));
```

3) Edit _main.cpp_ to add the new exchange:

``` C++
params.addExchange("BTCExchange", params.btcExchangeFees, false, true);
```

The `addExchange(std::string n, double f, bool h, bool m)` parameters are:
- Name of the exchange
- Fees
- Does the exchange provide an API to short sell?
- Has the exchange been fully implemented (in other words, is it possible for Blackbird to trade on that exchange?)

4) Finally, for each exchange the basic functions have to be implemented (e.g. send orders, check balance) in files named after the exchange's name (in our example: _btcexchange.h_ and _btcexchange.cpp_).

Here is the list of functions that have to be developed to connect the new exchange. Note the namespace `BTCExchange`:

``` C++
namespace BTCExchange {

// get quote
double getQuote(Parameters& params, bool isBid);

// get the current availability for usd or btc
double getAvail(Parameters& params, std::string currency);

// send order to the exchange and return order ID
int sendOrder(Parameters& params, std::string direction, double quantity, double price);

// check the status of the order
bool isOrderComplete(Parameters& params, int orderId);

// get the Bitcoin exposition
double getActivePos(Parameters& params);

// get the limit price according to the requested volume
double getLimitPrice(Parameters& params, double volume, bool isBid);

// send a request to the exchange and return a JSON object
json_t* authRequest(Parameters& params, std::string url, std::string request, std::string options);

}
```

**Comment by jcs224** [comment]
This is a great idea, I'm more of a PHP guy but it might be good to flex my C++ skills a little and add some exchanges.

I just built a plugin for the CubeCart e-commerce plugin using Coinbase, which has an exchange platform in addition to its wallet and merchant services. So I have a little experience with Bitcoin development under my belt! https://github.com/jcs224/cubecart-coinbase

**Comment by butor** [comment]
Thanks for your interest @jcs224! You're welcome to add any Bitcoin exchange to Blackbird. And of course let us know if you need assistance.

**Comment by butor** [comment]
__Note:__ it's possible to short sell on OKCoin but this hasn't been implemented yet. As for now Blackbird can only have _long_ positions on OKCoin.

**Comment by donald-leung** [comment]
"it's possible to short sell on OKCoin but this hasn't been implemented yet. As for now Blackbird can only have long positions on OKCoin."

I wonder if OKcoin supports short sell now?

Thanks a lot Butor

**Comment by butor** [comment]
Hi @donald-leung,

You are right, they updated their API with new functions. I think it will be possible to short sell (spot, not futures) with functions such as `/api/v1/borrow_money` and `/api/v1/repayment`. I'll take a look. Thanks!

**Comment by Frankenmint** [comment]
what is the difference between spot and futures?

**Comment by butor** [comment]
Hi @Frankenmint,

Here is the difference:

__Spot__
This is the current market price of Bitcoin: it represents the price you need to pay right now to buy Bitcoin. Same thing if you want to sell. The spot prices are the ones used by Blackbird in this project. As an example, these are all spot prices:

```
Bitfinex:    401.23 / 401.37
OKCoin:      402.66 / 402.67
Bitstamp:    398.92 / 399.87
Gemini:      400.73 / 400.74
```

__Futures__
In finance, futures (or futures contracts) are contracts between a buyer and seller to define in advance the price of a __future__ transaction. Originally they were used in commodities. For example, a futures contract to sell _x_ barrels of oil at a defined price, in 6 months. Thanks to that contract, the buyer and the seller both know the price of the transaction 6 months in advance, independently of the oil price fluctuation on the market within the next 6 months: they are protected against the market risk.
Nowadays, a great majority of futures are only used to speculate. You can find futures for everything (interest rates, currencies, indexes like S&P 500, etc), and now you can even find futures on Bitcoin ([more info about futures on Wikipedia](https://en.wikipedia.org/wiki/Futures_contract)).

__Note:__
There is an another arbitrage strategy, called __cash and carry arbitrage__ where you have a long position on the spot price and a short position on the future (or inversely), and you wait until the expiration date of the future, when the two prices converge ([more info on that strategy](http://www.investopedia.com/terms/c/cash-and-carry-arbitrage.asp)). We could easily adapt Blackbird to do this type of arbitrage.
