### ISSUE TITLE
src/parameters.h > #include <mysql/mysql.h> //terminates compile missing

### ISSUE THREAD

**Issue by Frankenmint** [butor/blackbird#40]
I'm guessing this is because I needed a cpp dependency? I tried adding c++ connector but it says I need to use bzr and from there I get this directory called trunk ...but the cmake command doesnt work in there which I presume would give me the mysql/mysql.h dependencies

This is on a linux machine I have everything else setup including using the apt-get dependencies

![logfile](https://puu.sh/mANvs/99d178ec34.png)

**Comment by butor** [comment]
Hi @Frankenmint,

Does the file `/usr/include/mysql/mysql.h` exist on your system? If the header file `mysql.h` is somewhere else, say `/opt/mysql/include`, then you need to add that path to the GCC line with the option `-I/opt/mysql/include`.

**Comment by Frankenmint** [comment]
Alright so Installing Mysql-Client requested me to use mysql-client-5.5 as a dependency first...I do that then look for the created `/usr/include/mysql/mysql.h` as you mention and it's never installed...doing `libmysqlclient-dev` created the dependencies, thank you...I'm now having the same step with openssl I've figured that its because i need libssl-dev by now so i'll just iterate through what I need and will possibly put together a dependency list string so you can add that to the readme.

**Comment by Frankenmint** [comment]
No dice....now I'm stuck...I followed as you suggest with getting the latest jansson driver and its still throwing me an error:

!(error2)[http://puu.sh/mBDB9/6f94b54a75.png]

I'm going to see if I can pin this down

**Comment by butor** [comment]
Hi @Frankenmint,

I hope you were able to manually install Jansson 2.7.

So if I summarize, this is what needs to be installed:

```
libssl-dev
libjansson-dev
libcurl4-openssl-dev
sendemail
libmysqlclient-dev
```

Thanks!

**Comment by Frankenmint** [comment]
I was...now its simply a config hangup on my end and I should be good to roll...thank you for all your help!  Review coming soon...
