### ISSUE TITLE
When I try to run BTC-E I have balance but blackbird says there is no usd balance

### ISSUE THREAD

**Issue by Frankenmint** [butor/blackbird#42]
I haven't dived into the code to look around for myself I'm just giving you info based on the cat output of the file

**Comment by butor** [comment]
Hi @Frankenmint,

This is because the BTC-e API hasn't been implemented yet. It's in the README file but I'll make it more obvious when the software starts. Thanks.

**Comment by butor** [comment]
Just made an update. Now this is what you would get:

```
[ Current balances ]
   Bitfinex:   0.00 USD    0.000000 BTC
   OKCoin:     0.00 USD    0.000000 BTC
   BTC-e:      n/a (API not implemented)
```

Thanks

**Comment by Frankenmint** [comment]
Is there an issue you're facing with implementing this?  I remember a friend of mine a few years ago was building a bot and had trouble with btc-e because he was required to generate an incrementing nonce on his side to provide in his api call to retrieve data properly...

**Comment by butor** [comment]
Hi @Frankenmint,

I haven't tried to implement the BTC-e API yet but I opened the enhancement #35 if anyone is interested to implement it.

Note (to your friend): we had an issue with the nonce in the past with other exchanges. We changed the type of the _nonce_ variable from `long` to `unsigned long long` and it fixed the issue.
For reference: issue #16 and pull request #17.
