### ISSUE TITLE
Crash just after send two orders

### ISSUE THREAD

**Issue by monossido** [butor/blackbird#421]
Blackbird output
```
Log file generated: output/blackbird_log_20180217_102458.log
Blackbird is running... (pid 28955)

terminate called after throwing an instance of 'std::out_of_range'
  what():  stol
Annullato
```
Log output

```
<Cexio> Trying to send a btc_eur buy limit order: 0,00@8.690,00
<Cexio> Done (order ID): 5689142503)

<Kraken> Trying to send a short "sell" limit order: 0,004680 @ $8.760,00...
<Kraken> Done (transaction ID: O5PEO6-54VOG-L6U5V6)

Waiting for the two orders to be filled...
```

Compiled and run on raspberry pi with raspbian

**Comment by CCKRK** [comment]
Due to bad error checking in Cexio::isOrderComplete. I don't have API keys to fix test this exchange, unfortunately.

**Comment by monossido** [comment]
Suggestions about how debug it?
I'm not an expert c++ developer, but I can try.

**Comment by CCKRK** [comment]
Well if you still have the log file you can use the CEXIO test functions to see whats going on in there. 


I'm not an expert either, but I don't think there's any reason for the stol call there. The function is passing you a string representation of the orderId, so you can just concatinate it to "id=" (e.g. string options = "id=" + orderId) and pass options to the authRequest call.

**Comment by CCKRK** [comment]
I can't be sure this is accurate because I don't have a key, but this code should never seg fault

```
bool isOrderComplete(Parameters& params, std::string orderId)
{
  using namespace std;

  bool tmp = true;
  unique_json root { authRequest(params, "/open_orders/","") };
  size_t arraySize = json_array_size(root.get());
  for (size_t i = 0; i < arraySize; ++i){
    string tmpid = json_string_value(json_object_get(json_array_get(root.get(),i),"id"));
    if (tmpid.compare(orderId.c_str())==0){
      *params.logFile << "<Cexio> Order Still open (ID: " << orderId << " )" << " Remaining: " 
      << json_string_value(json_object_get(json_array_get(root.get(),i),"pending"))
      << endl;
      return tmp = false;
    }
  }
  if (tmp == true){ *params.logFile << "<Cexio> Order Complete (ID: " << orderId << " )" << endl;}
  return tmp;
}
```

let me know if that works and I will change it in codebase

**Comment by monossido** [comment]
Thank you!
Testing now

**Comment by monossido** [comment]
Seems fixed
