### ISSUE TITLE
cLion instead of VisualStudio

### ISSUE THREAD

**Issue by RandyStevens** [butor/blackbird#434]
Any advice for developing with cLion vs VisualStudio?

**Comment by CCKRK** [comment]
Is there something you're having trouble with in particular?

**Comment by RandyStevens** [comment]
When I open the project in my IDE the error it returns when i try to press go in the IDE is
`
/Applications/CLion.app/Contents/bin/cmake/bin/cmake --build 
`

`
/Users/randalstevens/Workspace/blackbird/cmake-build-debug --target blackbird -- -j 2
make: /private/var/folders/_c/drbg5c9n3y30h14pdhvvxxp40000gn/T/AppTranslocation/76DF56DB-7DBA-442B-A775-0EAFDF4CED0F/d/CLion.app/Contents/bin/cmake/bin/cmake: No such file or directory
`

`
make: *** [cmake_check_build_system] Error 1
`

**Comment by CCKRK** [comment]
Looks like you did not import the project correctly, do not overwrite cmakelists.txt. You probably need to change a bunch of your build settings from the default to link the proper libraries. cLion is probably a bad choice for blackbird as they don't "support" .conf files -- even when you get it to build you'll probably have to modify parameters.cpp to find the config file, if it can be opened in cLion at all. 

My advice would be to not use cLion.

**Comment by RandyStevens** [comment]
ahhhh ok, im new to c++ development for sure. Thanks for the response.
please feel free to close this PR.

**Comment by CCKRK** [comment]
Just fyi this is an issue (not a PR) and you can close them yourself when you opened them.
