### ISSUE TITLE
Blackbird Shuts off after entering position...can I see a type of stack trace or troubleshoot it?

### ISSUE THREAD

**Issue by Frankenmint** [butor/blackbird#44]
I've been pretty busy but have the bot running 24-7 on some dedicated hardware. I see it attempted to enter a position, but that it seems to have died for no reason or cause after placing orders on the exchanges: 

  Bitstamp/Bitfinex:	 1.24% [target  0.80%, min -0.81%, max  1.29%]   trailing  1.19%  0/2
   Kraken/Bitfinex:	 1.06% [target  0.80%, min -1.61%, max  1.07%]   trailing  0.97%  0/2
   BTC-e/Bitfinex:	 0.21% [target  0.80%, min -2.29%, max  1.13%]   info only

[ 02/04/2016 06:06:00 ]
   Bitfinex: 	382.01 / 382.02
   Bitstamp: 	377.80 / 378.00
   Kraken: 	377.95 / 377.99
   BTC-e: 	381.50 / 381.20
   ----------------------------
   Bitstamp/Bitfinex:	 1.06% [target  0.80%, min -0.81%, max  1.29%]   trailing  1.19%  0/2
   Kraken/Bitfinex:	 1.06% [target  0.80%, min -1.61%, max  1.07%]   trailing  0.97%  0/2
   BTC-e/Bitfinex:	 0.21% [target  0.80%, min -2.29%, max  1.13%]   info only

[ 02/04/2016 06:06:05 ]
   Bitfinex: 	382.01 / 382.02
   Bitstamp: 	377.80 / 378.00
   Kraken: 	377.95 / 377.99
   BTC-e: 	381.71 / 381.27
   ----------------------------
   Bitstamp/Bitfinex:	 1.06% [target  0.80%, min -0.81%, max  1.29%]   trailing  1.19%  1/2
   Kraken/Bitfinex:	 1.06% [target  0.80%, min -1.61%, max  1.07%]   trailing  0.97%  0/2
   BTC-e/Bitfinex:	 0.19% [target  0.80%, min -2.29%, max  1.13%]   info only

[ 02/04/2016 06:06:10 ]
   Bitfinex: 	382.04 / 382.45
   Bitstamp: 	378.39 / 378.98
   Kraken: 	377.95 / 377.99
   BTC-e: 	381.71 / 381.27
   ----------------------------
   Bitstamp/Bitfinex:	 0.81% [target  0.80%, min -0.81%, max  1.29%]   trailing  1.19%  2/2
<Bitstamp> Looking for a limit price to fill 0.14 BTC...
<Bitstamp> order book: 22.88@$378.00
<Bitfinex> Looking for a limit price to fill 0.14 BTC...
<Bitfinex> order book: 12.58@$382.03

[ ENTRY FOUND ]
   Date & Time:       02/04/2016 06:06:10
   Exchange Long:     Bitstamp (id 1)
   Exchange Short:    Bitfinex (id 0)
   Fees:              0.25% / 0.20%
   Price Long:        $378.00 (target)
   Price Short:       $382.03 (target)
   Spread:            0.81%
   Cash used:         $53.46 on each exchange
   Exit Target:       -0.29%

<Bitstamp> Looking for a limit price to fill 0.14 BTC...
<Bitstamp> order book: 22.88@$378.00
<Bitstamp> Trying to send a "buy" limit order: 0.14@$378.00...
<Bitstamp> Done (order ID: 109,742,308)

<Bitfinex> Looking for a limit price to fill 0.14 BTC...
<Bitfinex> order book: 24.43@$382.04
<Bitfinex> Trying to send a "sell" limit order: 0.14@$382.04...
<Bitfinex> Done (order ID: 608,557,553)

Waiting for the two orders to be filled...

**Comment by butor** [comment]
Hi @Frankenmint,

Blackbird actually didn't shut off. What happened is that one of your orders never got fully filled and Blackbird kept waiting for the order to complete (last line of your log: _Waiting for the two orders to be filled..._).

That can happen when the market suddenly moves away from one of your limit prices. You can try to avoid this locked situation by increasing the parameter `OrderBookFactor`.

That being said, I just pushed a new version of Blackbird that brings the following advantages:

1. It will be more obvious that Blackbird is not down but simply waiting for an order to complete.
2. The log file will tell you which order (long one or short one) is still not complete.

I also increased `OrderBookFactor` from 2.0 to 3.0 by default.
