### ISSUE TITLE
Bitfinex Error With JSON

### ISSUE THREAD

**Issue by jspenc72** [butor/blackbird#45]
```bash
<Bitfinex> Error with JSON: {"message": "Could not find a key matching the given X-BFX-APIKEY."}. Retrying...
```

**Comment by jspenc72** [comment]
Receive this error when trying to connect to bitfinex. Problem Appears to be a malformed http request.

**Comment by jspenc72** [comment]
Here are other examples of people getting the same error:
https://bitcointalk.org/index.php?topic=528431.new

**Comment by jspenc72** [comment]
Uncommented this    // curl_easy_setopt(params.curl, CURLOPT_VERBOSE, 1L);
Saw this in the output.
X-BFX-APIKEY:"xxx"
X-BFX-PAYLOAD:xxx
X-BFX-SIGNATURE:xxx

Corrected this to be this:
X-BFX-APIKEY:xxx
X-BFX-PAYLOAD:xxx
X-BFX-SIGNATURE:xxx

But now I get the following error: 
Error with JSON: {"message": "Invalid X-BFX-SIGNATURE."}. Retrying...

**Comment by butor** [comment]
Hi @jspenc72,

Thanks for the feedback. When you put your credentials into the config file, make sure you don't include any quotes. It should be similar to this:

```
# Bitfinex
BitfinexApiKey=abcdef123456
BitfinexSecretKey=abcdef123456
BitfinexFees=0.0020
```
Can you please recreate an API key on Bitfinex and try again? Thanks.

**Comment by jspenc72** [comment]
What about the email addresses? Should they be in quotes?

**Comment by jspenc72** [comment]
Still having the issue, blackbird.conf does not contain quotes. Set this Curl to verbose and got this
< HTTP/1.1 401 Unauthorized
* Server nginx is not blacklisted
< Server: nginx
< Date: Sun, 07 Feb 2016 23:27:52 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 38
< Connection: keep-alive
< Vary: Accept-Encoding
< X-UA-Compatible: IE=Edge,chrome=1
< Cache-Control: no-cache

**Comment by jspenc72** [comment]
Still getting this:
<Bitfinex> Error with JSON: {"message": "Invalid X-BFX-SIGNATURE."}. Retrying...

**Comment by jspenc72** [comment]
Testing with an api key and secret that have full permissions.

**Comment by jspenc72** [comment]
Sorry, i had a rogue' in my .conf. Removed and now Blackbird appears to be authenticating correctly but I get this:

Blackbird Bitcoin Arbitrage
DISCLAIMER: USE THE SOFTWARE AT YOUR OWN RISK

Log file generated: blackbird_log_20160207_183426.log
Blackbird is running... (pid 10607)

* Hostname was NOT found in DNS cache
*   Trying 149.126.72.104...
* Connected to api.bitfinex.com (149.126.72.104) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: OU=GT54605854; OU=See www.rapidssl.com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=*.bitfinex.com
* 	 start date: 2014-10-16 17:43:37 GMT
* 	 expire date: 2016-10-15 19:38:19 GMT
* 	 subjectAltName: api.bitfinex.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> POST /v1/balances HTTP/1.1
Host: api.bitfinex.com
Accept: */*
X-BFX-APIKEY:111xxx
X-BFX-PAYLOAD:111xxx
X-BFX-SIGNATURE:111xxx
Content-Length: 0
Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Sun, 07 Feb 2016 23:34:26 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 2
< Connection: keep-alive
< Vary: Accept-Encoding
< X-UA-Compatible: IE=Edge,chrome=1
< Cache-Control: no-cache
< X-Runtime: 0.031755
< X-Rack-Cache: invalidate, pass
< Expires: Sun, 07 Feb 2016 23:34:25 GMT
< X-Frame-Options: SAMEORIGIN
< X-Iinfo: 0-10625592-10625593 NNNN CT(15 16 0) RT(1454888065555 49) q(0 0 0 0) r(0 0) U6
< X-CDN: Incapsula
< 
* Connection #0 to host api.bitfinex.com left intact
* Found bundle for host api.bitfinex.com: 0xc985d0
* Re-using existing connection! (#0) with host api.bitfinex.com
* Connected to api.bitfinex.com (149.126.72.104) port 443 (#0)
> POST /v1/balances HTTP/1.1
Host: api.bitfinex.com
Accept: */*
X-BFX-APIKEY:111xxx
X-BFX-PAYLOAD:111xxx
X-BFX-SIGNATURE:111xxx
Content-Length: 0
Content-Type: application/x-www-form-urlencoded

< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Sun, 07 Feb 2016 23:34:26 GMT
< Content-Type: application/json; charset=utf-8
< Content-Length: 2
< Connection: keep-alive
< Vary: Accept-Encoding
< X-UA-Compatible: IE=Edge,chrome=1
< Cache-Control: no-cache
< X-Runtime: 0.040354
< X-Rack-Cache: invalidate, pass
< Expires: Sun, 07 Feb 2016 23:34:25 GMT
< X-Frame-Options: SAMEORIGIN
< X-Iinfo: 0-10625592-10625593 SNNN RT(1454888065555 151) q(0 0 0 0) r(0 0) U6
< X-CDN: Incapsula
< 
* Connection #0 to host api.bitfinex.com left intact
Segmentation fault (core dumped)

**Comment by jspenc72** [comment]
This is my log file
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 02/07/2016 18:34:26

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.30%

[ Current balances ]
~                                                                                                                                      
~                                                                                                                                      
~                                                                                                                                      
~                                                                                                                                      
~

**Comment by jspenc72** [comment]
This is my result file.
TRADE_ID,EXCHANGE_LONG,EXHANGE_SHORT,ENTRY_TIME,EXIT_TIME,DURATION,TOTAL_EXPOSURE,BALANCE_BEFORE,BALANCE_AFTER,RETURN

**Comment by jspenc72** [comment]
I am trying to use bitfinex and sevennintysix 
The sevennintysix doesn't appear to be authenticating.
When the main.cpp gets to the loop that calls getAvail() on each exchange then it crashes on the second loop.

**Comment by jspenc72** [comment]
My blackbird.conf file lists them in this order.
# Bitfinex
BitfinexApiKey=
BitfinexSecretKey=
BitfinexFees=0.0020

# OkCoin
OkCoinApiKey=
OkCoinSecretKey=
OkCoinFees=0.0020

# Bitstamp
BitstampClientId=
BitstampApiKey=
BitstampSecretKey=
BitstampFees=0.0025

# Gemini
GeminiApiKey=
GeminiSecretKey=
GeminiFees=0.0025

# Kraken
KrakenApiKey=
KrakenSecretKey=
KrakenFees=0.0025

# ItBit
ItBitApiKey=
ItBitSecretKey=
ItBitFees=0.0020

# BTCe
BTCeApiKey=
BTCeSecretKey=
BTCeFees=0.0020

# 796.com
SevenNintySixApiKey=
SevenNintySixSecretKey=
SevenNintySixFees=0.0025

**Comment by jspenc72** [comment]
I know you commented that 796 hasn't been tested but if you can provide any assistance I would greatly appreciate it.

**Comment by jspenc72** [comment]
Thanks in advance for your response  @butor

**Comment by butor** [comment]
Hi @jspenc72,

Can you show us the output of the following command:

```
curl -v https://api.bitfinex.com/v1/ticker/btcusd
```

Also, can you comment again the line `curl_easy_setopt(params.curl, CURLOPT_VERBOSE, 1L)` then try to run Blackbird __without__ 796 and show us the output?

I think the `Segmentation fault (core dumped)` you got is probably due to a bug in our 796 implementation (as you said it has never been tested).

Thanks

**Comment by jspenc72** [comment]
Here is the output

bash```
root@tribeca:~# curl -v https://api.bitfinex.com/v1/ticker/btcusd
* Hostname was NOT found in DNS cache
*   Trying 149.126.72.104...
* Connected to api.bitfinex.com (149.126.72.104) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
* SSLv3, TLS handshake, Server hello (2):
* SSLv3, TLS handshake, CERT (11):
* SSLv3, TLS handshake, Server key exchange (12):
* SSLv3, TLS handshake, Server finished (14):
* SSLv3, TLS handshake, Client key exchange (16):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSLv3, TLS change cipher, Client hello (1):
* SSLv3, TLS handshake, Finished (20):
* SSL connection using ECDHE-RSA-AES256-GCM-SHA384
* Server certificate:
* 	 subject: OU=GT54605854; OU=See www.rapidssl.com/resources/cps (c)14; OU=Domain Control Validated - RapidSSL(R); CN=*.bitfinex.com
* 	 start date: 2014-10-16 17:43:37 GMT
* 	 expire date: 2016-10-15 19:38:19 GMT
* 	 subjectAltName: api.bitfinex.com matched
* 	 issuer: C=US; O=GeoTrust Inc.; CN=RapidSSL SHA256 CA - G3
* 	 SSL certificate verify ok.
> GET /v1/ticker/btcusd HTTP/1.1
> User-Agent: curl/7.35.0
> Host: api.bitfinex.com
> Accept: */*
> 
< HTTP/1.1 200 OK
* Server nginx is not blacklisted
< Server: nginx
< Date: Mon, 08 Feb 2016 15:53:16 GMT
< Content-Type: application/json; charset=utf-8
< Transfer-Encoding: chunked
< Connection: keep-alive
< Vary: Accept-Encoding
< Vary: Accept-Encoding
< X-UA-Compatible: IE=Edge,chrome=1
< ETag: "77d83bf71a9051244488c48beb888c4a"
< Cache-Control: no-cache
< X-Request-Id: 9b2885a564d6e1b61623f457a8744884
< X-Runtime: 0.008749
< X-Rack-Cache: miss
< Expires: Mon, 08 Feb 2016 15:53:15 GMT
< X-Frame-Options: SAMEORIGIN
< Set-Cookie: visid_incap_116519=U5O/u/XOSyKOz2FWSTYbHey5uFYAAAAAQUIPAAAAAABKHOAaOCjeTq3HjtAZzW2l; expires=Wed, 07 Feb 2018 14:42:57 GMT; path=/; Domain=.bitfinex.com
< Set-Cookie: nlbi_116519=1rnKMKvSgy/P7A3XGLrcwAAAAAAGpL0fmHBCl7T8Mo+9p0xx; path=/; Domain=.bitfinex.com
< Set-Cookie: incap_ses_128_116519=/1EaUTUrrCFATUJRH8DGAey5uFYAAAAAd+aIn213SyR2HNtVlaoDSQ==; path=/; Domain=.bitfinex.com
< X-Iinfo: 10-101585433-101520497 PNNN RT(1454946796211 49) q(0 0 0 1) r(0 0) U5
< X-CDN: Incapsula
< 
* Connection #0 to host api.bitfinex.com left intact
{"mid":"374.36","bid":"374.31","ask":"374.41","last_price":"374.41","timestamp":"1454946788.551013788"}
```

**Comment by jspenc72** [comment]
Blackbird runs fine without 796, or kraken

**Comment by jspenc72** [comment]
the output is the same as the readme.

**Comment by jspenc72** [comment]
```bash
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 02/08/2016 11:02:39

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.30%

[ Current balances ]
0
1
After Balances
   Bitfinex:    0.00 USD        0.000000 BTC
   OKCoin:      0.00 USD        0.000000 BTC

[ Cash exposure ]
   TEST cash used
   Value: $25.00

[ 02/08/2016 11:02:42 ]
   Bitfinex:    374.59 / 374.64
   OKCoin:      375.68 / 375.69
   ----------------------------
   OKCoin/Bitfinex:     -0.29% [target  0.80%, min -0.29%, max -0.29%]

```

**Comment by jspenc72** [comment]
```bash
--------------------------------------------
|   Blackbird Bitcoin Arbitrage Log File   |
--------------------------------------------

Blackbird started on 02/08/2016 11:04:28

[ Targets ]
   Spread Entry:  0.80%
   Spread Target: 0.30%

[ Current balances ]
0
1
After Balances
   Bitfinex:    0.00 USD        0.000000 BTC
   OKCoin:      0.00 USD        0.000000 BTC

[ Cash exposure ]
   TEST cash used
   Value: $25.00

[ 02/08/2016 11:04:30 ]
   Bitfinex:    374.50 / 374.58
   OKCoin:      375.70 / 375.71
   ----------------------------
   OKCoin/Bitfinex:     -0.32% [target  0.80%, min -0.32%, max -0.32%]

[ 02/08/2016 11:04:33 ]
   Bitfinex:    374.50 / 374.58
   OKCoin:      375.70 / 375.71
   ----------------------------
   OKCoin/Bitfinex:     -0.32% [target  0.80%, min -0.32%, max -0.32%]
```

**Comment by butor** [comment]
Thanks @jspenc72. The Kraken and 796.com implementations need to be fixed. Both have issues. I'll put a warning in the README file.

**Comment by jspenc72** [comment]
I think I have a solution, would you have a few minutes to skype?

**Comment by butor** [comment]
Hi @jspenc72,

Can you propose your solution here so it will be shared by others, or if you prefer shoot me a private email at julien.hamilton@gmail.com. Thanks
