### ISSUE TITLE
Having trouble building Blackbird

### ISSUE THREAD

**Issue by Ogeeon** [butor/blackbird#452]
Hello, everyone.
I'm trying to install Blackbird on a VDS. It's Debian 9 there.
Everything worked OK up to the last command: `cmake --build ./build -- install`
This is what I get:

[ 60%] Building CXX object CMakeFiles/blackbird.dir/src/exchanges/exmo.cpp.o
In file included from /usr/local/blackbird/src/exchanges/exmo.cpp:7:0:
/usr/local/blackbird/src/utils/hmac_sha512.hpp: In constructor ‘HMAC_SHA512::HMAC_SHA512(const string&, const string&)’:
/usr/local/blackbird/src/utils/hmac_sha512.hpp:11:12: error: aggregate ‘HMAC_CTX ctx’ has incomplete type and cannot be defined
/usr/local/blackbird/src/utils/hmac_sha512.hpp:12:21: error: ‘HMAC_CTX_init’ was not declared in this scope
/usr/local/blackbird/src/utils/hmac_sha512.hpp:27:24: error: ‘HMAC_CTX_cleanup’ was not declared in this scope
CMakeFiles/blackbird.dir/build.make:410: recipe for target 'CMakeFiles/blackbird.dir/src/exchanges/exmo.cpp.o' failed
make[2]: *** [CMakeFiles/blackbird.dir/src/exchanges/exmo.cpp.o] Error 1
CMakeFiles/Makefile2:163: recipe for target 'CMakeFiles/blackbird.dir/all' failed
make[1]: *** [CMakeFiles/blackbird.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Please advise on what should I do.

**Comment by monossido** [comment]
https://github.com/butor/blackbird/issues/353
