### ISSUE TITLE
OkCoin connetction troubles

### ISSUE THREAD

**Issue by wwarlock** [butor/blackbird#476]
Looks like OKCoin API was changed.
Now they are required to use `/api/v1/` and without `.do`-postfix urls.
For example
`https://www.okcoin.com/api/v1/ticker`
Instead of
`https://www.okcoin.com/api/ticker.do?ok=1`

Requesting the first link is giving some answers from server.
And requesting the second link is giving errors from cloudflare.
I used the `curl` utility to make my requests.

**Comment by edwinbodge** [comment]
Navigate to the following file...
`./src/exchanges/okcoin.cpp`

Make the following change:
Remove:
`unique_json root { exchange.getRequest("/api/ticker.do?ok=1") };`
Replace with:
`unique_json root { exchange.getRequest("/api/v1/ticker.do?symbol=btc_usd") };`

As @wwarlock mentioned, OKCoin changed their API, and your extension must be updated to reflect the proper URL. You can directly view the API response in your browser at https://www.okcoin.com/api/v1/ticker.do?symbol=btc_usd

**Comment by wwarlock** [comment]
I made the pull request please check and apply it 
https://github.com/butor/blackbird/pull/477

**Comment by wbrickner** [comment]
This has regressed, idk how.

Current master incorrectly connects to `.do` URLs for OkCoin.
