### ISSUE TITLE
File sharing not working, Windows Explorer properties sharing tab crash/hang

### ISSUE THREAD

**Issue by Tarocco** [butor/blackbird#479]
After running Blackbird 1.0.11 x64 on Windows 10 Pro x64 1709 with default options (no switches),

- Windows file sharing (SMB) no longer works at all (even when it is enabled in system settings).
- in Windows Explorer, _Right-click (on file/folder) > Properties > Sharing_ causes Windows Explorer to hang.

**Comment by butor** [comment]
Wrong project

**Comment by Tarocco** [comment]
@butor can you please elaborate on why this any my other two issues are "wrong project"?
