### ISSUE TITLE
Computers no longer accessible by host name on network

### ISSUE THREAD

**Issue by Tarocco** [butor/blackbird#480]
Computer A: Blackbird 1.0.11 x64 on Windows 10 Pro x64 1709 with default options (no switches)

Computer B: No Blackbird, Windows 10 Pro x64 1709

I am no longer able to access A from B by host name, and vice versa (cannot access B from A by host name). Is there a simple explanation for why local network host name network access completely stop working after running Blackbird? Is there a blackbird.exe switch I can use to allow host names again?

**Comment by butor** [comment]
Wrong project
