### ISSUE TITLE
Task bar/start menu intermittently working/breaking

### ISSUE THREAD

**Issue by Tarocco** [butor/blackbird#481]
After running Blackbird 1.0.11 (x64) on Windows 10 Pro, x64, 1709 with the `-L` switch, Every 10 seconds or so, the task bar, start menu, clock (opens calendar) and notifications button all cease to work, for about 10 seconds. This seems to alternate pretty regularly (exact duration of working/not working I have not measured) but it feels like about 10 seconds on and off.

Expected: clicking on the start menu icon or pressing the meta key on my keyboard opens the start menu

Observed: nothing happens

Restoring from backup fixes the problem, so it is Blackbird causing the issue.

**Comment by butor** [comment]
Wrong project
