### ISSUE TITLE
Error with JSON when executing Bitfinex trade

### ISSUE THREAD

**Issue by sdrelton** [butor/blackbird#50]
Hey, I'm having a bit of trouble getting Blackbird up and running. Everything runs smoothly until I'm executing a trade at which point I get the following error in my log file.

............
[ 02/21/2016 11:20:00 ]
   Bitfinex:    449.07 / 449.10
   OKCoin:      447.36 / 447.44
   Kraken:      440.31 / 442.32
   ----------------------------
   OKCoin/Bitfinex:      0.36% [target  0.80%, min  0.36%, max  0.39%]
   Kraken/Bitfinex:      1.53% [target  0.80%, min  1.53%, max  1.53%]   trailing  1.53%  0/2
[ 02/21/2016 11:20:03 ]
   Bitfinex:    449.07 / 449.10
   OKCoin:      447.36 / 447.43
   Kraken:      440.31 / 442.32
   ----------------------------
   OKCoin/Bitfinex:      0.37% [target  0.80%, min  0.36%, max  0.39%]
   Kraken/Bitfinex:      1.53% [target  0.80%, min  1.53%, max  1.53%]   trailing  1.53%  1/2
[ 02/21/2016 11:20:06 ]
   Bitfinex:    449.07 / 449.10
   OKCoin:      447.36 / 447.43
   Kraken:      440.33 / 442.32
   ----------------------------
   OKCoin/Bitfinex:      0.37% [target  0.80%, min  0.36%, max  0.39%]
   Kraken/Bitfinex:      1.53% [target  0.80%, min  1.53%, max  1.53%]   trailing  1.53%  2/2
Error with JSON:
'[' or '{' expected near '<'
Buffer:
<!DOCTYPE html>

<html class="no-js" lang="en"> 
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <meta name="description"
    content="The largest and most advanced crypto-currencies trading platform">
  <meta name="keywords"
    content="bitcoin,exchange,bitcoin exchange,litecoin,margin,trade">
  <meta name="referrer" content="origin">
  <title>Bitfinex - Error 404: Page not found</title>
............

It then continues retrying to send the trade, obtaining error 404 each time.

Any help you could provide would be much appreciated!

Thanks.

**Comment by butor** [comment]
Hi @sdrelton,

Thank you for the feedback. Your error is the same as the one described here: #41. I opened a ticket with Bitfinex to understand what's going on. I've never faced such an issue with Bitfinex so it looks like it's dependent of the environment on which Blackbird runs. Meanwhile, a workaround has been described on #41. Thanks.

**Comment by butor** [comment]
Thanks @sdrelton. I just saw you proposed a workaround on #41.
