### ISSUE TITLE
Kraken SSL Connect Error

### ISSUE THREAD

**Issue by sdrelton** [butor/blackbird#53]
When doing some testing I ran into an issue with Kraken.

My log file (modified to print the URL of every request) looks like this:

[ 02/23/2016 22:01:06 IN MARKET: Long Kraken / Short Bitfinex ]
URL: https://api.bitfinex.com/v1/ticker/btcusd
URL: https://api.bitfinex.com/v1/ticker/btcusd
   Bitfinex:    422.28 / 422.31
URL: https://api.kraken.com/0/public/Ticker
URL: https://api.kraken.com/0/public/Ticker
   Kraken:      418.17 / 420.90
   ----------------------------
   Kraken/Bitfinex:      0.99% [target -0.72%, min  0.26%, max  1.04%]
[ 02/23/2016 22:01:12 IN MARKET: Long Kraken / Short Bitfinex ]
URL: https://api.bitfinex.com/v1/ticker/btcusd
URL: https://api.bitfinex.com/v1/ticker/btcusd
   Bitfinex:    422.28 / 422.31
URL: https://api.kraken.com/0/public/Ticker
URL: https://api.kraken.com/0/public/Ticker
Error with cURL: SSL connect error
  URL: https://api.kraken.com/0/public/Ticker
  Retry in 2 sec...
Error with cURL: SSL connect error
  URL: https://api.kraken.com/0/public/Ticker
  Retry in 2 sec...

The program attempts to retry for about 30 minutes and then it runs fine again. Using GapSec = 6.0 this occurred approximately every 1hr 20mins.

I believe the reason for this is that I was hitting the Kraken API call limit (see excerpt below). You can clearly see from my log file that every time we are making two requests to "kraken.com/0/public/Ticker", one for the bid and ask prices respectively. I propose that these be merged into one call where both pieces of data are extracted at the same time. This would make it much harder to hit the API call limit, leading to maximized uptime of the program. It would also decrease the number of HTTP requests, which would minimize the bandwidth usage and speed up the time to analyze each tick.

Excerpt from Kraken API FAQ (https://www.kraken.com/help/api):

Every user of our API has a "call counter" which starts at 0.

Ledger/trade history calls increase the counter by 2.

Place/cancel order calls do not affect the counter.

All other API calls increase the counter by 1.

The user's counter is reduced every couple of seconds, and if the counter exceeds the user's maximum API access is suspended for 15 minutes. Tier 2 users have a maximum of 15 and their count gets reduced by 1 every 3 seconds. Tier 3 and 4 users have a maximum of 20; the count is reduced by 1 every 2 seconds for tier 3 users, and is reduced by 1 every 1 second for tier 4 users.

**Comment by butor** [comment]
Fixed with the merge #52.
