### ISSUE TITLE
Fatal error: 'mysql/plugin_auth_common.h' file not found

### ISSUE THREAD

**Issue by timforgach** [butor/blackbird#56]
Installed all the required packages, getting this error when I try to run the make command:

/usr/local/include/mysql/mysql/client_plugin.h:103:10: fatal error: 'mysql/plugin_auth_common.h' file not found

**Comment by butor** [comment]
Hi @timforgach,

Did you install the __dev__ package (i.e. `apt-get install libmysqlclient-dev `)?

If yes, what is the complete path to your _mysql.h_ file?

**Comment by KosherBacon** [comment]
I had this problem on my Mac running OS X 10.11. I got it to compile by installing mysql56 instead of the current version which I believe is 5.7.

**Comment by butor** [comment]
Thanks @KosherBacon
