### ISSUE TITLE
Error with cURL: Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by vaisov** [butor/blackbird#61]
Error with cURL: Peer certificate cannot be authenticated with given CA certificates
  URL: https://api.itbit.com/v1/markets/XBTUSD/ticker
  Retry in 2 sec...

**Comment by butor** [comment]
It seems very similar to the issue #43. In particular:

> Upgrading your `ca-certificates` package to a newer version might solve the problem:
```
sudo apt-get upgrade ca-certificates
```

Please have a look.

**Comment by vaisov** [comment]
Tried that, already have the latest package. I'm using Debian 8.4.

**Comment by butor** [comment]
What is your cURL version?

```
curl --version
```

Also, it might be an issue with your machine's time. Restart the _Network Time Protocol_ daemon of your server:
```
sudo service ntpd restart
``` 
and try again

**Comment by vaisov** [comment]
To be more precise I use it on Raspberry Pi 3. Where OSMC is running based on Debian 8.4.

```
root@osmc:~/blackbird# curl --version
curl 7.38.0 (arm-unknown-linux-gnueabihf) libcurl/7.38.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP
```

After restarting ntp the issue still persists.

**Comment by butor** [comment]
The user from error #43 was also on Raspberry Pi. He installed Ubuntu Mate to solve the problem.

Can you update your cURL? It's a little old.
* Yours: 7.38.0
* Mine: 7.47.0
* Latest: 7.49.1

If you want to see the details of your issue you can type:
```
curl -v https://api.itbit.com/v1/markets/XBTUSD/ticker
```
