### ISSUE TITLE
Issue with "make" and openssl/sha.h

### ISSUE THREAD

**Issue by GuySawyer** [butor/blackbird#62]
When running make, I get this error:

`
g++ -c -g -Wall -O2 src/bitfinex.cpp -o src/bitfinex.o
src/bitfinex.cpp:7:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
`

But I have openssl-1.0.2h_1 installed.

Help appreciated.

**Comment by butor** [comment]
Are you sure you have installed the exact following libraries:

```
libssl-dev
libcurl4-openssl-dev
```

If you still have the problem, what is your Linux distribution?

**Comment by GuySawyer** [comment]
I'm on osx using Homebrew, so I did run
`brew install openssl
brew install curl`

I managed to get it working by
- making sure xcode developer tools was installed
- unlinking openssl
- upgrading openssl
- and then force linking it again:

`xcode-select --install
brew openssl unlink
brew upgrade openssl
brew link openssl --overwrite --force`
