### ISSUE TITLE
Questions on strategy settings

### ISSUE THREAD

**Issue by dunham100** [butor/blackbird#66]
Hi, 

I'm a bit new to the trading/strategy params.  Is there any docs on breaking down the following to help understand the strategy the bot will take.  Thanks!

# Strategy parameters
GapSec=3.0
SpreadEntry=0.0020
SpreadTarget=0.0050
PriceDeltaLimit=0.10
TrailingSpreadLim=0.0008
TrailingSpreadCount=1
OrderBookFactor=3.0
UseVolatility=false
VolatilityPeriod=600

**Comment by butor** [comment]
I've recently updated the README file with the details of each parameter ([link here](https://github.com/butor/blackbird/blob/master/README.md#blackbird-parameters))

**Comment by dunham100** [comment]
Thank you.. just curious The SpreadEntry should always be greater then SpreadTarget?  Is there any cases, like above, where you'd want the Entry lower then the target?

cheers

**Comment by dunham100** [comment]
Got it.  Just another question,  can you break down the exit strategy on this trade:  I'm having difficulty figuring out when blackbird will automatically exit for the profit(not sure with the amounts). 

Thanks!

[ 06/02/2016 19:09:27 IN MARKET: Long OKCoin / Short Bitfinex ]
   Bitfinex: 	542.48 / 542.64
   OKCoin: 	540.09 / 540.39
   Kraken: 	538.48 / 539.20
   ----------------------------
   OKCoin/Bitfinex:	 0.47% [target -0.46%, min  0.21%, max  0.67%]

**Comment by butor** [comment]
The exit will be triggered when the OKCoin/Bitfinex spread will reach -0.46%, as defined by the target. Note that Blackbird won't exit at -0.46% but will try to wait a little longer to see if the spread continues to decrease. If that's the case the profit of the trade will increase.
