### ISSUE TITLE
Question about 796.com wallet

### ISSUE THREAD

**Issue by vaisov** [butor/blackbird#67]
I've tried to transfer BTC to any of the wallets available on 796.com, but in the log file I see: 796.com: 0.00 USD 0.000000 BTC. Which wallet should I use?

**Comment by butor** [comment]
796.com has been implemented but never tested. So it might be a bug. Are you familiar with C++ so you can help troubleshooting?

That being said, I'm personally not familiar with 796.com and I see three different balances we can get from the API:
* `btc`: wallet balance
* `mri`: balance of 796Xchange-MRI
* `asicminer`: balance of ASICMINER-796

Can you explain the differences? I guess your BTC can be retrieve with `btc`. What about your USD?

**Comment by vaisov** [comment]
796.com has these wallets which are used for BTC trading:

- Spot account for spot BTC trading
- Margin account for futures BTC trading

Unfortunately I'm not familiar with C++, however I'll try to look into the code, maybe I'll find a way on how to fix it.

**Comment by butor** [comment]
Which one is the spot account? `mri` or `asicminer`?

**Comment by vaisov** [comment]
Not sure what is mri in 796.com, but here are the wallets you can transfer money between:

- Main Wallet
- Spot Account
- Quanto Contracts(USD) Margin Account
- XinHua A50 Margin Account
- E-mini Dow Margin Account
- DAX Margin Account
- NK225M Margin Account
- USD/CNH Margin Account
- EUR/USD Margin Account
- USD/JPY Margin Account
- AUD/USD Margin Account
- GBP/USD Margin Account
- XTI/USD Margin Account
- XAU/USD Margin Account
- XAG/USD Margin Account

Though according to API docs all you can retrieve are:
- Main Wallet
- margin account (with get_assets)

So I'm completely out of idea what is 796Xchange-MRI

**Comment by butor** [comment]
I contacted 796.com to get more details about their API. I'll keep you posted.

**Comment by vaisov** [comment]
Thanks, waiting for reply. However withdrawal doesn't work on their page and their support stopped replying, so it could be that it's not very reliable exchange to trade on :)

**Comment by vaisov** [comment]
Finally support contacted me and they found out that in order to withdraw - you have to enable 2-fa and add phone number. So it's pretty safe, I'd say to use.

**Comment by btctoken** [comment]
The goal on 796 is to use the futures with leverage to initiate and unwind the arbitrage.

The coins should be in your margin account.

When you go long on per say bit bitfinex you would then initiate the open sell order on 796 futures 

When you sell the bitfinex coin you would then execute a close sell order.

I would recommend setting this up on bitvc.com (huobi) same contract pretty much but way more liquid
