### ISSUE TITLE
std::runtime error

### ISSUE THREAD

**Issue by pol672** [butor/blackbird#69]
when I was compiling i know one file didn't pass. But when i start ./blackbird it says std::runtime error.
any ideas how to fix it?

**Comment by butor** [comment]
Hi @pol672, you need to provide more details (e.g. logs, complete error). What do you mean by a file didn't pass the compilation? Thanks

**Comment by pol672** [comment]
Yeah the error I don't know about when I typed make there was a file that had some errors but it paste. I'm trying to run it on a raspberry pi B+, for exchange I've got bitstamp and bitfinex. This is what I get.

screenshot: https://www.dropbox.com/s/jlczcl72wjoysx2/Screenshot%20from%202016-07-04%2018%3A58%3A48.png?dl=0

**Comment by butor** [comment]
- What is the file that had errors during the compilation?
- Can you type the command ``locale`` in your terminal and show us the result?

Thanks

**Comment by pol672** [comment]
I fixed it myself. I deleted the blackbird file and than rerun make. Now it's says blackbird running  and log file generated so I guess it's fixed, but thankx for the help

**Comment by pol672** [comment]
it' was indeed because it wasn't locale. if I do ssh again on my pi and than run screen ./blackbird I still get screen terminating but if I run local screen ./blackbird not a problem.

**Comment by butor** [comment]
Thank you @pol672 for the feedback. I can close the issue.
