### ISSUE TITLE
Help wanted - On Entry and Exit

### ISSUE THREAD

**Issue by Newar417** [butor/blackbird#77]
Entry question: I have `TrailingSpreadCount 1`, but once an opportunity is found, the log reads: 
`trailing  0.50%  0/1` for probably 20 times or so, the spread even rises to 0.60% in that time, but it still does not enter. This is only with the testing amount, so I doubt liquidity is an issue.

Exit question: How is decided when to exit? The price went double of my profit target and the bot still did not exit. Instead he rode it all the way down again, now below my target.

**Comment by butor** [comment]
Hi @Newar417 
Can you please show me the relevant part of your log file (please hide any sensitive information)? It will be easier for me to understand what's going on. Thanks.
