### ISSUE TITLE
The way struct tm is used in main results in UB.

### ISSUE THREAD

**Issue by greatwolf** [butor/blackbird#79]
Consider the lines here https://github.com/butor/blackbird/blob/master/src/main.cpp#L294

    struct tm* timeinfo;
    timeinfo = localtime(&rawtime);

You're storing a pointer to an internal tm. Various reference docs on the net specifically states that C time functions dealing with `struct tm` may change the value of that internal tm. Storing a reference to that internal tm and just using it directly is a bad idea. Not only does it make your code non-reentrant but you also have to content with unexpected side-effects when you make subsequent calls to any of the `*time` C functions.

When I was testing it under windows, this resulted in `timeinfo` getting bogus values in the giant processing loop eg. getting 25000+ second elapses time causing it to go into an almost infinite sleep on line https://github.com/butor/blackbird/blob/master/src/main.cpp#L330

As a temp hacky fix to get things working I just stored tm on the stack. eg.

    tm safetm;
    tm *timeinfo = &safetm;
    *timeinfo = *localtime(&rawtime);

Long term, better solution is to refactor this and use `std::chrono` in c++11 instead.

**Comment by butor** [comment]
Thank you @greatwolf for fix
