### ISSUE TITLE
Running as daemon

### ISSUE THREAD

**Issue by nordicgit70** [butor/blackbird#88]
Just installed blackbird and would prefer to have it running as a service.
If you are interested to have it running as service I could look into that.

**Comment by butor** [comment]
Hi @nordicgit70,

Thank you. What would be the advantage for a trading system like this one?

**Comment by nordicgit70** [comment]
Hi, 
the application already acts as service, as it runs headless without a UI.
making it a daemon would allow stop/start/restart/reload control.
it would run in the background managed by Linux run-levels.
e.g. automatic stop-start, without user involvement
//

**Comment by greatwolf** [comment]
This has to work under windows too if you're going to add this feature.

**Comment by pgray64** [comment]
You could use nohup for the time being.
