### ISSUE TITLE
Building on mac OSX - errors, resolved

### ISSUE THREAD

**Issue by thomasvangurp** [butor/blackbird#92]
I got several issues building blackbird on OS-X. All of these were easy to resolve. I used macports to install jansson. I had to modify the makefile, it now looks like this:

> Blackbird Bitcoin Arbitrage Makefile
override INC_DIR += -I ./src -I/usr/local/mysql-5.5.21-osx10.6-x86_64/include/ -I/opt/local/include/
override LIB_DIR += -L /opt/local/lib/ -L/usr/local/mysql-5.5.21-osx10.6-x86_64/lib/
CXXFLAGS := -g -Wall -pedantic -std=c++11 -O2 $(INC_DIR)
LDFLAGS  := -g $(LIB_DIR) -L/opt/local/include/
LDLIBS   := -lcrypto -ljansson -lcurl -lmysqlclient
EXEC = blackbird
SOURCES = $(wildcard src/*.cpp) $(wildcard src/*/*.cpp)
OBJECTS = $(SOURCES:.cpp=.o)
ifndef VERBOSE
  CC := @$(CC)
  CXX := @$(CXX)
endif
All: $(EXEC)
$(EXEC): $(OBJECTS)
	@echo Linking $@:
	$(CXX) $(LDFLAGS) $^ -o $@ $(LDLIBS)
%.o: %.cpp
	@echo Compiling $@:
	$(CXX) $(CXXFLAGS) -c $< -o $@
clean:
	rm -rf core $(OBJECTS

see [Makefile.txt](https://github.com/butor/blackbird/files/671891/Makefile.txt) 

Furthermore, I need to make sure that  libmysqlclient.18.dylib is linked in /usr/local/lib instead of in the default directory. 

`sudo ln -s /usr/local/mysql-5.5.21-osx10.6-x86_64/lib/libmysqlclient.18.dylib /usr/local/lib/libmysqlclient.18.dylib`

That's it. Maybe some of this can be build into the makefile specific for mac?

**Comment by butor** [comment]
Thank you @thomasvangurp for the details.

**Comment by greatwolf** [comment]
That's why I added the lines 

    override INC_DIR +=
    override LIB_DIR +=

in the makefile, precisely because different platforms have different locations of where to find the dependencies. You should specify it as part of the make command so the paths get appended without changing the makefile. eg.

    make INC_DIR="-I/usr/local/mysql-5.5.21-osx10.6-x86_64/include/ -I/opt/local/include/" LIB_DIR=" -L /opt/local/lib/ -L/usr/local/mysql-5.5.21-osx10.6-x86_64/lib/"

**Comment by thomasvangurp** [comment]
ok, @greatwolf you taught me something new :-) Will use these command line flags next time instead of modifying the Makefile.

**Comment by thomasvangurp** [comment]
@butor  you can close this issue I think.
