### ISSUE TITLE
Kraken $0

### ISSUE THREAD

**Issue by mtamer** [butor/blackbird#93]
I know Kraken is currently being validated, but has anyone got it to work? 

My log keeps printing this out.
` Kraken:	0.00 USD	0.000000 BTC`

Even though there is cash in there

**Comment by mtamer** [comment]
Got Kraken working.

**Comment by allenfrostline** [comment]
Hi mtamer, I'm new to this project and I got stuck with the problem of zero cash in my Kraken account (even though there is actually USD in it). Can you tell me how you managed that later? Thanks!

**Comment by mtamer** [comment]
Hey @allenfrostline , sorry for the late reply. 

I'm pretty sure their was no-to minimal change in code. 
Is it working with your other exchanges?
Also whats your cash in that account?

**Comment by allenfrostline** [comment]
Hi @mtamer , I have another exchange set in the configuration, Bitfinex, and the cash display of that account is totally normal. The problem only happens to Kraken.

**Comment by BayesStreet** [comment]
If anyone is having this problem I solved it by regenerating an API key.

**Comment by allenfrostline** [comment]
@BayesStreet Thanks for the reply! I'll check it out right away.
