### ISSUE TITLE
Short order on Kraken

### ISSUE THREAD

**Issue by orator99** [butor/blackbird#95]
Hey all,
is there are particular reason why short orders on Kraken are not implemented? If not, I would start to work on it.

All the best,
Orator

**Comment by butor** [comment]
Unlike Bitfinex, on Kraken the short selling is more complicated and takes more steps, which add risks.

Unless it changed recently, on Kraken you need to first call functions to borrow the bitcoins you need, then once you get them you can sell them on the market. These are separated steps.

We should do a little research, but I'm not sure whether this is feasible using only the [
Kraken API](https://www.kraken.com/help/api).

Thanks

**Comment by orator99** [comment]
I believe this is explained in https://support.kraken.com/hc/en-us/articles/218741078-What-is-settling-a-position-and-how-do-I-do-it-
(and the end there is a link to the API calls which indicates that only one call is needed)

Another complication is that at least in the kraken web frontend (correct me if I'm wrong) one can only short trade using a leverage which will complicate the implementation.

**Comment by orator99** [comment]
The link was not exactly what I ment to send. Anyway I believe that sending a sell order together with a leverage via the api should do it. Do you agree?

**Comment by butor** [comment]
I agree that's the best way to implement it. Since you want to be market neutral at all times, the whole process should be quick enough to immediately hedge the "buy" order on the other exchange.
