### ISSUE TITLE
Question: shorting on bitfinex

### ISSUE THREAD

**Issue by ferencdg** [butor/blackbird#97]
Hi, thanks for this great project, I have some questions, suggestions:

1. normally if you short a stock, you need to pay daily interest rate on the amount you borrow: you borrowed the stock, so you pay to the one you borrowed it from. Do you need to pay some interest on bitfinex, if you short bitcoin?

2. the demo mode is very useful, but it would be great to calculate the profit while running the blackbird in demo mode: maybe the assumption could be that the limit orders are filled at the limit price, so the profit could be calculated. I think some people like me are just interested roughly how much return you can expect, but don't own any bitcoin yet to be able to try the real trading.

thanks

**Comment by butor** [comment]
Hi @ferencdg,

> normally if you short a stock, you need to pay daily interest rate on the amount you borrow: you borrowed the stock, so you pay to the one you borrowed it from. Do you need to pay some interest on bitfinex, if you short bitcoin?

Yes you are correct, you need to pay a daily interest rate for the borrowed bitcoins. The rates are pretty low, specially when the arbitrage opportunities are short (minutes or hours). So it can be estimated under the exchange fees (e.g. parameter `BitfinexFees` for Bitfinex).
That being said, it would be more accurate to use a separated parameter for that, computed directly from the actual rate. This would be specially useful for long arbitrage opportunities (days).

> the demo mode is very useful, but it would be great to calculate the profit while running the blackbird in demo mode: maybe the assumption could be that the limit orders are filled at the limit price, so the profit could be calculated. I think some people like me are just interested roughly how much return you can expect, but don't own any bitcoin yet to be able to try the real trading.


I think this is a great idea: enhancement issue #99 to keep track of that idea. Thanks.
